### ISSUE TITLE
ut on fairphone 2: program stalls asking for bootloader mode

### ISSUE THREAD

**Issue by samlestrade** [ubports/ubuntu-touch#1012]
- Device: fairphone 2 with android 6.0.1 (installer via macos)
- Build: FP2-gms-18.04.1

### Steps to reproduce
instructions from ubports website

### Expected behavior
proceed with installation after selection of device

### Actual behavior
installation stalls, asks for bootloader mode (which it is in already)

### Logfiles and additional information
seems similar to known issues, but cannot find solution there. tried older versions of installer (20 and 19) and switching off network, but that doesn't work.

**Comment by UniversalSuperBox** [comment]
Hello @samlestrade!

That does sound similar to other issues that have been filed, but we prefer to help people install Ubuntu Touch in one of our real-time chatrooms... You can find the install help group at @WelcomePlus on Telegram, otherwise we are in #ubports on freenode or #ubports:matrix.org on Matrix.

Since this is a question post and I think the actual issue is filed somewhere else, I'll close this for now.
