### ISSUE TITLE
Called number not seen in call log only contact name

### ISSUE THREAD

**Issue by mgresko8** [ubports/ubuntu-touch#1035]
### Description of the feature
When browsing through call log I am not able to see the number, only the contact name. It is very annoying when having more then one number added to the contact. If I called the same contact more time to different numbers, I am not able to select to repeat the call by number of the same contact from the call log.

I am pretty sure the feature was here added by Canonical on my request and somebody removed it.

- Device: BQ Aquaris E4.5
- Channel: stable
- Build: OTA-6

### Steps to reproduce
Call (or receive call) to the same contact, but on different numbers. You are not able to see the numbers in the call log.

### Expected behavior
Being able to see contact name along with the called number in call log.

### Actual behavior
You are only able to see the contact name in the call log.

**Comment by Gabriele69** [comment]
The call information is actually present. It's necessary to scroll to the left the contact that interests you in the call log (incoming or outgoing) and click on the "info" symbol. It is certainly not practical, but it is the way to get the most complete information, since the register groups the incoming and outgoing calls to / from the same user.

**Comment by mgresko8** [comment]
Nope, it was there in the past. But it was removed. When I scrll to
left and click the info symbol I see only the name and not the number
nowadays. Why it was removed?

2019-03-08 16:33 GMT+01:00, GIEMME <notifications@github.com>:

**Comment by brickeddroid** [comment]
Hi guys, i am a total newbie to the github thing, so correct me if I am totally wrong here. 
But i have three suggestions to may enhance this issue. 
I don't know, if I had to make three different pull requests but I thought it would be better to discuss them first before i make a pull request?!

All suggestions are for the dialer-app/src/qml/HistoryPage/HistoryDetailsPage.qml

1) pass an additional boolean parameter `prioName` to the getFormattedPhoneLabel function

then in line 46:
` } else if (prioName && contactWatcher.alias != "") {`

line 56:
` title: getFormattedPhoneLabel(phoneNumber, true)`

and line 144:
` text: getFormattedPhoneLabel(phoneNumber, false)`


2) maybe a cleaner way would be to "copy" the getFormattedPhoneLabel function and invert the range of the checks


3) or additional to suggestion 1 or 2 add a completely new label, maybe like it was in former versions

**Comment by Gabriele69** [comment]
> Nope, it was there in the past. But it was removed. When I scrll to left and click the info symbol I see only the name and not the number nowadays. Why it was removed? 2019-03-08 16:33 GMT+01:00, GIEMME <notifications@github.com>:
> […](#)
> The call information is actually present. It's necessary to scroll to the left the contact that interests you in the call log (incoming or outgoing) and click on the "info" symbol. It is certainly not practical, but it is the way to get the most complete information, since the register groups the incoming and outgoing calls to / from the same user. -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#1035 (comment)](https://github.com/ubports/ubuntu-touch/issues/1035#issuecomment-470969256)

Sorry, it's true. I didn't realize that the information did not include the number of the caller.
Having the number could be useful if the caller has more than one phone number

**Comment by Flohack74** [comment]
@brickeddroid you can go ahead with your PRs, its anyways better to see on the living thing how it works (or not).

**Comment by ChristianPauly** [comment]
This behavior is in fact the same like on my iPhone. You only see the phone number if the contact is **not** in your addressbook. I guess this is a UX design decision. Non-techy people don't care about digital addresses like phone numbers. They type them in once with a name and then associate the contact only with a name and not with a phone number anymore. Since I have a smartphone I don't recognize the phone number of my mother anymore so the contact name + the info whether the phone number type is "mobile" or "work" is much more important here for the end-user.

**Comment by jonnius** [comment]
I can confirm that I see the number of callers in info menu on left swipe, RC, FP2.

**Comment by Bolly** [comment]
I can confirm that I see the number of callers in info menu on left swipe, RC, BQe4.5
