### ISSUE TITLE
App scaling is wrong on external displays

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#1095]
- Device: Nexus 5
 - Channel: Edge
 - Build: 16.04 (2019-04-10/2)

### Steps to reproduce
1. Connect the device to an external display i.e. Nexus 5 via slimport adapter
2. Open apps.

### Expected behavior
The apps should scale proportionate to the Unity 8 shell.

### Actual behavior
The apps are scaled bigger than the scaling of the Unity 8 shell.

**Comment by kugiigi** [comment]
An interesting discovery that might help uncovering this regression mystery.
When app is dragged in an area on the right side, the scaling suddenly becomes correct.
The division of where the scaling is correct and incorrect is along the left side of the settings-app. Moving that app slightly to the left will make it bigger.

![screenshot20190531_230219609](https://user-images.githubusercontent.com/29456786/58716641-06c3c000-83fc-11e9-8451-ea5510d6074c.png)

**Comment by UniversalSuperBox** [comment]
It appears that the left 1200 pixels of the screen are treated as the device screen rather than the external screen. Since you're testing on the Nexus 7 in this image (confirmed out-of-thread), it's possible that we aren't updating our display geometry and are treating a 1200x1920 area (starting from the top left corner) as device screen. The area where the device screen doesn't overlap with the monitor is the only area treated as having monitor-size scaling.

![demo2](https://user-images.githubusercontent.com/21966173/58741542-afaff200-83df-11e9-8af4-44dbff877cff.png)

It's cool that we can handle different scale factors between multiple monitors, though. Might we be the only DE like that?

**Comment by luksus42** [comment]
For FP2 on RC, the initial app scaling is still wrong.
When I rescale an app-window to more width than height and close it afterwards, the app scaling is correct next time, the app gets started.

**Comment by UniversalSuperBox** [comment]
The report https://github.com/ubports/ubuntu-touch/issues/1343 is more accurate to the new issue. In this report, apps would always be in the incorrect scaling if they were to the left of the display. Now, they initially open incorrectly and can be adjusted with workarounds.

**Comment by Bolly** [comment]
Work for me. 
BQM10FHD on RC.
