### ISSUE TITLE
Delayed app spread animation

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#1121]
- Device: Nexus 5
- Channel: Edge

### Steps to reproduce
1. Slowly swipe from the right edge to open the app spread.

### Expected behavior
The app spread comes out with smooth animation following the swipes momentum and position.

### Actual behavior
The animation kicks in a bit delayed when the swipe is almost an inch from the edge.
A jump in animation seems to occur.

**Comment by UniversalSuperBox** [comment]
There are a couple things to unpack here.

Prior to the drop of Unity8, it appears the Stage was transitioning to a more declarative style from its previous imperative style. This moves a lot of the logic into bindings from scripts, and therefore into Qt internals rather than our JavaScript.

During this time, Design may have asked that the animations change for a short swipe. Where before the animation would have the seen the [application flipping in](https://imgur.com/a/ZzEfGd8), now they slide in (I'd love to take a video of that, but mirscreencast is being super weird on edge and it doesn't run fast enough through X forwarding to show it).

The animations that were playing were halfway between the imperative and declarative style, and they were halfway between designs. The old app fades out, comes back to full opacity, *then* gets hidden by the other app sliding over it. If the Spread is about to appear, the new app flips in and then all of the other animations play on top of it. It just looks silly.

But, to get to the meat of this issue, I think we're actually hitting against a performance problem. You'll notice that in the Stage's [stagedRightEdge state](https://github.com/ubports/unity8/blob/xenial_-_edge/qml/Stage/Stage.qml#L504), we're binding 15 properties at the same time. Not only that, but each binding has a bit of JavaScript behind it.

By placing some expert `console.log()`s (one `onStateChanged` in Stage.qml, one `onProgressChanged` in StagedRightEdgeMaths.qml), I was able to see that we switch to the stagedRightEdge state instantly upon Unity8 realizing that we've started dragging. Then we wait a bit... and then `StagedRightEdgeMaths`' progress property gets updated, bringing the Spread animation in. This is what makes me think our bindings are the problem... it just takes a while for all of those things to fire.

As for where to go next, I'm not sure yet. I've pushed https://github.com/ubports/unity8/commit/e817a492627d6bce5a9f6d43cc42ff03a4d59bfd to start sorting out what's going on here. It removes most of the imperative animations and goes fully toward the declarative model. Problem is, this removes the animations for "start to drag in the Spread, then stop and let go" where the app flips in AND focusing an app from the Spread. I think I can resolve this and make everything work the Declarative Way:tm:.

**Comment by UniversalSuperBox** [comment]
The delayed animation has been fixed by https://github.com/ubports/unity8/pull/175. However, the app switch animations still play all over each other.

**Comment by luksus42** [comment]
I have noticed a much more smoother feeling when using the phone, thanks for this.

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/unity8/pull/202 (FINALLY)
