### ISSUE TITLE
Today's edge channel update for krillin makes it unbootable

### ISSUE THREAD

**Issue by advocatux** [ubports/ubuntu-touch#1126]
- Device: BQ E4.5 (krillin)
- Channel: edge
- Build: version 69 / Update date: 2019-05-02

### Steps to reproduce
Install today's edge channel update for krillin

### Expected behavior
The OS works

### Actual behavior
Device can't boot, it gets stuck on the boot logo screen

### Logfiles and additional information
I tried to get some more info but I can only get the `iSerial ID` of my device. No `telnet` or `ssh` are possible

**Comment by zubozrout** [comment]
Same applies to Meizu MX4. Stuck on the white bootloader screen.

**Comment by FardaleM** [comment]
Same applies to Nexus 4.

**Comment by UniversalSuperBox** [comment]
Oh, no. That was a really dumb mistake on my part.

I merged https://github.com/ubports/ubuntu-touch-session/pull/7, which made the xenial version of the session newer than the xenial_-_edge. There are some edge-only fixes that need to be applied or this happens. Should be fixed by https://github.com/ubports/ubuntu-touch-session/commit/c2da06e7caa72b441e71e7088f1e61259796b239, I'll push a new release of edge after it builds.

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/ubuntu-touch-session/commit/c2da06e7caa72b441e71e7088f1e61259796b239

**Comment by UniversalSuperBox** [comment]
If your device is affected and you have developer mode enabled, you can run `adb shell system-image-cli -v  --progress=dots` to download a new image. If your device cannot connect to a Wi-Fi network or developer mode is not enabled, you will need to use the UBports Installer to reinstall devel, then move to edge again.
