### ISSUE TITLE
Touch screen is responding partially during/after phone call.

### ISSUE THREAD

**Issue by Thieb67k** [ubports/ubuntu-touch#1142]
### Description of the feature
The touch screen is often (that can happens several times a day!) not responding.
Two behaviours:
- (#991 ) After a phone call, I can hang up but can not right-left swipe. (That is to say I can not go to the scope.). Yet the left-right swipe movement still works with the notification bar.
 I must restart to go back to a normal behaviour.
- During a phone call the touch screen is not responding at all. I can not even hang up or select choices when calling a server.

- Device: LG Nexus 4 mako
- Channel: stable
- Build: OTA-8-->OTA10

### Steps to reproduce
Random...

### Expected behavior
Touch screen responding after phone call.

**Comment by UniversalSuperBox** [comment]
@Thieb67k,

In order to solve problems like this we will need some steps which can be used to reproduce it. Between your report #991 and this (with no confirmations from others), I suspect your Nexus 4 has hardware problems causing it to fail to register touch on the sides of the screen, or sometimes on the whole screen. To check this you can download [finger painting](https://open-store.io/app/finger-painting.bhdouglass) from the OpenStore. Using it will let you see where touch is or is not responsive.

It is very common for the battery in the Nexus 4 to swell, causing damage to the front or back glass or pressing up against electronics and affecting their operation. This problem gets increasingly worse as the devices age (as it is a design feature of Lithium Ion batteries).

We'll leave this report open for a week to see if anyone else is having the same problem (which would prove it is a software and not a hardware issue). If not, we'll close both this and #991 as hardware issues.

**Comment by Thieb67k** [comment]
The thing is that happens at the exact same step, during or just after a phone call.
I never experienced that with another step, gesture, app access, etc.
The squeezed electronics would be affected only with a precise condition? Strange but why not.
I can try the finger painting App.
Moreover one week before closing the issue is a bit short. One of my issue was confirmed several weeks after publication.

**Comment by Thieb67k** [comment]
@UniversalSuperBox ,
As you recommended me to try the finger painting app, so far, it is working well. Each cm² of the screen respond very nicely.

**Comment by Thieb67k** [comment]
I close this issue because too close to #991, which is more detailed and up to date...
