### ISSUE TITLE
Adapt to Google requirements for syncing data after July 15th 2019

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-touch#1171]
### Google gives us the kick
Since a few days users get strange warning emails from Google about the "Ubuntu" app being limited in functionality after July 15th 2019. Work out what needs to be done to prevent any loss of sync connectivity here.
 see also [this link](https://arstechnica.com/gadgets/2019/06/gmails-api-lockdown-will-kill-some-third-party-app-access-starting-july-15/)

**Comment by dobey** [comment]
I think "fixing" this, just means changing the Google accounts code to not request access to gmail stuff via OAuth 2 token.

**Comment by UniversalSuperBox** [comment]
This is our current understanding of the situation:

After the July 15th deadline is reached, users should not lose access to any Google account data stored on their Ubuntu Touch device. Only GMail access is being denied, which the system does not use. Contacts and calendar sync should continue normally. 

There has been confusion about the GMail webapp which may use these permissions, but it seems it will continue to work. If it does not, even creating a new key will not help since we will need special permission from Google to continue using this data.

We are in the process of creating a new OAUTH token for Ubuntu Touch. This token will request access to the data that Ubuntu Touch needs, which does NOT include GMail. Having this token created for ourselves is to allow us to have control over our Google integration.

We are currently waiting for Google to approve our request for these credentials.

We are unsure if users will need to log in to their Google account again when the new token is put into place.

This issue does NOT need to be fixed before OTA-10 may be shipped. The key we inherited from Canonical will continue to work, albeit without access to GMail data.

**Comment by mardy** [comment]
I confirm that this does not affect the Gmail Webapp at all: it would affect the old GMail webapp by Canonical (that one had some sort of integration with Online Accounts), but the "GMail UT" application -- which is the only gmail application I can find in the OpenStore -- does not use Online Accounts.

**Comment by Flohack74** [comment]
Ok so we can close here? Or remove this one from OTA-10 but leave it open for changing the API key what we should do anyways.

**Comment by mardy** [comment]
I suggest removing the OTA-10 tag, but keep this open.

**Comment by UniversalSuperBox** [comment]
Will be fixed by https://github.com/ubports/account-plugins/pull/33

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/account-plugins/pull/33

**Comment by jezek** [comment]
There is OTA10 call for testing in progress. How can we test this?

**Comment by UniversalSuperBox** [comment]
This can be tested by adding a Google account to your device.

**Comment by jezek** [comment]
FP2 (2019-W32) - Fixed

Note: After update, calendar won't synchronize. I had to remove google account and add new one from scratch. Any changes between update & setting new account are lost.
