### ISSUE TITLE
[M10HD] [Camera] Wrong Orientation

### ISSUE THREAD

**Issue by cibersheep** [ubports/ubuntu-touch#1180]
This is a follow up from [Telegram conversation](https://t.me/ubports_qa_team/17814):

![imatge](https://user-images.githubusercontent.com/6640041/60937659-78cbd680-a2d1-11e9-922b-22d9d2a3dbe8.png)

Device: M10HD
- lastest Dev
- Camera 3.1.0

camera_orientation 
```
This device is: Aquaris M10 HD Ubuntu Edition

According to libhybris, this device has 2 camera(s).
Camera 0: facing = 0, orientation = 0.
Camera 1: facing = 1, orientation = 0.

According to QT, this device has 2 camera(s).
Camera 0: position() = 1, orientation() = 0
Camera 1: position() = 2, orientation() = 0
```

/etc/ubuntu-touch-session.d/android.conf
```
GRID_UNIT_PX=8
QTWEBKIT_DPR=1.0
NATIVE_ORIENTATION=landscape
FORM_FACTOR=tablet
```

X-Ubuntu-Rotates-Window-Contents with device on Main orientation (landscape)

![imatge](https://user-images.githubusercontent.com/6640041/60937690-a0bb3a00-a2d1-11e9-91c2-9b097ab4f68c.png)

Update:
[X-Ubuntu-Rotates-Window-Contents 1.2.0](https://junk.peat-network.xyz/ubports/xyz.peat-network.qml-orientation-demo/xyz.peat-network.qml-orientation-demo_1.2.0_armhf.click) shows:

![imatge](https://user-images.githubusercontent.com/6640041/61092104-31665700-a445-11e9-98b4-03c0ee5c3837.png)

**Comment by Wolfi0815** [comment]
On my Aquaris E5 the rear camera view is upside down. Version 3.1.0

**Comment by UniversalSuperBox** [comment]
@Wolfi0815, are you on stable OTA-9? If so, you may have been offered camera 3.1.0 erroneously. You can install the click from https://gitlab.com/ubports/apps/camera-app/-/jobs/250050092/artifacts/browse/build/, which is built from some source from right before the change, instead. Note that this is an unreleased build, but it should get you going again.

Otherwise, please file a new bug to track this issue. Thanks!

**Comment by Wolfi0815** [comment]
Hi Dalton,
thank you so much. My camera is back alive.
Wolfi

**Comment by mariogrip** [comment]
Fixed. Fix is in devel now :)
