### ISSUE TITLE
Libertine apps don't show up keyboard on input field focus

### ISSUE THREAD

**Issue by zubozrout** [ubports/ubuntu-touch#1192]
- Device: Meizu MX4 (arale)
- Channel: edge
- Build: any

### Steps to reproduce
Open any GUI application via Libertine and click on an input field. Unlike on current stable/rc/devel the keyboard won't show up.

### Expected behavior
Keyboard pops up on input field focus.

### Actual behavior
Nothing happens on input field focus. Input is only possible via external keyboard or if running e.g. matchbox keyboard in the same window.

**Comment by balcy** [comment]
Another effect of this issue is, that no keyboard is shown in "LXTerminal". This was always handy to get the virtual keyboard there, if you have to external keyboard with you, and want to start a graphical libertine app not present in the launcher.
Would you assume the bug is in unity8, in mir, or in libertine itself ?

**Comment by UniversalSuperBox** [comment]
This issue is related to a patch carried by us on top of maliit-framework: https://github.com/ubports/maliit-framework-packaging/blob/0df5b5412e22e9c0b55a1645e5b8c1b26af776a5/debian/patches/0015-obey-unity8-focus.patch#L79

This patch ensures that an application has focus in Lomiri before actually showing the keyboard. If Lomiri does not attest to an application having focus, the keyboard is not shown and the following is logged:

```
WARNING: Application attempted to activate itself without focus, PID:  4806
``` 

Guess what gets logged when you try to focus an input in a Libertine application? :)

**Comment by UniversalSuperBox** [comment]
Closed by https://github.com/ubports/qtmir/pull/47

**Comment by balcy** [comment]
keyboard is back in lxterminal (libertine) on BQ Aquaris 4.5 (devel) 🎆

**Comment by lduboeuf** [comment]
It is too on N5. Note that unfortunatly, each typed letter spawn a new app instance and make the device easily unusable. ( tested with geany )

**Comment by zubozrout** [comment]
@lduboeuf I can reproduce that using Geany on Meizu MX4 arale, but Firefox for instance doesn't behave like that and works just fine for me.

**Comment by UniversalSuperBox** [comment]
For new issues, please open a new report.

**Comment by cibersheep** [comment]
On M10HD I had installed gargoyle (gtk app) before installing RC image.
Gargoyle has a file chooser, tapping on search the OSK doesn't show up.

![imatge](https://user-images.githubusercontent.com/6640041/77940682-580d3c00-72b9-11ea-8ae4-79480e1ab4f4.png)

**Comment by abkro** [comment]
N5 on RC. Tested with Geany and Pidgin. No keyboard pops up when you click in a text entry field.

**Comment by UniversalSuperBox** [comment]
Pull request https://github.com/ubports/qtmir/pull/47 was merged 4 days ago. This change will not reach rc until Wednesday. It can currently be tested in devel.

**Comment by abkro** [comment]
Tested today on N5 running RC 2020-W14. Tested with:
Geany
Gimp
Pidgin

All behaved as expected. The keyboard came up.

**Comment by cibersheep** [comment]
Fix works on M10HD
