### ISSUE TITLE
Broken online accounts fail silently

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubuntu-touch#1195]
- Device: *
- Channel: *
- Build: *

### Steps to reproduce

1. Create an online account (Google, Nextcloud, whatever)
1. Break the account's sync, such as by expiring its token (removing the device from your Google account, for example)

### Expected behavior

Something notifies me that my account has become invalid and asks me to log in again.

### Actual behavior

I get no notification of the bad account. All sync services silently fail.

### Logfiles and additional information

[sync-monitor](https://github.com/ubports/sync-monitor) is a rather old project for exactly this purpose. Indeed, it does its job acceptably. When the user manually initiates a sync in calendar-app, sync-monitor is called on to check authentication. If it fails, it pops up a notification asking the user to fix their account.

Unfortunately, this only happens manually. Maybe there was a plan for sync-monitor to become the hub for account sync requests. Maybe we could schedule sync-monitor to run automatically.

**Comment by UniversalSuperBox** [comment]
This bug is `critical (rc)` because releasing RC to Stable breaks everyone's Google account, they must reauthenticate. Needing to find that out manually is terrible UX.

The bug itself is likely much older, it is only critical when triggered this way.

**Comment by mardy** [comment]
I see, the synchronization stack is not totally clear to me :-) It looks like the reauthentication UI that was added in sync-monitor would be better triggered by some other component (buteo, maybe?), in order to capture all cases.

It might also be that this was a conscious decision by the UX designers in Canonical, since it's not clear what is the best way to warn the user that an automatic sync has failed. Emitting a notification every time that the background sync fails might lead to a storm of pending notifications :-) (even though that's indeed better than failing silently)

**Comment by UniversalSuperBox** [comment]
Well, sync-monitor has the state for that, it could easily track whether it's made a notification *on this boot* or *in the last 24 hours* and act accordingly.

**Comment by mardy** [comment]
Right.

Anyway, given that this is no longer that urgent (since you reverted the API key change), feel free to assign this to me, unless someone else wants to step in and fix this sooner.

**Comment by dobey** [comment]
Notifications for automatic sync fail (which also go away when sync succeeds again automatically) would be fine, assuming it tracks state to a single notification. Re-authorization should only happen from the notification if the failure was due to failed authorization, and I suppose the notification should have the appropriate URL attached in that case, so that it opens the right thing to perform that action.

**Comment by UniversalSuperBox** [comment]
The only time that sync-monitor notifies is on authentication failure, as far as I saw.

**Comment by UniversalSuperBox** [comment]
The merge of https://github.com/ubports/account-plugins/pull/34 removes the `critical (rc)` status from this issue. Please see [the OTA-10 call for testing](https://ubports.com/blog/ubports-blog-1/post/call-for-testing-ubuntu-touch-ota-10-238) for more details on OTA-10's release status.

**Comment by mardy** [comment]
Does the sync ever occur automatically? Who and when is calling `sync-monitor` to perform the calendar sync?

I can see that the sync happens when I disable and re-enable my account, but I haven't seen it happen in other cases.

**Comment by mardy** [comment]
OK, I've found at least one reason why this can happen: the authentication notification is triggered only if the account authentication fails, but most of the times the authentication token is read from the cache, so it's immediately considered as a success. The error comes later, when the `SyncAccount::fetchRemoteSources()` method is called, because the Google server is given an invalid token and it returns an error at that point.

The `sync-monitor` code should be changed to check for "unauthorized" error at every step, and trigger the reauthentication if needed.

**Comment by mardy** [comment]
Some issues were fixed in https://github.com/ubports/sync-monitor/pull/14. However, the main issue still persists.
In a branch of mine, I managed to get the notification shown when the authentication fails, but then if the manual sync fails one gets three (!) notifications. :-) The code is rather messy, I'm afraid this needs some refactoring.
