### ISSUE TITLE
Attaching keyboard to oneplus one

### ISSUE THREAD

**Issue by aclifton314** [ubports/ubuntu-touch#1275]
### System Info:

Device: Oneplus One (bacon)
OS: Ubuntu 16.04 (OTA 11)
Channel: Not sure how to get this information from the phone.

This is a complete newbie question. I'm fairly comfortable with linux and the command line, but I was wondering if it were possible to connect a physical keyboard to the device either through USB (and using the device screen) or through convergence (presumably using an HDMI cable and using a laptop screen) to enter commands in the command line, explore the device, etc.?

**Comment by PhoenixLandPirate** [comment]
Yes you can, you can do it via Bluetooth, or via a otg adapter.

You can't connect it using a hdmi cable however because the OPO doesn't support MHL, I believe OP only started supporting MHL out, in the OP7 line of devices.

Also for question based thoughts like this, please could you ask them either in the forums (forums.ubports.com) or one of the chats, be it Matrix, or telegram (https://matrix.to/#/!NrkQorBIyLCRuiynHA:matrix.org?via=matrix.org&via=ubports.chat&via=librem.one) (https://t.me/ubports)

**Comment by aclifton314** [comment]
@PhoenixLandPirate for sure. Apologies for posting to the wrong medium. Thanks for your response!
