### ISSUE TITLE
Update kernel to run Docker - Nexus 5, linux-image-3.4.0-1-hammerhead

### ISSUE THREAD

**Issue by ravikv123** [ubports/ubuntu-touch#1276]
### Description of the feature

Update kernel to run Docker - Nexus 5, linux-image-3.4.0-1-hammerhead
Iam unable to run docker on nexus 5, running ubuntu touch , with the below error
**time="2019-10-26T22:13:52.045791393+05:30" level=fatal msg="Your Linux kernel version 3.4.0-cyanogenmod-gc95a726 is not supported for running docker. Please upgrade your kernel to 3.10.0 or newer."**
any way I can update my kernel to 3.10.0 ? and any issues if i update ?

I saw  few instructions in the post: [Link](https://askubuntu.com/questions/119080/how-to-update-kernel-to-the-latest-mainline-version-without-any-distro-upgrade) ,  use the below commands to check avbl kernels and update
**apt-cache search linux-image
sudo apt-get install linux-image-your_version_choice linux-headers-your_version_choice linux-image-extra-your_version_choice**

Is it safe to update kernel? and wht version I can install if its ok..

### Illustrations

- Device: N5xus 5
- Channel: Stable 
- Build: OTA 11

**Comment by BlueKenny** [comment]
Hello,

The kernel for Phones are very different do the same situation on PCs,

For Phones, wich are arm or arm64 devices you need to compile / create a new kernel for each phone model. in such a Kernel there alot of device specific driver, that can't be easy ported to a new kernel version as there are Closed Source...

Hope you unterstand my Ugly English ;)

**Comment by ravikv123** [comment]
thanks @BlueKenny  for the info..
I will try [THIS LINK](https://github.com/masneyb/nexus-5-upstream#notification-settings) as last hope..
thankyou

**Comment by dobey** [comment]
No, Android kernels cannot be upgraded reliably to newer versions, due to the proprietary drivers which are required for the phone hardware, being only compiled for the specific kernel the device shipped with. Nexus 5 shipped with kernel 3.4 and Android 4.4, and so it is stuck with that kernel. Your options would be to backport whatever kernel features are needed to the 3.4 kernel, so that they could possibly be included, or to use a different OS which runs on upstream Linux kernel (though all hardware may not work in such case) such as postmarketOS.

I'm not sure what you're trying to do with docker on your phone either, but as a point of note, Ubuntu Touch is a phone OS, not a traditional PC Linux distribution, so it may not align with your goals. I'm going to close this, as we cannot upgrade the kernel to a newer version.
