### ISSUE TITLE
apt upgrade errors referencing lxc-android-config

### ISSUE THREAD

**Issue by aclifton314** [ubports/ubuntu-touch#1288]
- Device: Oneplus One
- Channel: 16.04/stable

I am unable to do `sudo apt upgrade` on my device. The errors seem to reference `lxc-android-config` and I can't seem to resolve them to do a system upgrade. Here is what I have done:

1. From a fresh install of ubuntu touch, I run `sudo apt update` in the terminal. There is an error that is thrown saying something like `cannot open file in /var/.../... read only system`. However, `sudo mount -o rw,remount /` appears to fix that.

2. `sudo apt update` then gives the `no sandbox user _apt` error. `sudo adduser _apt --force-badname` and filling in the details (with nonsense) seems to fix that.

3. `sudo apt update` then works with no more errors. However, `sudo apt upgrade` gives an error saying something `there is not enough space on /var/cache/apt/archives`. Doing 
`sudo mv -i /var/cache/apt /userdata`
`sudo ln -s /userdata/apt /var/cache/apt`
resolves the space issue but then I start running into errors referencing lxc-android-config.  I get something like `E: subprocess /usr/bin/dpkg returned error  code (1). Errors encountered while processing /var/cache/apt/archives/lxc-android-config_0.232 blah blah blah .deb`

I've tried a few things just from searching to no avail and was wondering if anyone had any recommendations on how to resolve this? Thanks in advance.

**Comment by Flohack74** [comment]
Hello,
apt upgrades are not supported on the phone, because, as you saw, you run into a lot of issues with that. Phones are not PCs, and for stability reasons all system updates must come via an OTA offline upgrade. For developers it is still useful sometimes to install single pacakges with apt, but it is nothing you would do on a weekly basis.

The reason for all this is: limitation of size of partitions and write-access: Basically the whole system is read-only for safety reasons. Folders that eventually need write access are bind-mounted into a separate area. So for example even if you set read-write to the / path, you will run out of disk space since / is mounted on rootfs.img file which is limited in size.

If you want to try out certain packages (QA or dev scenario), you can follow the way you explored, but do not do apt upgrade just so.

**Comment by aclifton314** [comment]
Hi @Flohack74. Thank you for your response. It makes sense to me. Closing this issue.
