### ISSUE TITLE
Failed to power up wifi chip

### ISSUE THREAD

**Issue by Pdbrantley** [ubports/ubuntu-touch#1351]
- Device: Nexus 5 (hammerhead) LG-D820
- Channel: ubports-touch/16.04/devel
- Build: 2020-01-18

### Steps to reproduce
Problem is constant.
Anbox is not installed
**This is a new (to me) device, and I think this is most likely a hardware issue, but I would like someone to confirm.**

### Expected behavior
Wifi should power up, and show a list of networks to connect to.

### Actual behavior
Wifi adapter not detected in settings. No switch is show to turn on wifi.

### Logfiles and additional information
**Relevant Dmesg:**
```
[   10.436771] bcm_wifi_set_power: wifi power successed to pull up
[   10.638079] wifi_set_carddetect = 1
[   10.638093] wcf_status: wifi_detect = 1
[   10.638098] mmc0: Slot status change detected (0 -> 1)
[   10.671382] mmc0: msmsdcc_switch_io_voltage: MCIDATIN_3_0 is still not all zeros
[   12.638089] failed to power up wifi chip, retry again (4 left) **

[   12.638257] ## wifi_remove
[   12.638262] wifi_set_power = 0
[   12.638265] WiFi: trying to acquire BT lock
[   12.638269] ####btlock acquired cookie: WiFi
[   12.638273] bcm_wifi_set_power: btlock acquired
[   12.638322] ####btlock released, cookie: WiFi
[   12.649302] mmc0: error -110 whilst initialising SDIO card
[   13.163506] bcm_wifi_set_power: wifi power successed to pull down
[   13.163514] wifi_set_carddetect = 0
[   13.163524] wcf_status: wifi_detect = 0
[   13.163528] mmc0: Slot status change detected (1 -> 0)
[   13.236717] wifi_set_power = 1
[   13.236724] WiFi: trying to acquire BT lock
[   13.236728] ####btlock acquired cookie: WiFi
[   13.236733] bcm_wifi_set_power: btlock acquired
[   13.236799] ####btlock released, cookie: WiFi
[   14.535267] bcm_wifi_set_power: wifi power successed to pull up
[   14.738042] wifi_set_carddetect = 1
[   14.738059] wcf_status: wifi_detect = 1
[   14.738064] mmc0: Slot status change detected (0 -> 1)
[   14.770534] mmc0: msmsdcc_switch_io_voltage: MCIDATIN_3_0 is still not all zeros
[   16.738028] failed to power up wifi chip, retry again (3 left) **

[   16.738255] ## wifi_remove
[   16.738260] wifi_set_power = 0
[   16.738263] WiFi: trying to acquire BT lock
[   16.738268] ####btlock acquired cookie: WiFi
[   16.738271] bcm_wifi_set_power: btlock acquired
[   16.738320] ####btlock released, cookie: WiFi
[   16.749828] mmc0: error -110 whilst initialising SDIO card
[   17.146417] type=1400 audit(35353775.409:3): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/lib/lightdm/lightdm-guest-session" pid=1267 comm="apparmor_parser"
[   17.147979] type=1400 audit(35353775.409:4): apparmor="STATUS" operation="profile_load" profile="unconfined" name="chromium" pid=1267 comm="apparmor_parser"
[   18.832724] bcm_wifi_set_power: wifi power successed to pull down
[   18.832747] wifi_set_carddetect = 0
[   18.832760] wcf_status: wifi_detect = 0
[   18.832765] mmc0: Slot status change detected (1 -> 0)
[   18.919047] wifi_set_power = 1
[   18.919064] WiFi: trying to acquire BT lock
[   18.919073] ####btlock acquired cookie: WiFi
[   18.919077] bcm_wifi_set_power: btlock acquired
[   18.919154] ####btlock released, cookie: WiFi
[   20.239947] type=1400 audit(35353778.509:5): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/sbin/dhclient" pid=1620 comm="apparmor_parser"
[   20.241448] type=1400 audit(35353778.509:6): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/lib/NetworkManager/nm-dhcp-client.action" pid=1620 comm="apparmor_parser"
[   20.242537] type=1400 audit(35353778.509:7): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/lib/NetworkManager/nm-dhcp-helper" pid=1620 comm="apparmor_parser"
[   20.243626] type=1400 audit(35353778.509:8): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/lib/connman/scripts/dhclient-script" pid=1620 comm="apparmor_parser"
[   21.134724] init: bluetooth-touch-hammerhead main process (1090) terminated with status 1
[   21.151161] init: bluetooth-touch main process (1082) terminated with status 1
[   22.424391] bcm_wifi_set_power: wifi power successed to pull up
[   22.628079] wifi_set_carddetect = 1
[   22.628094] wcf_status: wifi_detect = 1
[   22.628098] mmc0: Slot status change detected (0 -> 1)
[   22.660361] mmc0: msmsdcc_switch_io_voltage: MCIDATIN_3_0 is still not all zeros
[   24.468817] [rmnet0] error: rmnet_ioct called for unsupported cmd[35585]
[   24.469168] [rmnet1] error: rmnet_ioct called for unsupported cmd[35585]
[   24.469631] [rmnet2] error: rmnet_ioct called for unsupported cmd[35585]
[   24.469927] [rmnet3] error: rmnet_ioct called for unsupported cmd[35585]
[   24.470251] [rmnet4] error: rmnet_ioct called for unsupported cmd[35585]
[   24.531305] [rmnet5] error: rmnet_ioct called for unsupported cmd[35585]
[   24.531636] [rmnet6] error: rmnet_ioct called for unsupported cmd[35585]
[   24.531969] [rmnet7] error: rmnet_ioct called for unsupported cmd[35585]
[   24.532377] [rev_rmnet0] error: rmnet_ioct called for unsupported cmd[35585]
[   24.532710] [rev_rmnet1] error: rmnet_ioct called for unsupported cmd[35585]
[   24.533055] [rev_rmnet2] error: rmnet_ioct called for unsupported cmd[35585]
[   24.628074] failed to power up wifi chip, retry again (2 left) **

[   24.628394] ## wifi_remove
[   24.628399] wifi_set_power = 0
[   24.628403] WiFi: trying to acquire BT lock
[   24.628407] ####btlock acquired cookie: WiFi
[   24.628410] bcm_wifi_set_power: btlock acquired
[   24.628488] ####btlock released, cookie: WiFi
[   24.640204] mmc0: error -110 whilst initialising SDIO card
[   24.649646] [rev_rmnet3] error: rmnet_ioct called for unsupported cmd[35585]
[   24.649933] [rev_rmnet4] error: rmnet_ioct called for unsupported cmd[35585]
[   24.650215] [rev_rmnet5] error: rmnet_ioct called for unsupported cmd[35585]
[   24.650551] [rev_rmnet6] error: rmnet_ioct called for unsupported cmd[35585]
[   24.650857] [rev_rmnet7] error: rmnet_ioct called for unsupported cmd[35585]
[   24.651133] [rev_rmnet8] error: rmnet_ioct called for unsupported cmd[35585]
[   26.716028] bcm_wifi_set_power: wifi power successed to pull down
[   26.716125] wifi_set_carddetect = 0
[   26.716131] wcf_status: wifi_detect = 0
[   26.716135] mmc0: Slot status change detected (1 -> 0)
[   26.958225] wifi_set_power = 1
[   26.958233] WiFi: trying to acquire BT lock
[   26.958238] ####btlock acquired cookie: WiFi
[   26.958241] bcm_wifi_set_power: btlock acquired
[   26.958309] ####btlock released, cookie: WiFi
[   27.246870] type=1400 audit(35353785.509:9): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/sbin/dhclient" pid=1658 comm="apparmor_parser"
[   27.379045] type=1400 audit(35353785.649:10): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/sbin/dhclient" pid=1660 comm="apparmor_parser"
[   27.380480] type=1400 audit(35353785.649:11): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/lib/NetworkManager/nm-dhcp-client.action" pid=1660 comm="apparmor_parser"
[   27.381556] type=1400 audit(35353785.649:12): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/lib/NetworkManager/nm-dhcp-helper" pid=1660 comm="apparmor_parser"
[   27.382624] type=1400 audit(35353785.649:13): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/lib/connman/scripts/dhclient-script" pid=1660 comm="apparmor_parser"
[   27.507246] type=1400 audit(35353785.769:14): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/sbin/dhclient" pid=1674 comm="apparmor_parser"
[   27.508692] type=1400 audit(35353785.779:15): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/lib/NetworkManager/nm-dhcp-client.action" pid=1658 comm="apparmor_parser"
[   27.509789] type=1400 audit(35353785.779:16): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/lib/NetworkManager/nm-dhcp-helper" pid=1658 comm="apparmor_parser"
[   27.510851] type=1400 audit(35353785.779:17): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/lib/connman/scripts/dhclient-script" pid=1658 comm="apparmor_parser"
[   27.590989] type=1400 audit(35353785.859:18): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/sbin/dhclient" pid=1673 comm="apparmor_parser"
[   29.251973] bcm_wifi_set_power: wifi power successed to pull up
[   29.458049] wifi_set_carddetect = 1
[   29.458065] wcf_status: wifi_detect = 1
[   29.458069] mmc0: Slot status change detected (0 -> 1)
[   29.490484] mmc0: msmsdcc_switch_io_voltage: MCIDATIN_3_0 is still not all zeros
[   30.649760] init: apport-config main process (2260) terminated with status 1

[   31.458295] failed to power up wifi chip, retry again (1 left) **

[   31.458468] ## wifi_remove
[   31.458473] wifi_set_power = 0
[   31.458476] WiFi: trying to acquire BT lock
[   31.458480] ####btlock acquired cookie: WiFi
[   31.458484] bcm_wifi_set_power: btlock acquired
[   31.458567] ####btlock released, cookie: WiFi
[   31.470446] mmc0: error -110 whilst initialising SDIO card
[   31.691012] bcm_wifi_set_power: wifi power successed to pull down
[   31.691032] wifi_set_carddetect = 0
[   31.691037] wcf_status: wifi_detect = 0
[   31.691042] mmc0: Slot status change detected (1 -> 0)

[   31.693671] failed to power up wifi chip, max retry reached, exits **
```
**`nmcli -p g` shows:**
=============================================================
                    NetworkManager status
=============================================================
STATE      CONNECTIVITY  WIFI-HW  WIFI     WWAN-HW  WWAN    
-------------------------------------------------------------
connected  full          enabled  enabled  enabled  enabled 

**`nmcli -p d` shows:**
========================================================
                   Status of devices
========================================================
DEVICE  TYPE      STATE      CONNECTION                
--------------------------------------------------------
ril_0   gsm       connected  /310260974971847/context2 
sit0    iptunnel  unmanaged  --                        
lo      loopback  unmanaged  --  

**Edit**
Following advice in another thread, I disabled developer mode and rebooted. This allows the Wifi cars to power on, but it still does not show a list of networks and is not able to connect. Also this seems cause instability with the settings and browser apps.

nmcli -p d now shows:
 DEVICE TYPE STATE CONNECTION
ril_0 gsm disconnected 
wlan0 wifi unavailable
sit0 iptunnel unmanaged --
lo loopback unmanaged --

nmcli -p g shows:
STATE CONNECTIVITY WIFI-HW WIFI WWAN-HW WWAN
disconnected none enabled enabled enabled enabled

**Comment by rocket2nfinity** [comment]
Do you have anbox installed? There is a known bug with anbox that disables wifi.

 
 
  On Sat, Jan 18, 2020 at 11:16 AM, Pdbrantley<notifications@github.com> wrote:      
   - Device: Nexus 5 (hammerhead) LG-D820
   - Channel: ubports-touch/16.04/devel
   - Build: 2020-01-18

Steps to reproduce

Problem is constant.
This is a new (to me) device, and I think this is most likely a hardware issue, but I would like someone to confirm.

Expected behavior

Wifi should power up, and show a list of networks to connect to.

Actual behavior

Wifi adapter not detected in settings. No switch is show to turn on wifi.

Logfiles and additional information

Relevant Dmesg:
[   10.436771] bcm_wifi_set_power: wifi power successed to pull up
[   10.638079] wifi_set_carddetect = 1
[   10.638093] wcf_status: wifi_detect = 1
[   10.638098] mmc0: Slot status change detected (0 -> 1)
[   10.671382] mmc0: msmsdcc_switch_io_voltage: MCIDATIN_3_0 is still not all zeros
[   12.638089] failed to power up wifi chip, retry again (4 left) **

[   12.638257] ## wifi_remove
[   12.638262] wifi_set_power = 0
[   12.638265] WiFi: trying to acquire BT lock
[   12.638269] ####btlock acquired cookie: WiFi
[   12.638273] bcm_wifi_set_power: btlock acquired
[   12.638322] ####btlock released, cookie: WiFi
[   12.649302] mmc0: error -110 whilst initialising SDIO card
[   13.163506] bcm_wifi_set_power: wifi power successed to pull down
[   13.163514] wifi_set_carddetect = 0
[   13.163524] wcf_status: wifi_detect = 0
[   13.163528] mmc0: Slot status change detected (1 -> 0)
[   13.236717] wifi_set_power = 1
[   13.236724] WiFi: trying to acquire BT lock
[   13.236728] ####btlock acquired cookie: WiFi
[   13.236733] bcm_wifi_set_power: btlock acquired
[   13.236799] ####btlock released, cookie: WiFi
[   14.535267] bcm_wifi_set_power: wifi power successed to pull up
[   14.738042] wifi_set_carddetect = 1
[   14.738059] wcf_status: wifi_detect = 1
[   14.738064] mmc0: Slot status change detected (0 -> 1)
[   14.770534] mmc0: msmsdcc_switch_io_voltage: MCIDATIN_3_0 is still not all zeros
[   16.738028] failed to power up wifi chip, retry again (3 left) **

[   16.738255] ## wifi_remove
[   16.738260] wifi_set_power = 0
[   16.738263] WiFi: trying to acquire BT lock
[   16.738268] ####btlock acquired cookie: WiFi
[   16.738271] bcm_wifi_set_power: btlock acquired
[   16.738320] ####btlock released, cookie: WiFi
[   16.749828] mmc0: error -110 whilst initialising SDIO card
[   17.146417] type=1400 audit(35353775.409:3): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/lib/lightdm/lightdm-guest-session" pid=1267 comm="apparmor_parser"
[   17.147979] type=1400 audit(35353775.409:4): apparmor="STATUS" operation="profile_load" profile="unconfined" name="chromium" pid=1267 comm="apparmor_parser"
[   18.832724] bcm_wifi_set_power: wifi power successed to pull down
[   18.832747] wifi_set_carddetect = 0
[   18.832760] wcf_status: wifi_detect = 0
[   18.832765] mmc0: Slot status change detected (1 -> 0)
[   18.919047] wifi_set_power = 1
[   18.919064] WiFi: trying to acquire BT lock
[   18.919073] ####btlock acquired cookie: WiFi
[   18.919077] bcm_wifi_set_power: btlock acquired
[   18.919154] ####btlock released, cookie: WiFi
[   20.239947] type=1400 audit(35353778.509:5): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/sbin/dhclient" pid=1620 comm="apparmor_parser"
[   20.241448] type=1400 audit(35353778.509:6): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/lib/NetworkManager/nm-dhcp-client.action" pid=1620 comm="apparmor_parser"
[   20.242537] type=1400 audit(35353778.509:7): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/lib/NetworkManager/nm-dhcp-helper" pid=1620 comm="apparmor_parser"
[   20.243626] type=1400 audit(35353778.509:8): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/lib/connman/scripts/dhclient-script" pid=1620 comm="apparmor_parser"
[   21.134724] init: bluetooth-touch-hammerhead main process (1090) terminated with status 1
[   21.151161] init: bluetooth-touch main process (1082) terminated with status 1
[   22.424391] bcm_wifi_set_power: wifi power successed to pull up
[   22.628079] wifi_set_carddetect = 1
[   22.628094] wcf_status: wifi_detect = 1
[   22.628098] mmc0: Slot status change detected (0 -> 1)
[   22.660361] mmc0: msmsdcc_switch_io_voltage: MCIDATIN_3_0 is still not all zeros
[   24.468817] [rmnet0] error: rmnet_ioct called for unsupported cmd[35585]
[   24.469168] [rmnet1] error: rmnet_ioct called for unsupported cmd[35585]
[   24.469631] [rmnet2] error: rmnet_ioct called for unsupported cmd[35585]
[   24.469927] [rmnet3] error: rmnet_ioct called for unsupported cmd[35585]
[   24.470251] [rmnet4] error: rmnet_ioct called for unsupported cmd[35585]
[   24.531305] [rmnet5] error: rmnet_ioct called for unsupported cmd[35585]
[   24.531636] [rmnet6] error: rmnet_ioct called for unsupported cmd[35585]
[   24.531969] [rmnet7] error: rmnet_ioct called for unsupported cmd[35585]
[   24.532377] [rev_rmnet0] error: rmnet_ioct called for unsupported cmd[35585]
[   24.532710] [rev_rmnet1] error: rmnet_ioct called for unsupported cmd[35585]
[   24.533055] [rev_rmnet2] error: rmnet_ioct called for unsupported cmd[35585]
[   24.628074] failed to power up wifi chip, retry again (2 left) **

[   24.628394] ## wifi_remove
[   24.628399] wifi_set_power = 0
[   24.628403] WiFi: trying to acquire BT lock
[   24.628407] ####btlock acquired cookie: WiFi
[   24.628410] bcm_wifi_set_power: btlock acquired
[   24.628488] ####btlock released, cookie: WiFi
[   24.640204] mmc0: error -110 whilst initialising SDIO card
[   24.649646] [rev_rmnet3] error: rmnet_ioct called for unsupported cmd[35585]
[   24.649933] [rev_rmnet4] error: rmnet_ioct called for unsupported cmd[35585]
[   24.650215] [rev_rmnet5] error: rmnet_ioct called for unsupported cmd[35585]
[   24.650551] [rev_rmnet6] error: rmnet_ioct called for unsupported cmd[35585]
[   24.650857] [rev_rmnet7] error: rmnet_ioct called for unsupported cmd[35585]
[   24.651133] [rev_rmnet8] error: rmnet_ioct called for unsupported cmd[35585]
[   26.716028] bcm_wifi_set_power: wifi power successed to pull down
[   26.716125] wifi_set_carddetect = 0
[   26.716131] wcf_status: wifi_detect = 0
[   26.716135] mmc0: Slot status change detected (1 -> 0)
[   26.958225] wifi_set_power = 1
[   26.958233] WiFi: trying to acquire BT lock
[   26.958238] ####btlock acquired cookie: WiFi
[   26.958241] bcm_wifi_set_power: btlock acquired
[   26.958309] ####btlock released, cookie: WiFi
[   27.246870] type=1400 audit(35353785.509:9): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/sbin/dhclient" pid=1658 comm="apparmor_parser"
[   27.379045] type=1400 audit(35353785.649:10): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/sbin/dhclient" pid=1660 comm="apparmor_parser"
[   27.380480] type=1400 audit(35353785.649:11): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/lib/NetworkManager/nm-dhcp-client.action" pid=1660 comm="apparmor_parser"
[   27.381556] type=1400 audit(35353785.649:12): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/lib/NetworkManager/nm-dhcp-helper" pid=1660 comm="apparmor_parser"
[   27.382624] type=1400 audit(35353785.649:13): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/lib/connman/scripts/dhclient-script" pid=1660 comm="apparmor_parser"
[   27.507246] type=1400 audit(35353785.769:14): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/sbin/dhclient" pid=1674 comm="apparmor_parser"
[   27.508692] type=1400 audit(35353785.779:15): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/lib/NetworkManager/nm-dhcp-client.action" pid=1658 comm="apparmor_parser"
[   27.509789] type=1400 audit(35353785.779:16): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/lib/NetworkManager/nm-dhcp-helper" pid=1658 comm="apparmor_parser"
[   27.510851] type=1400 audit(35353785.779:17): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/lib/connman/scripts/dhclient-script" pid=1658 comm="apparmor_parser"
[   27.590989] type=1400 audit(35353785.859:18): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/sbin/dhclient" pid=1673 comm="apparmor_parser"
[   29.251973] bcm_wifi_set_power: wifi power successed to pull up
[   29.458049] wifi_set_carddetect = 1
[   29.458065] wcf_status: wifi_detect = 1
[   29.458069] mmc0: Slot status change detected (0 -> 1)
[   29.490484] mmc0: msmsdcc_switch_io_voltage: MCIDATIN_3_0 is still not all zeros
[   30.649760] init: apport-config main process (2260) terminated with status 1

[   31.458295] failed to power up wifi chip, retry again (1 left) **

[   31.458468] ## wifi_remove
[   31.458473] wifi_set_power = 0
[   31.458476] WiFi: trying to acquire BT lock
[   31.458480] ####btlock acquired cookie: WiFi
[   31.458484] bcm_wifi_set_power: btlock acquired
[   31.458567] ####btlock released, cookie: WiFi
[   31.470446] mmc0: error -110 whilst initialising SDIO card
[   31.691012] bcm_wifi_set_power: wifi power successed to pull down
[   31.691032] wifi_set_carddetect = 0
[   31.691037] wcf_status: wifi_detect = 0
[   31.691042] mmc0: Slot status change detected (1 -> 0)

[   31.693671] failed to power up wifi chip, max retry reached, exits **

nmcli -p g shows:
                NetworkManager status

=============================================================
STATE CONNECTIVITY WIFI-HW WIFI WWAN-HW WWAN

connected full enabled enabled enabled enabled

nmcli -p d shows:
               Status of devices

========================================================
DEVICE TYPE STATE CONNECTION

ril_0 gsm connected /310260974971847/context2
sit0 iptunnel unmanaged --
lo loopback unmanaged --

**Comment by Pdbrantley** [comment]
@rocket2nfinity No, all of the above output is without a box installed. 

But I also decided to flash the custom boot image and install anbox to see if there was any changes. There were not, and the same issues were still present.

**Comment by Pdbrantley** [comment]
Confirmed issue was due to hardware failure.
