### ISSUE TITLE
Error: systemimage: Error: Error: Failed to push file 0: Error: Push failed: out of space

### ISSUE THREAD

**Issue by Bassnote** [ubports/ubuntu-touch#1388]
This is a Nexus 7 tablet. I have tried on both wifi and the LTE, each download ended in errors
 

Thank you for wanting to file an issue! If you have a minute, please take the time to read our guide on writing a good bug-report:

    https://docs.ubports.com/en/latest/contribute/bugreporting.html

If not and you just want to get this over with, that's also quite alright. But please try to format your issue correctly, to make it easier for us to read. Below, we provide a template for a feature-request and a bug-report. Use common sense to determine what category your issue falls under and delete the template you don't need. Also, you don't need to stick to the templates under all circumstances. If you don't need a heading, remove it. If you think a new section will provide valuable information, add a new heading. We're not dogmatists, we're pragmatists who just want to be able to efficiently work with new issues.

--------------------------------------------------------------------------------
------------------------------------------------------------------------------->

### Illustrations

- Device:
- Channel:
- Build:

**Comment by UniversalSuperBox** [comment]
Hi @Bassnote, thanks for your report.

If you'd like help installing Ubuntu Touch on your Nexus 7, you can find us in the support section of forums.ubports.com or <at>WelcomePlus on Telegram. It sounds like you may have resized your device's cache partition at some point, causing it to be too small for installing Ubuntu Touch. The partition layout must be absolutely stock in order to install Ubuntu Touch on your device.

If you still aren't able to install Ubuntu Touch after following these steps, please find us at one of our support channels I mentioned before.
