### ISSUE TITLE
My last-minute WishList for the UT OTA 12 update

### ISSUE THREAD

**Issue by weh2002** [ubports/ubuntu-touch#1392]
My UbuntuTouch WishList

I am running UT 16.04 OTA 11 from 26.08.19 on a OnePlus One 64GB

-------------------------------------------------------------

1.) A password protected recovery shell that can backup/restore an image of the entire phone OS and data of all involved partitions or ROMs to/from an external OTG or SD card. The image files should optionally be password protected.

2.) An app to backup/restore any user-selected part of the filesystem to/from an external OTG or SD card, either as a 1-to-1 file copy or into a compressed archive. This would need to give the user the full elevated rights to do so for this process only.

3.) A seperate app for each of the following items, or rather within the app of each of the following items, to export/import the items to/from an external OTG or SD card:

all or selected Call Logs
all or selected SMSs
all or selected Emails (POP3 + IMAP?!)
all or selected Chats of various clients
all or selected WiFi connections saved
all or selected BlueTooth links saved
all or selected NearField links saved
all or selected GPS locations logged
 

4.) An SMS app that supports moving and grouping of individual SMSs or whole conversation threads into a subfolder to any level and allowing backup/restore of all or selected SMSs to/from an external OTG or SD card

5.) A POP3 Email app that supports moving and grouping of individual Emails or whole conversation threads into a subfolder to any level and allowing backup/restore of all or selected Emails to/from an external OTG or SD card

6.) An app launcher that allows free ordering of app icons across various pages and even creating a folder that holds a group of app icons

7.) Support for USB tethering, not only WiFi

8.) A way to make annymous calls, either using a pre-settable prefix via a speed dial key before clicking the person,s number in Contacts or typing a number on the dial pad. Or temporarily activating the hide-mode at the cell provider via a xxxx code

9.) A smaller phone numberpad area, but a larger area to display the person,s contact details on two rows below the phone number, which is almost too large. There seems to be no use/need for the alphabetic letters to be shown below the numbers anyway

10.) An input field without the little circle with an x inside on the right end, which deletes the whole input field. This sort of input field is found in the Contacts app to save the names + numbers and in the Writer app to save the document.

11.) I LOVE the way the Morph browser just saves any webpage to mhtml and pdf and how it adjusts the page layout to any level of focus and the fact that all the tabs get restored in the event of a crash (which did happen numerous times for what ever reason). But:

it should use the full screen width to display the web address of each open tab, not only half the screen width
it should display an image (thumbnail) of the webpage for each tab in the list, not only for the top tab
it should not move a tab to the top of the tab list after selecting it for viewing, but leave it in it,a original position
it should open new tabs next to (below) the tab in which it was called from, or let a user select whether it should be placed as first or last tab in the list
it should display the tab next to (above) the one that was just closed and not jump to the top tab
It should be able to open the webpages it saves as pdf or mhtml or open an appropriate default app

12.) A call-recording feature by tapping the internal likes of speaker+mic, activatable within the Phone app

13.) A screen+speaker recording feature by tapping the internal lines of speaker+screen, activatable from the pull-down menu

14.) A volume adjustment for app alert like calander and alarm-clock within the sound settings menu

15.) Additional app-permission controles for the use of the WiFi and BlueTooth transceivers

16.) A viewer that that displays all activities of system processes and app tasks that request or selfiniciate data transfer between CPU, RAM, Storage, USB, Cellular, WiFi, BT, GPS, Camera, Mic, Speaker, motion sensor, etc. It should alert for selectable activities and provide auto/manual process killing/blocking/freezing

17.) Dark Sceme for the Setting Menu and all other system windows

18.) Rotation to landscape for all system windows like Settings, pull-down menu, etc.

19.) A lower keyboard formfactor in landscape mode to see more of the app we,re typing into and a way to make apps even scrall the header out of the visible screen area, in oder to have more space on the screen to see the text we,re writing/reading

20.) A keyboard with arrow keys and a Cntrl key and apostroph key as part of the permanent layout. I,d rather use the space of the word-prediction for that and let the system underline (red) any misspellt word, to be tapped for word correction. Now, any misspellt word remains unmarked if not selecting a correct option before tapping the spacebar, which is not useful at all. A Cntrl key would be good for convergance, I imagine. And I,d rather swap the possition of comma with the apostroph, ie press long to get the comma and short to get the apostroph. It would be fair to make it a selectable option in the Settings menu.

21.) The funtion to select text for cut, copy, paste needs to be such that we don,t cover the text with our finger to still be able to navigate the cursor correctly. The flowting menu should be closable without having to rotate to landscape to find the close button. And the auto-select more/less/segment/all should work correctly. And in select/cut/copy/paste funtion, by long-pressing the spacebar, the arrow keys should make the cursor move one step for each short tap, and select one whole word after each other with a short interval inbetween. And a double tap should select to the end (left, right, top, bottom).

21.) I,m actually glad that UT does not use the harware+virtual keys below the dispay, because it causes less unexpected triggers while handling the phone, especially in the one-handed operation. But often it so hard to reach the top left corner where many windows place the back button. I have no good suggestion to this. I wonder if the part below the display also responds to left/right swipe. Maybe that would be a nice solution, as a simple touch would still not cause any triggering of unwanted actions.

22.) I love receiving status information by a short look at the LED. Presently, there is only a slowly blinking green LED. I,m not even clear about what it is indicating. A missed call, a received message, an app alert, an active cell connection, the battery status, or what? But It would be wonderful to allow the user to self-define a whole row of indicator functions by selecting the reason of indication along with a specific color and blinking frequency and interval.

Many many thanks! The only way I can say it is that you are saving my life!!!!
Thank you for all your hard work, skill and dedication!!! I need to learn so much more and have so many question around using this OS, but Im soooo greatful for having more privacy, freedom and aecurity this way!
Winfried

**Comment by ruedigerkupper** [comment]
LOL. That's a list for 10 years. More OTA22 than OTA12.
Thanks for your suggestions. If you want to see them realized in the long run, please file them with the respective issues. If there is no appropriate issue, please open one with the resp. application.

**Comment by UniversalSuperBox** [comment]
Hi @weh2002,

Thank you for your report. I'm glad that you're happy enough with Ubuntu Touch to have ideas for the future. :)

Doing a quick tally in my head, I suspect this wishlist would be a six-month to one-year venture for our full-time team of three to handle. Unfortunately, we cannot commit to this kind of list, in full or in part, in order to balance the needs of our full community. Unless, of course, you have a very large monetary windfall laying around to hire a team. As such, this request is not actionable (it cannot be easily understood, digested, and completed by a single person in up to a months' time), so I will close it.

I suggest you file your wishes as specific, focused requests on the corresponding repository. For example, morph-browser requests should be filed at https://github.com/ubports/morph-browser and keyboard requests at https://github.com/ubports/keyboard-component. Do not file your requests as a list like this, only singly actionable tickets which can be taken as a full request for work. Please provide examples of successful implementation of these ideas in other operating systems, if possible. At the very least, if you are requesting design changes, having a mockup of a way things *could* work to satisfy your request would be helpful.

Some of your requests in this list are things which, to my knowledge, have not been designed around by any operating system on Earth. For example, there are not many options to make the keyboard shorter on landscape screens. It would become very difficult to hit touch points.

Please note that a majority of work on Ubuntu Touch is done by unpaid volunteers who got involved because they wanted to see something change (just like you!). Many of them say they are "not a developer" even though they are working on things like this. If you would like to see most of the things on this list become a reality, you may need to be the one to pick up the text editor and implement them.

We're always here to help as much as we can, of course, so please do file actionable and singly-focused tickets on the appropriate policies. However, as stated, it's unlikely that you will receive an answer without providing some effort toward design or implementation.

Again, thanks so much for your interest in Ubuntu Touch.
