### ISSUE TITLE
No WiFi switch nor connection on N5 (hammerhead)

### ISSUE THREAD

**Issue by GuglielmoFelici** [ubports/ubuntu-touch#1414]
- Device: Nexus 5 (hammerhead)
- Channel: all
- Build: 2020-04-06/2

I just got a Nexus 5 from ebay. After a fresh install using UBports Installer 0.4.18, there is no WiFi switch, no WiFi connections are found/listed in _Settings > Wifi_ .
The WiFi switch in _Settings > Battery_ is ON.
I have no SIM.
I tried to reinstall wiping all data and using each channel. Tried rebooting, toggling airplane mode on and off and restoring the phone.
I read a lot of forum posts and bug reports about similar issues on N5 and other phones, but didn't manage to find a solution.
This is the output from some commands i run:

`nmcli g`
output:
`STATE         CONNECTIVITY  WIFI-HW  WIFI     WWAN-HW  WWAN    
disconnected  none          enabled  enabled  enabled  enabled 
`

`ifconfig wlan0`
Output:
`wlan0: error fetching interface information: Device not found
`

`nmcli dev wifi con <my ssid> password <mypassword> name <myname>`
Output:
`Error: No Wi-Fi device found.
`

`nmli network`
Output:
`enabled`

`nmli network connectivity`
Output:
`none`

`systemctl restart netmgrd`
Output:
`Failed to restart netmgrd.service: No such method 'RestartUnit'
See system logs and 'systemctl status netmgrd.service' for details.
`
![WhatsApp Image 2020-04-06 at 15 43 18](https://user-images.githubusercontent.com/26324703/78565052-a3759c00-781d-11ea-82d3-c9b72b72a92b.jpeg)
![WhatsApp Image 2020-04-06 at 15 43 50](https://user-images.githubusercontent.com/26324703/78565056-a4a6c900-781d-11ea-91f3-3702384f5526.jpeg)

**Comment by Flohack74** [comment]
Please provide a dmesg log after boot to see if there are kernel driver messages...

**Comment by GuglielmoFelici** [comment]
Thanks for the reply. Here it is
[n5dmesg.txt](https://github.com/ubports/ubuntu-touch/files/4442809/n5dmesg.txt)

**Comment by Flohack74** [comment]
The problem is:
```
[    8.645556] wifi_set_carddetect = 1
[    8.645569] wcf_status: wifi_detect = 1
[   10.645584] failed to power up wifi chip, retry again (4 left) **
```

And thats being repeated 4 times, then the driver gives up. On top of that you got a lot of strange messages about the mmc:
```
 mmc0: SPS BAM reset failed: sps reset_bam=1
[   85.212038] mmc0: got_dataend=0, prog_enable=0, wait_for_auto_prog_done=0, got_auto_prog_done=0, req_tout_ms=0
[   85.212118] mmc0: PM: sdcc_suspended=0, pending_resume=0, sdcc_suspending=0
```

I suspect this is a hardware issue, please install the stock Android ROM from Google and confirm if all the hardware works. Sorry to say, I dont expect this to happen :(

**Comment by GuglielmoFelici** [comment]
That's sad, i'll do the check and report back. Thanks anyway and sorry for wasting your time

**Comment by GuglielmoFelici** [comment]
Can confirm, the WiFi does not work on stock android. The system actually has serious instability issues, like randomly boot-looping. The quick check when i got the phone didn't show this kind of issues tho... could have i fucked up the system in any way using the ubports installer? Btw, thanks very much for the help, if you don't have further advice to spare i'll close the issue, since is not something that affects other devices but mine.

**Comment by rocket2nfinity** [comment]
Do you have any repair skills? Before you write it off as dead, if you have the skills, open it up and look it over. Check for signs of water damage/debris. Check the integrity of the power switch, loose connectors and screws. If there isn't anything obvious, what you're describing sounds like a cold solder joint or component failure. In which case, it's good for parts to repair another. Sorry. 
 
 
  On Wed, Apr 8, 2020 at 9:06 AM, GuglielmoFelici<notifications@github.com> wrote:   


Can confirm, the WiFi does not work on stock android. The system actually has serious instability issues, like randomly boot-looping. The quick check when i got the phone didn't show this kind of issues tho... could have i fucked up the system in any way using the ubports installer? Btw, thanks very much for the help, if you don't have further advice to spare i'll close the issue, since is not something that affects other devices but mine.

**Comment by GuglielmoFelici** [comment]
Sadly i have close to none reparation skills. Thanks anyway for your kind feedback.
Closing.
