### ISSUE TITLE
media-hub track changes result in choppy audio and/or playback control misbehavior

### ISSUE THREAD

**Issue by wdehoog** [ubports/ubuntu-touch#1415]
- Device: opo
- Channel:
- Build: 2020-01-19/2

### Steps to reproduce
add multiple urls to an Audio playlist. start the music and turn the screen off.

### Expected behavior
the media-hub plays and after some time continues with the next song and I listen to it joyfully

### Actual behavior
the media-hub plays but when the next track is started it becomes choppy as xxxxx and I start to cry

### Logfiles and additional information
when media-hub starts the next track it seems to wait for the app to respond to something. but the app is *suspended* so can't. when I wake up the phone the audio becomes normal again.

For music-app it works correct maybe the music-app does respond since it is never suspended (lifecycle-exempt-appids).

In player_implementation.cpp you will see that media-hub releases the lock/wake/state/whatever and only aquires a new one when it receives the Playing state. with my app this Playing state does not arrive only after I wake up the phone. With music-app this state arrives immediately.

-edit-

After removing music-app from the lifecycle-exempt-appids it has the same choppy audio after changing to the next track.

**Comment by UniversalSuperBox** [comment]
This is indeed a problem that seems to have carried over from OTA-11 (therefore it is not a regression and should not block OTA-12).

Excellent observation about music-app only experiencing this issue if its lifecycle exemption is set!

**Comment by wdehoog** [comment]
More info. Stuff happens mainly in player_implementation.cpp.

When handling about_to_finish the next uri of the track list is loaded and state goes to 'ready'. It must go to 'playing' again to acquire a new lock. It looks like an mpris 'play' event is expected that will trigger that. (when the app becomes active again this event is triggered).

I think the player should not go to 'ready' but remain playing by calling d->engine->play() (or play(true), no idea) after open_resource_for_uri(). The app is suspended but the user probably wants to listen to all the tracks.

Now the problem is the mpris event that will arrive  when the app becomes active again.
(see handle_play in player_skeleton.cpp). We could check for already 'playing' but what if playing has stopped? 

Why does the app send this mpris play event? Does the client part of the media-hub do that? 

Is there any documentation on the idea, design or the architecture of this media-hub?

**Comment by wdehoog** [comment]
Even more info. The client side that makes the app send a 'play' command is related to qtubuntu-media.  This package contains code to detach en reattach from media-hub (-events?) when the app is inactivated/activated. This code has been disabled long time ago.  I think this code can be enabled again (but act on 'suspended' not 'inactive') in order to prevent it handling old events.

Probably this also only needs to be done if media-hub is playing tracks from a playlist.

**Comment by UniversalSuperBox** [comment]
It's worth noting that this issue has a visual component as well: the media control in the sound indicator says "Media Player" instead of the current track name, but the media controls are still active and in the wrong state.

Additionally, the following content is logged from media-hub: https://gist.github.com/UniversalSuperBox/f18279888adf27b04fa69d32c6e74e25. At this point, the requesting application is suspended and logs nothing.

![Cropped screenshot of sound-indicator displaying "Media Player" instead of the actual playing media](https://user-images.githubusercontent.com/21966173/114073386-d73c3500-9868-11eb-823b-eddf8ce5afde.png)

When this screenshot was taken, Podbird was playing a podcast. Note that the media control displays the "Play" button instead of the "Pause" button, though.

If the user opens the requesting app, the sound-indicator displays the correct information (the track title and the Pause button). The app and media-hub log the following: https://gist.github.com/UniversalSuperBox/48286c02413a28f06c0d39007b610959

If, instead, the user taps the "Play" button without resuming the requesting app, the sound indicator still picks up the correct information. It seems like all is good. The following is logged by media-hub: https://gist.github.com/UniversalSuperBox/bc1e2fc6451e0d5f4e925e551ef2ae2d. The app is still suspended and is silent.

Later, the user might pause playback from the sound-indicator and put their phone to sleep. This should be fine, but there's one big gotcha: As soon as the requesting application resumes, it starts playing audio again! The app's log in this case follows: https://gist.github.com/UniversalSuperBox/800a13e9d0ddfda953798a0ec042ada2

**Comment by mardy** [comment]
I believe this is now fixed, please reopen if that's not the case.
