### ISSUE TITLE
NEXUS 5X please add support for this platform

### ISSUE THREAD

**Issue by cederom** [ubports/ubuntu-touch#1421]
### Description of the feature
Please add support for LGE Nexus 5X :-)

**Comment by UniversalSuperBox** [comment]
Hi @cederom,

Your device does not appear to be supported. Devices which are not supported can have a Halium port created for them. For Android 5.1 or 7.1 devices this is quite a lot of work and best for people who have ported Android before. For Android 9 devices, you can join the community working hard on bringing Ubuntu Touch to them.

Please see the following resources to get started: https://forums.ubports.com/topic/2068/halium-first-steps

I will be closing this issue, because if we had an issue for every device that someone wanted Ubuntu Touch on, we'd more than double our issue volume.

**Comment by cederom** [comment]
Thank you for the hints @UniversalSuperBox :-)
