### ISSUE TITLE
Device crashes and reboots when adding accounts

### ISSUE THREAD

**Issue by mr-growl** [ubports/ubuntu-touch#1434]
- Device: Nexus 7 2013 wifi 16GB (flo)
- Channel: RC
- Build: 2020-W17

### Steps to reproduce

1. Open "System Settings"
2. click "Accounts"
3. click "Nextcloud"

### Expected behavior
A dialog appears allowing me to enter account information

### Actual behavior
A progress indicator appears, then freezes, then the device reboots

Same thing happens when adding a google account.

**Comment by UniversalSuperBox** [comment]
I can confirm this on the Nexus 7 2013 WiFi (flo). However, it does not occur on any other device in my testing.

**Comment by duckunix** [comment]
I am on OTA-12, UBports Image part 20200507-10245, Device Image Part 20181229-30682, and I am seeing slightly different issues.  I can add a NextCloud account no issues, but the device locks hard when I try to add a Google account first.

However, if I add a NextCloud account, I can then add a Google account.

**Comment by UniversalSuperBox** [comment]
I have been able to mostly resolve this issue with the fix for https://github.com/ubports/ubuntu-touch/issues/1719. However, there are still occasionally problems with the online account overlay popping up as a corrupted rectangle. This is filed as https://github.com/ubports/ubuntu-touch/issues/1723.
