### ISSUE TITLE
Implement gestures when screens off

### ISSUE THREAD

**Issue by PhoenixLandPirate** [ubports/ubuntu-touch#144]
When the phone screen is off you should be able to use gestures to do certain things.

swipe down with two fingers - Pause/start Music
> - skip to the next song
< - Go back to the last song
O - activates the camera
V - Activates the torch

The one that is most used
Double tap to wake.

**Comment by Flohack74** [comment]
Erm? Is this on Android? =)

**Comment by ChloeWolfieGirl** [comment]
@Flohack74 Depends which android device you get, many have the double tap to wake at least.

**Comment by Fuseteam** [comment]
the music and torch gestures seem usefull to me =) as long it doesn't start playing music in me pocket haha the double tap to wake seems to be the same as #472

**Comment by Flohack74** [comment]
So one big update here: Gestures when screen is off are not supported by all hardware. What a surprise :D ! Since the panel must stay powered. This also creates a tiny bit of increased power consumption.
Also the gestures are not unified between vendors that much, but: We will however try now to enable double-tap to wake for the phones that support it.
Also there will be a system-settings setting to enable or disable this. Please follow #472 for details... I will close here for the mentioned reasons.
