### ISSUE TITLE
Launcher missing ( happens randomly )

### ISSUE THREAD

**Issue by lduboeuf** [ubports/ubuntu-touch#1441]
### Illustrations

- Device: N5
- Channel:devel
- Build:2020/05/07

### Steps to reproduce

It happens randomly, but launcher is not displayed ( placeholder still there )
Note that my system may be broken due to some custom tests ( installed debs from PRs i don't remember of )
Launcher is recovered after screen is off and on )
### Expected behavior

Launcher always available and displayed when needed

### Actual behavior

Launcher not displayed
![screenshot20200508_194939447](https://user-images.githubusercontent.com/11663835/81453823-e1ead780-918a-11ea-9bd8-d3e1ccfc544d.png)

### Logfiles and additional information

https://paste.ubuntu.com/p/fTbtT4hDx3/

**Comment by zubozrout** [comment]
I can confirm the same behaviour on Meizu MX4. But as noted on Telegram by some this is not a new issue. It is quite a while since I've experienced that first, very probably even more than 2 months ago.

**Comment by mauricioduarte01** [comment]
I've experienced this as well 3-4 weeks ago. It's not something that happens often tbh. Just happened twice for me.

**Comment by UniversalSuperBox** [comment]
This is likely related to https://github.com/ubports/ubuntu-touch/issues/1326

**Comment by Danfro** [comment]
I had this issue once a day ago on my Xperia. It did happen exactly when I was opening TELEports with an incoming Telegram notification at the same time.

It does sound similar to what is described in #1326 . 

But the launcher did not hide for a brief moment, but stayed invisible until I pulled down the "new message" indicator. So there seems to be a notification relation.

**Comment by carrabelloy** [comment]
Hello unfortunately nothing seems to be happening anymore with the oneplus 3T. That my camera still doesn't work or with some apps. It would be nice if something happened here, since I am a oneplusone & oneplus3T, but the camera on my oneplus3T is still not running. Some apps also do not work. It would be nice if something would happen here. But otherwise thanks for a new alternative for my cell phone

**Comment by Danfro** [comment]
@carrabelloy please stop spamming random issues with your OP3/OP3t questions. Your questions are 0% related to this issue. As I already said in Telegram group, please check the forum and contact the porter for questions.

On Thu, 25 Jun 2020 23:21:08 -0700, Andreas Plassmann wrote:
> Hello unfortunately nothing seems to be happening anymore with 
> the oneplus 3T. That my camera still doesn't work or with some 
> apps. It would be nice if something happened here, since I am a 
> oneplusone & oneplus3T, but the camera on my oneplus3T is still 
> not running. Some apps also do not work. It would be nice if 
> something would happen here. But otherwise thanks for a new 
> alternative for my cell phone
>

--

**Comment by lduboeuf** [comment]
happened today again, yesterday also ( devel ). The action i've made just before was opening Teleport, then it crashed and then the launcher disappeared

**Comment by GI9VANNI** [comment]
> happened today again, yesterday also ( devel ). The action i've made just before was opening Teleport, then it crashed and then the launcher disappeared

Same for me on Nexus 5 OTA-13 stable.

**Comment by UniversalSuperBox** [comment]
I've found how to reproduce this.

https://user-images.githubusercontent.com/21966173/104675959-1add3380-56ac-11eb-8af0-f7678e635e31.mp4

The problem occurs when the Launcher is pulled out while the "peek" animation is running. This animation runs when an app's badge count changes... that's why people would see this most often with Teleports.
