### ISSUE TITLE
incomming and outgoing calls not possible

### ISSUE THREAD

**Issue by ancaf33** [ubports/ubuntu-touch#1468]
Issue: I can't receive or make a call. When someone calls me it is busy for them while I receive a text that I missed a call. When I try to call it tries for a while then says call failed. 

What I expected to happen: To be able to make and receive calls.

Steps to reproduce: Make a call or receive a call with the Swedish carrier tele2/comviq. 

Software Version: 20200608

-------------------------------------------------------

**Comment by Flohack74** [comment]
Hmm you need to specify which device you are talking about.

**Comment by ancaf33** [comment]
Yes I realised that I forgother that. The device is the pinephone community edition.

**Comment by UniversalSuperBox** [comment]
Hi @ancaf33, thanks for your report!

I'm happy to hear that your device is now working again.

We are currently tracking PinePhone issues at https://gitlab.com/ubports/community-ports/pinephone/-/issues, since it is so much different from our other devices. Please file any new issues there in the future.

Thanks again!
