### ISSUE TITLE
Infinite loading when adding online accounts

### ISSUE THREAD

**Issue by jwillikers** [ubports/ubuntu-touch#1472]
- Device: PinePhone
- Channel: Stable
- Build: 2020-06-08

### Steps to reproduce

1. Go to Accounts in Settings.
2. Click Google under add account.

### Expected behavior

I expected some page to pop-up for me to log in to my Google account.

### Actual behavior

A loading circle spins endlessly.

### Logfiles and additional information

I can attach logs later if needed.

This issue also appears to effect @knipp30, as reported in issue #1456.

**Comment by Bugsbane** [comment]
I also have this issue, brand new Pinephone UBports CE edition, no apps added, updated to update 3 stable. I would add that it's not just Google accounts, though. The same thing happens when trying to add any online account (Evernote, Nextcloud, Caldav, ownCloud or Google).

@jwillikers Please update the topic title to reflect that this affects all online accounts, not just Google.

**Comment by jwillikers** [comment]
@Bugsbane, done.

**Comment by Bugsbane** [comment]
I just realized that the issue template here on GitHub asks for any Pinephone related issues to he reported at Gitlab instead. There's already a duplicate issue [here](https://gitlab.com/ubports/community-ports/pinephone/-/issues/42) so I'd suggest going over and adding a thumbsup to that @jwillikers.

**Comment by jwillikers** [comment]
@Bugsbane You are totally right! I'm following the issue there now, thanks.
