### ISSUE TITLE
Brightness flickers in About in System Settings

### ISSUE THREAD

**Issue by jwillikers** [ubports/ubuntu-touch#1473]
- Device: PinePhone
- Channel: Stable
- Build: 2020-06-08

### Steps to reproduce

1. Go to System Settings.
2. Go to About.
3. Wait about 10-15 seconds and the screen's brightness will start to flicker.

### Expected behavior

The screen's brightness should not flicker but stay constant.

### Actual behavior

The screen gets brighter and less bright, alternating back and forth until the About page is left.

### Logfiles and additional information

I can attach logs if necessary.

This occurs whether the adaptive brightness setting is enabled or disabled.

**Comment by Charckle** [comment]
Same issue.

PinePhone, OS build 2020-06-08

**Comment by UniversalSuperBox** [comment]
Hi @jwillikers, thanks for your report!

We are currently tracking PinePhone-specific issues at https://gitlab.com/ubports/community-ports/pinephone/-/issues since it is so different than other devices.

I have re-filed your report there as https://gitlab.com/ubports/community-ports/pinephone/-/issues/142. I'll close this report to keep our issue trackers clear.

**Comment by jwillikers** [comment]
Thanks @UniversalSuperBox. I appreciate you creating the issue for me there. I'll make sure to submit PinePhone specific bugs there in the future.
