### ISSUE TITLE
[enhancement] - App launch automatically

### ISSUE THREAD

**Issue by Gabriele69** [ubports/ubuntu-touch#148]
Hello,
I think it might be useful if we could select apps with automatic startup.
I think, for example, Dekko, Telegram, or some other app we use frequently.

GM

**Comment by dobey** [comment]
This doesn't make much sense, because unless you're actively using the app with it at the top of the stack, then the app is not actually running anyway. You're just wasting RAM by having it open and not using it. And in a complete and functional Unity 8 system, there would be no need to do this, even on a PC, since you would ideally get push notifications and such.

**Comment by NeoTheThird** [comment]
I agree with @dobey on this one. It does not seem like a feature that would be useful for many people, and if someone wants it, it could still be done by using upstart. But for most use-cases, this would be just bad practice.
