### ISSUE TITLE
Phone "Add an online account" greyed out, no sim. No other options for Contacts sync

### ISSUE THREAD

**Issue by ubuntu-touch-testing** [ubports/ubuntu-touch#1485]
Phone and Contacts "Add an online account" greyed out (Phone --> Settings --> "Add an online account")

Contacts --> Settings --> "Add Google account" is the only option available.  

Thus there it is not possible to sync online contacts from other sources than Google.  I should have all the same options as presented in "Accounts"

For my tests, I have a Nextcloud Account configure (System Settings --> Accounts) and working, the Calendar and UBSync are working correctly in both directions.  I expect to be able to sync Contacts even if I do not have a sim card in the phone.

Also, creating contact manually works without a sim, so syncing them should be an option without a sim.

Ubuntu Touch Info:
Phone: Nexus 5
Channel: Development
OS Build Number: 2020-06-19/2

**Comment by UniversalSuperBox** [comment]
Hi @ubuntu-touch-testing,

Indeed, the "Add an online account" option in the dialer is grayed out, but that's because it has no use. I've filed that issue here: https://github.com/ubports/dialer-app/issues/125

It is currently not possible to sync contacts from any other platform, such as Nextcloud, using the Ubuntu Touch interface. There are many different tickets requesting support or planning for support of this, such as https://github.com/ubports/ubuntu-touch/issues/997, https://github.com/ubports/address-book-app/issues/3, and https://github.com/ubports/sync-monitor/issues/9. To help keep the issue tracker clean. I'll close this request.

Thank you for letting us know!
