### ISSUE TITLE
Pinephone: DTMF tones aren't sent during call

### ISSUE THREAD

**Issue by faissaloo** [ubports/ubuntu-touch#1492]
- Device: Pinephone
- Channel: Idk
- Build: 2020-06-18

### Steps to reproduce
 1. Create a Google Hangouts call on a computer
 2. Dial the Google Hangouts number on the Pinephone
 3. Open the dial pad and enter the meeting code 

### Expected behavior

My meeting code should be received by Google Hangouts and I should be able to enter the call (as on other phones I've tested this on)

### Actual behavior

I am continually prompted for my meeting code

**Comment by UniversalSuperBox** [comment]
Hi @faissaloo, thanks for your report!

I've noticed that your issue was not filed on the PinePhone tracker, so I have filed it for you. https://gitlab.com/ubports/community-ports/pinephone/-/issues/162

When reporting bugs that only affect the PinePhone, please use the PinePhone issue tracker in the future.

Thanks again!
