### ISSUE TITLE
unable to install packages in a container

### ISSUE THREAD

**Issue by donno2048** [ubports/ubuntu-touch#1526]
I'm using Nexus 5 with Ubuntu touch and I'm using a libertine container.

When trying to install package like so:
```
libertine-launch -i xenial sudo apt-get install <package>
```
I get:
```
E: You don't have enough space in /var/cache/apt/archives/.
```
and nothing would fix it, I tried `sudo apt-get autoclean` and `sudo apt-get clean` both on the system and on the container.

When I try:
```
libertine-container-manager install-package -p <package>
```
I get:
```
/usr/sbin/chroot: failed to run command '/usr/bin/apt-get': no such file or directory
```
When I tried to install directly from libertine using the '+' button the package was in the 'installing' status but when finished nothing happen and the 'No packages are installed' message appeared...

**Comment by donno2048** [comment]
Looks like I'm not the only one with this problem, apparently someone already uploaded an example to YouTube(https://www.youtube.com/watch?v=zdVuiftJGLc)

**Comment by UniversalSuperBox** [comment]
I believe this issue has been fixed since it was filed. I am able to install packages using the Libertine UI on my Nexus 5 running Ubuntu Touch OTA-16.

Please don't use `sudo` in a Libertine container. It can cause problems leading to a broken container. A broken container will need to be deleted and re-added. Instead, only install packages using the Libertine UI in system-settings or `libertine-container-manager` on the command line.

**Comment by hilga007** [comment]
> I'm using Nexus 5 with Ubuntu touch and I'm using a libertine container.
> 
> When trying to install package like so:
> 
> ```
> libertine-launch -i xenial sudo apt-get install <package>
> ```
> 
> I get:
> 
> ```
> E: You don't have enough space in /var/cache/apt/archives/.
> ```
> 
> and nothing would fix it, I tried `sudo apt-get autoclean` and `sudo apt-get clean` both on the system and on the container.
> 
> When I try:
> 
> ```
> libertine-container-manager install-package -p <package>
> ```
> 
> I get:
> 
> ```
> /usr/sbin/chroot: failed to run command '/usr/bin/apt-get': no such file or directory
> ```
> 
> When I tried to install directly from libertine using the '+' button the package was in the 'installing' status but when finished nothing happen and the 'No packages are installed' message appeared...

This is the closest I have come when googling to an answer: I am using the command prompt as well. Receiving this exact same issue with apt-get not being found. The only "solution" is at the bottom of this post (which isn't a solution -- it is saying do not use sudo -- which we are not -- and it is saying they are not having issues in the GUI -- which is great but irrelevant as this issue is CLI) 

Were you ever able to find a helpful resolution other than the dismissive "I don't care because it is not happening for me" response below?

**Comment by donno2048** [comment]
> Were you ever able to find a helpful resolution other than the dismissive "I don't care because it is not happening for me" response below?

Not that I can recall... This issue is from a year and a half ago...

**Comment by UniversalSuperBox** [comment]
If I say "I believe the issue has been fixed" and no one says otherwise for eight months, I've spent eight months thinking that the issue is fixed. I'm not dismissing your issue, just doing the tests that I can. Please don't assume the worst from maintainers, we've got a lot to keep track of. :)

I would greatly appreciate someone doing more investigation into why this issue occurs (how is apt-get gone!?), at least knowing what causes the container to become broken could help us fix it. If you're still having the issue, then obviously it's still valid and should be open.

**Comment by UniversalSuperBox** [comment]
Did either of you have this issue before trying to run `libertine-launch -i xenial sudo apt-get install ...`?

**Comment by donno2048** [comment]
I updated my ubuntu touch version, recreated the libertine container, and installed ubuntutoolkit. Then everything seemed to work perfectly, but when my device turned off the container was deleted by the time I turned it back on... What???

**Comment by donno2048** [comment]
When I recreated the container and tried to install packages it didn't work and when I did it in the terminal using `libertine-container-manager install-package -p *****` I got this error:
```sh
/usr/sbin/chroot: failed to run command ‘/usr/bin/apt-get’: No such file or directory
/usr/sbin/chroot: failed to run command ‘bash’: No such file or directory
/usr/sbin/chroot: failed to run command ‘/usr/bin/apt-get’: No such file or directory
/usr/sbin/chroot: failed to run command ‘bash’: No such file or directory
/usr/sbin/chroot: failed to run command ‘/usr/bin/apt-get’: No such file or directory
/usr/sbin/chroot: failed to run command ‘bash’: No such file or directory
...
/usr/sbin/chroot: failed to run command ‘/usr/bin/apt-get’: No such file or directory
/usr/sbin/chroot: failed to run command ‘bash’: No such file or directory
Libertine.py:45: ERROR: handle_runtime_error(): maximum recursion depth exceeded libertine-container-manager:184: ERROR: install_package(): Package '******' failed to install in container 'xenial'
```
(related: ubports/libertine#47)

**Comment by donno2048** [comment]
When I try `libertine-launch -i xenial sudo apt-get install ****` directly I get:
```sh
: DISPLAY environment variable not set!
proot error: 'sudo' not found (root = *******)
fatal error: see `proot --help`.
```

**Comment by donno2048** [comment]
@UniversalSuperBox

**Comment by donno2048** [comment]
Stale... Again :cry:
