### ISSUE TITLE
Feature Request - Pine Phone

### ISSUE THREAD

**Issue by JColemanAU** [ubports/ubuntu-touch#1533]
### Description of the feature
Desktop Icons / Add Remove Topbar Icons / Touch Screen Double Tap / Lock Screen
(PinePhone Related)

1. I would like Ubuntu-Touch to have the option of having Applications on the desktop.
  Could the Icons be Animated to resemble Widgets such as Weather / Time
2. Topbar Icons for WiFi / Messing etc get crowed can there be a option to turn them off
3. Double Tap the front screen to wake the device
4. Lock Screen Options Ie Different background / Weather

Ubuntu-Touch is great to use and continue the great Development 

### Illustrations

- Device:
- Channel:
- Build:

**Comment by UniversalSuperBox** [comment]
Hi @JColemanAU, thanks for your report!

I'm happy that you've added your own to the list! However, we're never short on ideas around here and we prefer issue posts are actionable. As it is, an issue post with four requests is very difficult to act on or close.

Additionally, I must warn you that suggestions are usually not going to be acted upon. While we do maintain the [enhancement label](https://github.com/ubports/ubuntu-touch/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) for singular, actionable feature requests, you may notice that the "closed" list is smaller than the "open" list, and the rate of closure is very low. These tickets are generally closed by becoming out-of-date, not by being implemented.

We run a volunteer-driven community, so it is more likely that your requests will be implemented if you help us implement them. For more information on how to make suggestions that work, check out [this answer on AskUbuntu for "where do I place a suggestion?"](https://askubuntu.com/questions/979759/where-to-place-a-suggestion-for-ubuntu/979810#979810) The only change is to replace community.ubuntu.com with forums.ubports.com for the forum.

If you have any questions about any of this, please let me know and I'll try my best to answer them. But due to this post containing more than one request, I will close it as I believe it is not actionable.

Thank you again!
