### ISSUE TITLE
Text messages do not wake the phone

### ISSUE THREAD

**Issue by farkasdvd** [ubports/ubuntu-touch#1556]
- Device: bq e5
- Channel: RC
- Build: 2020-W36

### Steps to reproduce
Lock your phone. Send a text message (SMS) to your phone. The notification about the new text message does not appear while the phone is locked. After unlocking the phone the notification appears instantly.

### Expected behavior
The new text message wakes the phone on its own.

### Actual behavior
The new text message does not wake the phone.

### Logfiles and additional information
Let me know which logfile contains useful information.

**Comment by UniversalSuperBox** [comment]
I've reproduced this issue on the Sony Xperia X by:

1. Turning off Wi-Fi
1. Putting the phone to sleep
1. Waiting 20 minutes
1. Sending a text message from my OnePlus One to the Xperia X.

The message was not received on my Xperia X. After I:

1. Pressed the power button

The device woke up and the message arrived with a vibration.

**Comment by UniversalSuperBox** [comment]
This issue will only occur when Wi-Fi is turned off and the device is not plugged in to charge. Makes debugging a bit more difficult, that.

**Comment by UniversalSuperBox** [comment]
I've just confirmed the above message is also true on the OnePlus One. This is not a case of the device failing to wake up to receive messages, though, because:

* The time of SMS receipt is correct in the indicator. This means that telephony-service is receiving the message and storing it correctly.
* Another push notification arriving wakes the device, shows the target push notification, then quickly shows the SMS notification.

**Comment by gbdomubpkm** [comment]
Is the bug supposed also to occur on the dev channel? My BQ E5 HD is in dev 581 (this day) and I receive sms notifications without any problem when the phone is locked (sleeping black screen): the screen turns on and sound envelope led notification.

**Comment by UniversalSuperBox** [comment]
It appears that repowerd is failing to keep the device out of suspend after telephony-service requests it at https://github.com/ubports/telephony-service/blob/f80374d6c5779f3f7531d2cd6a94b559cda8890f/indicator/textchannelobserver.cpp#L749.

See debugging prints and their output in https://paste.ubuntu.com/p/SDn4V86ktC/

See repowerd output during this operation at https://paste.ubuntu.com/p/2gyVdydgwz/

Time to leave this one for the night.

**Comment by farkasdvd** [comment]
Device: bq e5
Build: 2020-W37

Works great!

**Comment by c4pp4** [comment]
Device: Xperia X
Channel: RC
Build: 2020-W37

I think it's not fixed. Sometimes message notification is delayed and moreover sometimes there is no sound of incoming call, only missed call LED indicator after that.

**Comment by jezek** [comment]
Device: FP2
Image: 2020-W37

Seems to work.

I turned the wifi off, sent SMS to myself and locked screen (power off button) quickly.
After a short while, display was turned on, sound for receiving SMS was played and notification with incoming SMS was shown. After some time display turned off ang green notification LED stated to blink.

**Comment by UniversalSuperBox** [comment]
@c4pp4, I believe your trouble with only the missed call notification showing up may be related to https://github.com/ubports/ubuntu-touch/issues/1561. I will continue to monitor the situation on my Xperia.

**Comment by c4pp4** [comment]
@UniversalSuperBox 

I've reinstalled the device to exclude everything non standard:
Device: Xperia X (F5122)
Channel: ARM64/RC
Build: 2020-W37
Wipe userdata - checked
Bootstrap - checked

The state when tested:
4-digit passcode, Battery: 49%, Location - On, Bluetooth - Off, Cellular data - On (SIM1 Phone, SIM2 Data), Wi-Fi - Off

### Actual behavior
Reboot the device, don't lock/unlock it, just let it sleep via Lock when idle after 1 minute.
After the screen turns off, send a message to the device.
No notification shows up, you have to turn display on or send another message and the notification appears.
The same behavior as you mentioned here: https://github.com/ubports/ubuntu-touch/issues/1556#issuecomment-688480377

You can make a call instead of sending a message and the result is similar. Sometimes no notification shows up, only missed call LED is blinking after that, sometimes notification shows up but there are only vibrations without sound or sometimes it correctly shows up notification with vibrations and sound.

Issue #1561 happens in any state (regardless of notification shows up correctly or not).

I can send any logs you want.

**Comment by UniversalSuperBox** [comment]
Hi @c4pp4, I've filed this as a new issue at https://github.com/ubports/ubuntu-touch/issues/1562

**Comment by c4pp4** [comment]
@UniversalSuperBox OK thank you!
