### ISSUE TITLE
Pine Tab touch pad and mouse limited mobility

### ISSUE THREAD

**Issue by qastokes** [ubports/ubuntu-touch#1581]
### Illustrations

- Device: pinetab
- Channel:???
- Build:20200918

### Steps to reproduce

either the original keyboard track pad or my usb mouse will freeze in movement. I don't know how for this to not happen.

### Expected behavior

the cursor will be trapped by a rectangle that does change in shape. not sure what is the isssue, but graphics or driver id assume. forced to use touch screen for input.

### Logfiles and additional information

appologies for the mess that this is. No idea what i am doing, but this is wildly annoying. glad to answer questions.

thanks

**Comment by UniversalSuperBox** [comment]
Hi @qastokes, thanks for your report!

We're currently tracking issues which only affect the PinePhone and PineTab at https://gitlab.com/ubports/community-ports/pinephone/-/issues. There are several issues relating to call audio and calls failing to be sent or received.

Please file any new issues that only affect the PinePhone and PineTab there in the future.

Luckily, this issue is already filed over there: https://gitlab.com/ubports/community-ports/pinephone/-/issues/118
