### ISSUE TITLE
Sound and Wi-Fi issue Nexus 6P

### ISSUE THREAD

**Issue by Rob3rtLangdon** [ubports/ubuntu-touch#1596]
**FEATURE-REQUEST**
Kindly add predictable text feature. It is a ease of access feature but greatly reduce typing time and spelling mistakes.

### Description of the Bug

1. No ringtone sound for incoming calls.
2. Wi-Fi get disconnected if the device is no used for long time. And have to restart Wi-Fi to connect again.
### Illustrations

- Device: Nexus 6P
- Channel: Stable
- Build: 2020-10-08

### Steps to reproduce

1. Set volume to full for ringtone. Make a call to your device.
2. Lock your screen and keep it unused for 8-10 hours. Then unlock your phone. If Wi-Fi doesn't connect automatically, you've successfully reproduced the bug.

### Expected behavior

1. Should be able to hear sound when the device is ringing while not in mute or vibration only mode.
2. Either the Wi-Fi should not get disconnected or at least reconnect automatically after unlocking.

### Actual behavior

1. Ringing with no sound but only with vibration at incoming calls.
2. Wi-Fi is disconnected and stays that way until you restart the adapter.

### Logfiles and additional information

N/A

**Comment by Flohack74** [comment]
I am aware of the WiFi issue, but the ringtone should work. Maybe you are bitten by https://github.com/ubports/ubuntu-touch/issues/1594 ? That should be fixed soonish.

**Comment by Fuseteam** [comment]
1 feature request and 2 bug reports in one issue........nice :eyes: 
the text prediction feature is a more general issue fwiw see issue #1030 and #1038 appearently

**Comment by UniversalSuperBox** [comment]
Hello @Rob3rtLangdon,

In the future, please split your reports so there is only one issue or feature request per report. This helps us manage the reports and schedule their completion.

I believe the problem with ringtones on incoming calls was resolved. It was tracked as https://github.com/ubports/ubuntu-touch/issues/1594

Ubuntu Touch has predictive text, but it is currently not available in the browser or in any browser-based webapps. This issue is tracked as https://github.com/ubports/morph-browser/issues/406

WiFi reconnecting on suspend is the only remaining issue, then. I've re-filed this for you, please continue any further discussion at  https://github.com/ubports/ubuntu-touch/issues/1604

Thank you for your reports! Since everything in this report has been moved or tracked elsewhere, I will close this one now.
