### ISSUE TITLE
After Rebooting or Shutdown, the bluetooth sustained soft blocked. And WIFI hot-plug, windowed mode also didn't restore its pervious state.

### ISSUE THREAD

**Issue by idtwar** [ubports/ubuntu-touch#1601]
### Description of the feature

After shutdown or rebooting UT, the last state of rfkill's configuration didn't save its blocked or unblocked state.
Also, WIFI hot-plug, Windowed mode (desktop mode via UT tweaks tool) didn't restore its previous state. 

### Illustrations

- Device: dora (Xperia X peformance)
- Channel: community dev (aarch64)
- Build: aosp_f8131-userdebug 7.1.1 NOF27B 174 test-keys

### Steps to reproduce

Shutdown or rebooting event didn't save those states for later booting to restore from it's saved states. 

### Expected behavior

As for soft blocking, urfkill service didn't properly work in UT.
I tried to use sytemctl for enabling the urfkill.service, systemctl couldn't be utilized in UT.
I have no idea about WIFI hot-plug and un-restored windowed.

**Comment by UniversalSuperBox** [comment]
Hello @idtwar, thank you for your report!

In the future, please try to make reports so only one piece of broken functionality (or feature request) is contained in each report. This helps us track what has been broken and schedule fixes.

On the problem with starting `urfkill` with `systemd`, Ubuntu Touch does not use systemd to manage services. Instead, we use `upstart`. You can start `urfkill` with the command `sudo start urfkill` and check its status with `sudo status urfkill`.

With regards to saving and loading the desktop mode switch, I have filed a request for discussion at https://github.com/ubports/unity8/issues/343. I do not think that we should ever make "Desktop Mode" the default on phones, and I don't think any changes there would affect phones. The saved state would be available for tablet users only. So it doesn't affect you, but thank you for starting the discussion.

Ubuntu Touch _should_ save the state of networking cards, however. Since that issue was mixed with your others, I have re-filed it as https://github.com/ubports/ubuntu-touch/issues/1605.

Since this request was multiple requests which have now been filed elsewhere, I will close this one. Could you please check https://github.com/ubports/ubuntu-touch/issues/1605 to make sure I have properly represented the problem?
