### ISSUE TITLE
bug - camera access broken on bacon

### ISSUE THREAD

**Issue by stekalb** [ubports/ubuntu-touch#1631]
- Device: oneplus one (bacon)
- Channel:developer
- Build: 2020-12-18

### Steps to reproduce
 - Update to todays dev-build (2020-12-18)
 - Open Camera app
 - Camera requests for access, but you are not able to grant it
 - open system settings, go to "App Berechtigungen / application rights?" 
 - camera is greyed out

### Expected behavior
- camera access can be granted

### Actual behavior
- camera access can't be granted

### Logfiles and additional information

[bacon_dmesg-20201218.log](https://github.com/ubports/ubuntu-touch/files/5717573/bacon_dmesg-20201218.log)

**Comment by stekalb** [comment]
[syslog_snippet-20201218.log](https://github.com/ubports/ubuntu-touch/files/5717593/syslog_snippet-20201218.log)

**Comment by delijati** [comment]
I got the same error when i was testing the halium-7.1 image. Camera (zoom) is ne of the longest outstanding issues i have with my opo

**Comment by wdehoog** [comment]
Same here with build 2020-12-15. System Settings appear but no idea how to grant permission.

part of unity8.log: https://pastebin.com/7DdV8MTw

**Comment by UniversalSuperBox** [comment]
This is related to our moving of Android compatibility image builds from our Ubuntu 16.04 build server to our Ubuntu 20.04 build server. It appears that something is incompatible or otherwise working incorrectly.

This can be verified by replacing the file at `/var/lib/lxc/android/system.img` on a devel image with one from the latest stable image. The older file from the stable image works correctly, the newer file from the devel image does not.

Further, it is possible to narrow it down to something inside the `/system/lib/`, `/system/bin/`, and `/system/vendor` folders. If all of them are taken from the stable image into the devel image, the camera works correctly.

Four files are missing from /dev/ when the camera is not working:

```
/dev/v4l-subdev16
/dev/v4l-subdev17
/dev/video1
/dev/video2
```

Additionally, it seems like something which initializes the camera subsystem on the Android side isn't working at all. `logcat` is missing all mentions of the OMX video decoder and many audio decoding messages are missing as well.

Working camera logcat: https://paste.ubuntu.com/p/hkFzMz4B2W/
Broken camera logcat: https://paste.ubuntu.com/p/HzcvFKswbT/

Working camera dmesg: https://paste.ubuntu.com/p/qMfzX5dRg3/
Broken camera dmesg: https://paste.ubuntu.com/p/mwxzKPgrHZ/

**Comment by UniversalSuperBox** [comment]
This was fixed by https://github.com/ubports/android/commit/424066e177f069d77e06895220fe24c41940e2ae. Turns out the old build server used a different version of the proprietary blobs than the new build server... Using the same version as the old server on the new server fixed the camera. In devel now.
