### ISSUE TITLE
BUG > 4g(LTE) Fails consistantly > but 3G works fine > 

### ISSUE THREAD

**Issue by alexjoverton** [ubports/ubuntu-touch#1635]
BUG-REPORT 
Device: Xiaomi Redmi Note 7 
Channel: devel
Build: 16.04 27/12/2020 build 020122714
### Steps to reproduce
Wifi on > 4G selected > connects once then fails thereafter 
Downgrade to 3G/2G only > everything works fine > Data is restored 

### Expected behavior
Enable 4G data no loss of comms

### Actual behavior
No cell data while 4G is selected

**Comment by padhitheboss** [comment]
jasmine_sprout(Mi A2) is having the same issue. Any temporary fix till now?

**Comment by alexjoverton** [comment]
For me, I leave it on 3G only and I have data working, but only on 3g speeds, so not a fix but a work around. If I leave it on 4G lte nothing works. Not sure if this helps..

**Comment by shoukolate** [comment]
@padhitheboss Can you elaborate how to produce this issue on jasmine_sprout?

**Comment by padhitheboss** [comment]
@shoukolate steps for producing this issue is exactly the same as lavendar. In my case, I have tested 4G sim on both the slots(SIM1, SIM2), changed APN settings but nothing works. I live in India, so I have tested True 4G Network (Jio 4G, Airtel 4G). 

But something strange happened when I use BSNL 4G SIM data works flawlessly. As per my research, BSNL doesn't have 4G spectrum yet so they are refarming 3G spectrum to 4G spectrum. I am using this for 10 hours without any disconnection. 

I hope this makes sense and might help some developer to find problems with LTE data

**Comment by alexjoverton** [comment]
look like latest OTA has fixed this , great thanks very much, will test then close is all goes well...

**Comment by padhitheboss** [comment]
Channel: devel
OS build number- 2021-01-05/4
Still having the same issue as described above

**Comment by alexjoverton** [comment]
Channel: devel
OS build number- 2021-01-05/4
UBports Image part0210105-25239

Spoke too soon! This mornings update has put it back to as described above on original post. So forced to use 3G network again. Strange as yesterday it was working a treat!
Cheers

**Comment by shoukolate** [comment]
After testing on Mi A2, I found out that this issue is mostly likely related to any recent changes to ofono since LTE works perfectly fine on Erfan's GSI v10 and we're using same ofono configs in device port.

**Comment by shoukolate** [comment]
The temporary work around is to disable ipv6 using this command `./usr/share/ofono/scripts/set-context-property 0 Protocol ip` as mentioned here https://t.me/ubports_porting/79146

**Comment by padhitheboss** [comment]
Now mobile data is working. And  I got the reason behind the strange behaviour that some operator works fine while some do not. It may not fix problems, everyone, because there is some operator out there who are using ipv6 only, in those cases mobile data won't work because we are disabling ipv6.
Let's wait for ipv6 support for cellular data.

**Comment by alexjoverton** [comment]
command is not working for me : 
Error setting context /ril_1/context1 property Protocol: org.ofono.Error.InvalidFormat: Argument format is not recognized

**Comment by padhitheboss** [comment]
Go to- /usr/share/ofono/scripts/ -
cd /usr/share/ofono/scripts/ 
Then execute the following -
./set-context-property 0 Protocol ip 

I have exactly copied the commands from the shell window. Try this once.

**Comment by alexjoverton** [comment]
Thanks for that, seems to have worked, I did not realise I needed to cd to the directory, I was tried many ways.. nano to edit etc.. Great news at last I can use 4g all the time !! Just need to sort GPS then everything works except video on front facing camera. Thanks for taking the time to share your fix
Cheers
Alex

**Comment by UniversalSuperBox** [comment]
Hi @alexjoverton,

I've filed a new report to consolidate information spread across multiple similar reports for all Android9 devices. This new report is #1657. I'd appreciate if any further conversation happened there, I will close this report now.

Thank you!
