### ISSUE TITLE
volla phone ubports no calls or sms

### ISSUE THREAD

**Issue by duportail** [ubports/ubuntu-touch#1656]
Sometimes no phone calls or sms can be recieved. Only reboot can make the phone operational again. Very fustrating when the phone is used in business.

### Illustrations

- Device:
- Channel:
- Build:

**Comment by UniversalSuperBox** [comment]
Hi @duportail, thanks for your report!

Given the information in this request, I believe this is the same issue as https://github.com/ubports/ubuntu-touch/issues/1656. Sometimes it manifests itself differently (calls simply dropping instead of the phone showing no carrier *and* calls dropping). I will close this request in favor of the linked one to avoid confusion.

Thanks again for your report!
