### ISSUE TITLE
A minimal install and a full install?

### ISSUE THREAD

**Issue by mishamagher** [ubports/ubuntu-touch#1659]
At certain times I feel like the operating system can be bloated with useless animations, while other times I feel like it doesnt have enough customizability.  what if there were 2 install options, one that uses as little.computing power as possible while another is feature full.

**Comment by UniversalSuperBox** [comment]
Hi @mishamagher, thanks for your report.

Unfortunately, I don't think we'll be able to act on your report to create exactly what you say you're looking for. There are a few reasons for this:

* Creating two install options is *a lot* of work. Right now, we have trouble testing all of our devices with a single install options. Needing to duplicate that work for a minimal install would kill us. That doesn't take into account the time spent to create the second install option in the first place.
* If a feature in Ubuntu Touch performs poorly, we don't want to gloss over that by removing it. Instead, we'd rather fix the poorly-performing feature so it performs well. Then, people get the feature *and* the performance.
* The time we spent creating an OS with everything removed is time we could spend making the original OS better in the first place, so we didn't need to remove everything!
* Bloat is a loaded term. It doesn't usually mean anything useful to us, as the developers of the operating system. The default Ubuntu Touch install takes up 5GB of storage or less (most of it is actually Android storage that we can't move) on most Android devices, and it uses less than 700MB of RAM on the Nexus 5 after it's booted. I have a 2017 Android phone that uses 8GB of storage eternally and 1.4GB of RAM after it's booted, when nothing is running. Is that bloat?

By default, Ubuntu Touch should use as little computing power as possible. It should be efficient and fast. If it's not, then there are specific problems that we need to fix. Painting over the problem by removing features from the OS would be counterproductive.

If you're having performance problems with a specific Ubuntu Touch feature or application, we'd love to help. Please file an issue report on the affected component (it helps to follow [our bug reporting document](https://docs.ubports.com/en/latest/contribute/bugreporting.html)). Hopefully then we can improve Ubuntu Touch for everyone, not just for people who are okay with not having all of its features.

You also mention wanting more customization options. These generally follow the same problems... Making something customizable makes it more complex and requires more testing. We're okay with making things customizable, if the system can be tested in its customized states without a lot of work. The customization should also add something functional and useful to the system, making it more accessible for people for example. So go ahead and request these specific options, too... but please try to include good descriptions of what you would like changed, why you would like it changed, and how it will help other people if it is changed. Include mock-ups and screenshots if possible.

All of these things help make Ubuntu Touch better.

Since this report isn't terribly actionable, I will close it now. Again, thank you for your report. I'm looking forward to seeing many more.
