### ISSUE TITLE
No SIM Card detected

### ISSUE THREAD

**Issue by alitrack** [ubports/ubuntu-touch#1664]
I tried ubuntu touch both stable and developer version, just got "No SIM card detected"
no matter China Unicom or China Mobile

**Comment by Flohack74** [comment]
@alitrack Please use the issue template, that suggested to give us more information, most importantly:
- Which device are you using?

**Comment by Vartojas** [comment]
I can verify this problem for s3ve3g. No Sim-Card detected after initial boot. Needs a reboot to find Sim-Card.


    _Device:_ Samsung S3 Neo (s3ve3g)
    _Channel:_ devel
    _Build:_ up to 101 for sure

**Steps to reproduce**

    Insert a SIM card and start phone. It will directly lead to the UT circle.

**Expected behavior**

    Field to type the PIN

**Actual behavior**

   Phone shows instantly UT circle and it shows that no Sim Cards are in the phone (need to insert Sim Card)

**Comment by alitrack** [comment]
> @alitrack Please use the issue template, that suggested to give us more information, most importantly:
> 
> * Which device are you using?

Oneplus One

**Comment by UniversalSuperBox** [comment]
Hi @alitrack,

I've looked up the carrier compatibility of the OnePlus One. It appears that China's telecoms are supported by the international version of the device indeed. Which version of the device do you have?

Otherwise, much of the standard advice applies: please ensure that you are inserting a mini-SIM card (not a micro-SIM); that the SIM card is inserted correctly; and that the SIM card works with Android installed on the device instead of Ubuntu Touch.

**Comment by alitrack** [comment]
bad  news， my OnePlus One become brick now, but I tried other OS, some works, mine is not international version, just China mainland.

**Comment by uamoti** [comment]
Hi,
I'm having the same issue with my OPO.

I've tried different SIM cards from a few carriers and none of them work; all previously working with LineageOS.

**Comment by Flohack74** [comment]
Can it be that those carriers are VoLTE-only? Ubuntu Touch does not support VoLTE atm.

**Comment by Atomos-X** [comment]
> 
need add more parameters to support china telecom.
https://github.com/ubports/ofono/pull/39
