### ISSUE TITLE
Renaming of maliit input context plugin can be dropped

### ISSUE THREAD

**Issue by nicolasfella** [ubports/ubuntu-touch#1708]
https://github.com/ubports/maliit-framework-packaging/blob/xenial/debian/patches/0001-rename_input_context.patch renames the maliit Qt plugin from maliit to maliitphablet to work around a name clash with Qt's own plugin.

However Qt hasn't shipped it's own maliit plugin for years (https://codereview.qt-project.org/c/qt/qtbase/+/63891) so the renaming is no longer needed

**Comment by Fuseteam** [comment]
so the patch can be dropped?

**Comment by Flohack74** [comment]
Whats the state here :)

**Comment by dobey** [comment]
> Whats the state here :)

State is the patch comes from Ubuntu (we are using the package directly from Ubuntu in 20.04 builds currently), and I think having it doesn't harm anything. When we can finally migrate to shared upstream maliit keyboard2, we will need to backport the new framework and keyboard packages from debian anyway, and this (as well as I think the other patches) should no longer be relevant.

I'm closing this, since while the patch may no longer be needed, it seems to not hurt anything, and won't be relevant in the future anyway. I don't think we should be updating it on 16.04 any more before we switch to 20.04, either. If there is indeed something being broken by the patch existing, please report it against https://launchpad.net/ubuntu/+source/maliit-framework for the current development series and Focal, so that the Ubuntu packaging can remove it, and backport that removal to 20.04.

Thanks.
