### ISSUE TITLE
UT won't return coordinates of the device reliably to the uNav app

### ISSUE THREAD

**Issue by codinghedgehog-python** [ubports/ubuntu-touch#1756]
I'm testing uNav on Xperia X (F5121) and Meizu 5 Pro both running Ubuntu Touch.
On Meizu the app sometimes takes couple of minutes before it finds my location and
sometimes it doesn't find it at all (yes GPS is on) .
On Xperia I've tested it today and it didn't find my location even after waiting for 5 minutes.
It should be almost immediate detection.

- Device: Xperia X (F5121) & Meizu 5 Pro
- Channel: stable
- Build:   OTA-17

### Steps to reproduce
Get F5121 or Meizu 5 Pro and test location detection outside of WLAN. Using 3 or 4G.

### Expected behavior
Detection of my location within few seconds.

### Actual behavior
Often it takes about a minute or two for the the app to locate the phone. Some other times it won't find location at all.

### Logfiles and additional information
I contacted uNav's developer. He said it's issue of the OS not returning coordinates of phone back to the app.
https://forums.ubports.com/topic/6294/system-isn-t-returning-coordinates-to-unav-app?_=1624352424539

**Comment by Flohack74** [comment]
Hi,

our GPS is not assisted, means when you turn on an App the GPS is cold-started. If you google a bit around a cold start of a GPS receiver can take from under a minute up to much longer. And thats only in clear visibility of the sky. Indoor it wont work at all. Basically the receiver does have to scan all different frequencies for the current satellites, inquire the so called almanac and then start sorting out which satellites it wants to listen to.
Also satellites being turned off or on maintenance need to be considered.
At the end, the receiver has to lock in on at least 3 satellites, better 4, to give you an initial fix. That takes also considerable amount of time.
With UT everything under 5 minutes is already good. But on some devices it can take longer. It really depends only on the hardware.
We cannot make this any better, excapt at some point when we could use WiFi AP names to assist with the first fix, and this has been planned for a long time now, but currently there are more important items on the roadmap.
I can assure you that the code itself is working, its just a matter of your location, clouds, and the current position of satellites.

**Comment by codinghedgehog-python** [comment]
Hi and thank you for the feedback.
It sounds like UT just gave potential new users another reason for not to switching to UT full-time.
"With UT everything under 5 minutes is already good. But on some devices it can take longer. It really depends only on the hardware."  <-- that's unacceptable for most people.
I do understand that developers need to follow what's on the agenda of the community. The roadmap if you will but
I've noticed that the Notes app is getting updates quite often. I don't know how significant those commits are as I'm not
heavy Notes user but it kinda gets me thinking what's the point of making Notes better if the user can't get the phone tell
where he is at any given time ? What people need more when they're lost ? A fully functional map app that can show them where they are or cutting edge version of Notes ?

Please don't get me wrong. I understand that you, personally, aren't responsible for who works on what. Since this is a community-driven mobile OS. All I'm saying that the donations community is getting from backers could perhaps be used in areas where the real pains are.

I understand that lack of funding may be the real issue here. Since this problem isn't confined to particular app but rather the hardware's ability to connect fast to satellites how can I, as a backer make sure the donations will be used to improve this ?

**Comment by Flohack74** [comment]
First you have ask a few questions:
1. What are the technical facilities to provide a feature?
1. How hard is it to implement (code & test) those facilities?
1. Are there external dependencies, maybe incurring costs?

For the location service in UT I would answer as follows:

1. The location feature of a modern mobile OS like Android is provided by a location backend that combines multiple sources of location providers so be as fast as possible with providing location to the user. The answer times on location request got less and less ofer the last ten years by adding more sources of location: GPS, cell towers, WiFi access point fingerprinting, maybe more. For GPS you need a hardware sensor. For cell towers you need a protocol to extract the cell tower´s coordinates list from the modem and triangulate it. For the WiFi fingerprinting you would take a list of WiFi access points, send it to a cloud service and ger an approximation of your location.
2. Ubuntu Touch has a location backend that can use various plugins, that part is covered. So lets go over the potential plugins for that:
Unfortunately GPS, while being the most precise of the mentioned ones, needs considerable time to obtain a location. 2 solutions here: Leave GPS on all the time, or be patient enough. GPS plugin is fully implemented already, but relies on Android container and cannot talk directly with the GPS chip.
Cell towers: The modem communication to get this information is proprietary and not documented. It also varies from device to device and from chipset to chipset. The effort to implement this is unknown and currently impossible to estimate. Setting up a developer for that will be anything from weeks to months, with unclear outcome and only getting it to work on some devices probably. The testing effort is unknown since also it will vary on country and provider, we cannot make sure it will work for everyone.
WiFi: A cloud service must be used. While implementing that might be not so hard, we need to use a service, means that normally will cost money. We will look at Mozilla´s location service, but we have an upper limit of requests per day, otherwise its commercial use and no longer possible for us. That means users might or might not get an answer from it. We cannot and dont want to use Google for that btw.

Its not about priority. Donation wont help, either. We need hands on deck that dig into tons of code and reverse-engineer the mess from Google and Android. Then finally things could get forward. Lack of location is not because we are not enough people but because **Google does not want anyone else to have that cool feature working smoothly**. period.

**Comment by Flohack74** [comment]
Oh and the 2nd solution: Leave GPS on all the time. No, we dont want to do this: 1. it will kill your battery 2. It would allow potential tracking of your location all the time. Ubuntu Touch is all about privacy, so our users would kill us if we open a potential tracking backdoor by having location on all the time.
Thats the tradeoff: nobody can track your location, but now you need to wait some minutes for a fix. What would be your preference? Maybe we should make a switch (still the battery willd rain quickly...)

**Comment by codinghedgehog-python** [comment]
"Google does not want anyone else to have that cool feature working smoothly. period."  I love your blunt honesty. It makes perfect sense. Why make the code open source if it will only invite competition to the space ? Would you shoot yourself in the foot ?
"Ubuntu Touch is all about privacy, so our users would kill us if we open a potential tracking backdoor by having location on all the time." So true as well. AFAICT Android comes with location toggled on out of the box. Not the case with UT. Having
more privacy-focused device brings pros as well as cons.

It sounds a lot like the issue isn't really in money or where the issue stands on a to-do list but rather finding the group of people (preferably stubborn and determined) who won't mind investing time and energy digging through tons of code for the sake of future of UT. I understand not everyone is up for this.

**Comment by codinghedgehog-python** [comment]
I'm gonna close this now as this doesn't have a real resolution. Solution is finding dedicated group of developers who want to fix this.
