### ISSUE TITLE
Halium: Camera permissions are not enforced

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-touch#1821]
- Device: Any device with Halium >= 7.1
- Channel: All channels
- Build:

### Steps to reproduce
1. Reset a device to factory defaults
2. Open Camera or Tagger or any App requesting camera access

### Expected behavior
- A trust prompt appears and can be accepted / declined

### Actual behavior
- Camera access is given instantly

### Logfiles and additional information
- The category for camera access in system-settings Security section also stays empty.

**Comment by peat-psuwit** [comment]
So, the camera permission thingy is implemented in the Android side with a couples of commits [1][2] (they're from Canonical's phablet_4.2.2 tree). I was going to say that the patch was rather intrusive, but upon looking at the patches, turns out it's not that intrusive. It's pretty much self-contained in a C++ class, and shouldn't be hard to backport. So, I guess we can have this patch for now.

In longer terms though, I think we should plug into Android's PermissionController interface and provide permission that way. The service is stubbed by droidmedia [3], but I think we can implement it if we want.

[1] [0001-Adjust-permissions-of-socket.-Provides-a-connection-.patch.txt](https://github.com/ubports/ubuntu-touch/files/7253336/0001-Adjust-permissions-of-socket.-Provides-a-connection-.patch.txt)
[2] [0002-Fix-bugs-and-add-traces-for-trust-store-support.patch.txt](https://github.com/ubports/ubuntu-touch/files/7253339/0002-Fix-bugs-and-add-traces-for-trust-store-support.patch.txt)
[3] https://github.com/sailfishos/droidmedia/blob/master/services/services_9_0_0.h#L179

----------
Note to self: this is the original bug discussing this.
https://bugs.launchpad.net/ubuntu/+source/qtubuntu-camera/+bug/1230366

**Comment by Flohack74** [comment]
Oh that means we need to patch **every** kernel out there? That can be a huge task. At least we need to get a good recipe for the porters and put it into porting documentation.

**Comment by peat-psuwit** [comment]
Yes (Oh, well). That is, unless we want to get Android out of the container, which is essentially what Mer/SailfishOS does.

Or we find another alternative...

**Comment by fredldotme** [comment]
Thanks for the link to the required kernel change. I've gone ahead and enabled them for the Xperia X (k4.4) and Pixel 3a (k4.9) already:

4.4: https://github.com/fredldotme/device-kernel-loire/commit/7f691378d97f4cf5effd2c3b1f521e918f25df8e
4.9: https://github.com/fredldotme/android_kernel_google_bonito/commit/d2587ce3968c6fdde3cf09d785bb957c4b75572f

Should be easy to cherry-pick or `git am` them as patch files into other device kernels.

**Comment by fredldotme** [comment]
The integration has been merged into Halium 9.0. For Halium 7.1 these PRs are required:

https://github.com/Halium/android_frameworks_av/pull/8
https://github.com/Halium/android_system_core/pull/16

As agreed with other Halium maintainers & consumers it only enables the trust-store codepaths in case the following patch is present in the kernel to keep unpatched devices functional:

https://github.com/fredldotme/device-kernel-loire/commit/b9174d305668a21da1c1efa1ff0cdc961ed1d2db

**Comment by mariogrip** [comment]
Merged

**Comment by c4pp4** [comment]
RC OTA22: 2022-W04 (device: Mi A2 with patched kernel)
Works.
