### ISSUE TITLE
Xiaomi Redmi Note 7 stereo speaker mode does not work

### ISSUE THREAD

**Issue by GermanAizek** [ubports/ubuntu-touch#1824]
Device: Xiaomi Redmi Note 7
Ubuntu Touch: 16.04 dev branch

It was noticed that the left speaker of the phone does not work, the device has two speakers but acts only right.

**Comment by mardy** [comment]
I can confirm this. But this probably needs to be reported here: https://gitlab.com/ubports/community-ports/android9/xiaomi-redmi-note-7/xiaomi-lavender/-/issues

**Comment by Danct12** [comment]
The Redmi Note 7 does not have stereo speakers.

**Comment by Danct12** [comment]
That's simply for looks, the left one is the microphone and the right one is the actual speaker. This is also confirmed by [reviewers}(https://www.gsmarena.com/xiaomi_redmi_note_7_pro-review-1945p2.php) when they got the phone.

**Comment by Flohack74** [comment]
@GermanAizek just because there are holes on bboth sides does not mean there are 2 speakers. Really a lot of phones faked that impression over time, there are in reality very very few models with 2 speakers. I liked the solution of the Nexus 6P where the 2 speakers were on top and bottom using the telephone openings, and if you turned it landscape you had real stereo base since they have quite a distance. Watching movies like this is really an option :)
Sadly device manufacturers think a big screen is everything and forget that percepation of sound is much more important to the human being than perception of light :)
Less screen, better speakers please!
