### ISSUE TITLE
Correct translation for Ubports website

### ISSUE THREAD

**Issue by GermanAizek** [ubports/ubuntu-touch#1993]
@Flohack74, how to access translation of ubports website?
I have already translated many modules and apps, but site has a lock.

**Comment by Flohack74** [comment]
@GermanAizek this is because the site is using Odoo, and it was impossible to get a clean sync between both systems, Weblate and this. We had always a ton of merge conflicts, and idiotic sentences in translation like "<br/><br/><br/>" as it cannot separate text from markup.
Ultimately the UBports website will not be longer translated, its simply technically impossible. Sorry for your efforts.
