### ISSUE TITLE
[Feature Request] 3D Acceleration via Mesa Freedreno for Angler/Huawei Nexus 6P

### ISSUE THREAD

**Issue by hilga007** [ubports/ubuntu-touch#2033]
### Description of the feature
Mesa 3D Acceleration on Nexus 6P is needed. With the latest Mesa freedreno, this seems as if it should be possible on this device

- Device: Nexus 6P (Angler) 
- Channel: dev
- Build: 634

### Expected behavior
3D acceleration using newest drivers is expected. 

### Actual behavior
glxinfo -B shows no displays are connected. Manually installed programs (LibreOffice, Firefox, Chromium) cannot launch thanks to no display being found.

**Comment by Flohack74** [comment]
I have no idea how I can fix this for you - we are using an Android lowlevel container and all rendering is done via that. There is no way I can install an alternative to th vendor´s defaults.

**Comment by dobey** [comment]
You seem to be conflating one issue with some perhaps misguided information you might have found elsewhere. We do not run mainline kernels on Android devices for UT, but run them on top of the Android HAL, which provides the necessary drivers for graphics. Therefore 3d acceleration is already working (otherwise, you wouldn't be able to use UT at all really).

In any case though, `glxinfo` will likely be not useful, as we do not use X11, and the devices use GLES, not GL/GLX.

As for the "display not found" issue for manually installed programs, if you did not install them via libertine, then you are likely doing unsupported things on your device. We do not use X11 as display server, but using Mir as a compositor, which handles mirclient and wayland protocols. Xwayland does not work.

**Comment by hilga007** [comment]
Conflating, no. Confusing; yes.

In my mind I was using a normal Ubuntu install but it is clear now why Canonical abandoned this project in favor of having a desktop-only OS. 

How do I see what is being accelerated? I thought glxinfo also showed OpenGL ES versions and info. That being said - I also don't know what Mir is. 

**Regardless: Godot 3D test is slow on this device and made me believe it was being software-accelerated / was a framebuffer or using the equivalent of llvmpipe. How do I find out the GPU utilization?**

Maybe I should ask these elsewhere but all the "GIVE US FEEDBACK" options so prominently displayed pointed me here. 

> 
> 
> In any case though, `glxinfo` will likely be not useful, as we do not use X11, and the devices use GLES, not GL/GLX.
> 
> 
> 
> As for the "display not found" issue for manually installed programs, if you did not install them via libertine, then you are likely doing unsupported things on your device. We do not use X11 as display server, but using Mir as a compositor, which handles mirclient and wayland protocols. Xwayland does not work.

**Comment by dobey** [comment]
> In my mind I was using a normal Ubuntu install but it is clear now why Canonical abandoned this project in favor of having a desktop-only OS.

Don't be rude and make wild claims regarding things you clearly know nothing about. It will not work out well for you.

> Regardless: Godot 3D test is slow on this device and made me believe it was being software-accelerated / was a framebuffer or using the equivalent of llvmpipe. How do I find out the GPU utilization?

Are you asking about https://open-store.io/app/godot3dtest.pavelprosto being slow on Nexus 6P? It has a link to telegram for the developer to ask them for support, as well as a link to the github repo for that application, right in the store. If you are otherwise running a godot 3d test thing from somewhere else, likely the problem is you are making a lot of wrong assumptions about how the OS you're running on works.

_Ubuntu Touch is not a traditional PC linux distribution, and phones are not traditional PCs.__

Treating your phone like it's a PC, or Ubuntu Touch like it's the same as Ubuntu on your PC, will only give you poor results. Being rude here won't solve your problems.

**Comment by Flohack74** [comment]
More infos about Mir can be found here: https://en.wikipedia.org/wiki/Mir_(software)
