### ISSUE TITLE
 Media player app is not shown on Home scope/screen.

### ISSUE THREAD

**Issue by Stefano0101** [ubports/ubuntu-touch#233]
- Device: Any (turbo)
- Channel: Stable (any)
- Build: Ota-1

## Steps to reproduce

1. ...No Media player app shown on default scope/home screen
2. ...Media player only appears when trying to open a video file in File browser
3. ... The video file can be played from within Gallery app, if is located in Photos, if located in Videos, Downloads, etc, it won't be found.

## Expected behavoir

... Should be permanently on Home scope/screen, when clicked on, it should give an option to navigate to file location, give option to play last played video files...

## Actual behavior

... Media player only visible when the video file is looked up with File manager.

## Logfiles and additional information

...

**Comment by Stefano0101** [comment]
Media player should be a standalone application, just like Music app.

**Comment by sverzegnassi** [comment]
Thank you for taking the time to report the issue.

You properly addressed the main three issues:
- All the videos in 'Pictures', 'Videos' or 'Downloads' folders should be accessible from gallery-app. This seems a specific issue of the application, and it might be worth to forward the report to the application bug tracker.

I suspect the Canonical Design team deliberately designed the app to work as such.
- "give option to play last played video files"
I believe that the "Local Videos" scope has been meant as a sort of promoted UI for this usage.
Since videos are accessible both from gallery-app and scopes, Canonical engineers may have preferred to provide mediaplayer-app as a ghost app. On Android, for instance, the video player is directly provided by the gallery-app.

- "option to navigate to file location"
Usually, mobile OS's don't allow direct access to the file system, but mediate the access to the file location through a database. In the world of sandbox'ed apps, it's very hard to offer a consistent access to the file system, like it currently happens on GNU/Linux distributions.
Third party apps store their data in an isolated location, and system folders are not accessible for security reasons. As Snap and Flatpak packages become more common, I suspect this behavior will spread on desktops too. Providing a file picker for browsing the content of a single folder might lead to a sub-optimal user experience.

For specific needs, File Manager can act as a surrogate of a file picker. Since FM is now installed by default in UBports' system images, we are trying to make it more user friendly and improve our support to this specific use case. 

Further improvements (we are discussing) that might help with your current issues are:
- Allow users to browse gallery-app content by folders, like it happens on Android. This would make easier to find the searched picture/video
- Expose the downloaded documents handler to the applications scope. This feature is currently accessible from webbrowser-app only.

There is a number of possible solutions for serving this use case better. Each of those solutions comes with their trade-offs and their development costs. We might need some time in order to choose the one that fits better with our current infrastructure and our final goal of a convergent OS. Making things more "UNIX-friendly" is surely a value, so we'll try to provide simplifications where possible.

I'm therefore marking the report as "needs confirmation" in order to reflect the fact we need to extensively discuss the UX behavior of our set of core applications. We will keep this report on our radars.

We do recognize that some previous design choice does not completely meet users' requirements, but we also need to enforce consistent behaviors between core apps and other platforms as well.
We still want to allow a seamless migration from other platforms, and ease the learning curve for new users.

Thanks again for reporting this!

**Comment by dobey** [comment]
Media player being a hidden app is by design, fwiw. It does not have any UI for browsing local media or such. It's simply a player interface and that's all.

**Comment by NeoTheThird** [comment]
Yeah, that makes sense. @sverzegnassi, are you OK with closing this? On xenial, the app actually appears in the apps scope at the moment. @mariogrip is that because of a conscious design decision or a bug? Do we want it to show up or not?

**Comment by sverzegnassi** [comment]
@NeoTheThird , a recap of my previous message:

1. mediaplayer-app does not provide a file picker. By the original design, gallery-app is the only app authorized to browse picture/video collections. For me that's a __won't fix__. So yes, we can close this*.

2. If `~/Videos` and `~/Downloads` are not indexed and therefore accessible, it might probably be worth to open another issue. On iOS and Android I can browse downloaded files in gallery-app.

3. The "Downloads" page in `webbrowser-app` might become a separate app and/or have a separate link in the homescreen. That might make easier to find content in the folder.

4. `filemanager-app` might become an alternate interface for browsing public user's content. As such, it'd have to: 1) make a clear distinction between regular and superuser capabilities; 2) make a better use of `url-dispatcher` and `content-hub` to open user's files.

I still believe that Ubuntu Touch fails to communicate its data sharing model, and many apps seem to misbehave. We need to produce documentation on how UT apps are meant to work, in order to find out improper behaviors. 

* However, I'm on 16.04 right now and I see that mediaplayer-app not only is visible in the home screen, but also provides a file picker by leveraging content-hub. We need to find out _when_ and _why_ someone has made this change.

**Comment by Stefano0101** [comment]
This can be closed now as in 16.04 is this fixed.
