### ISSUE TITLE
Sending data over NFC

### ISSUE THREAD

**Issue by PhoenixLandPirate** [ubports/ubuntu-touch#245]
It would be nice to be able to send data like browser pages, youtube videos, contacts, photos, to other devices using NFC.

![photo_2017-09-17_12-32-49](https://user-images.githubusercontent.com/8162805/30520382-68d5d64e-9ba4-11e7-9689-6b344512a5ff.jpg)

https://www.youtube.com/watch?v=Ixri3uAZzhI
https://www.youtube.com/watch?v=cwU4TvQEq0g

**Comment by Flohack74** [comment]
I think the problem is currently that while libhybris supports NFC already there are no low-level components in Ubuntu at all that would support this. I mean, our ubuntu Touch comes mostly from the desktop, and its very unlikely that a desktop PC has NFC builtin. So we are missing the Ubuntu side of things here, and I am not sure we can implement this without any good lib from some upstream.

**Comment by NeoTheThird** [comment]
Yep, that's true. But with GNU/Linux (ie not bionic based) becoming more and more popular, a solution for that might just come along. Let's keep this issue open, maybe someone comes up with an easy solution.

**Comment by ChloeWolfieGirl** [comment]
Can we not steal any nfc librarys from android, or see what plasma mobile does?

**Comment by NeoTheThird** [comment]
@ChloeWolfieGirl 
> Can we not steal any nfc librarys from android

That's not how it works. Android runs below libhybris which does also support NFC, but we need a library to expose and implement NFC into the OS. Since we don't want to do any not-invented-here bullshit (small team, limited resources, more pressing issues, blah blah), we shouldn't create that from scratch.

> see what plasma mobile does?

That's what we need to do. If Plasma Mobile, Sailfish OS or other libhybris-based projects supporte NFC, we can probably use their solution as well. Feel free to do some research ;)

**Comment by topiasv** [comment]
Sailfish OS just got NFC support on the latest update and seems like it can be found on the mer gitlab. This might help you get started with implementing NFC on Ubuntu Touch. Check it out [here](https://git.merproject.org/mer-core/nfcd).

**Comment by mariogrip** [comment]
nfc is now in the latest devel, but we are still missing the p2p data sending, so will keep this open.

Created this to track the nfc itself https://github.com/ubports/ubuntu-touch/issues/1697

**Comment by fredldotme** [comment]
Missing piece: https://gitlab.com/ubports/core/apparmor-easyprof-ubuntu/-/merge_requests/1

Happy easter! :)

**Comment by fredldotme** [comment]
This is now included in devel. A demo on how to access P2P functionality: https://github.com/fredldotme/ut-nfcd-p2p-demo

**Comment by ExoPlant** [comment]
Has this been added?

**Comment by fredldotme** [comment]
@ExoPlant Yes. OTA-17 includes this functionality and a demo on how to build P2P applications is in the link above your comment.

**Comment by ExoPlant** [comment]
👍

**Comment by ExoPlant** [comment]
I'd update devices.ubuntu-touch.io ASAP

**Comment by fredldotme** [comment]
The NFC listing depends on the porter or community members updating the details. See the Pixel 3a: https://devices.ubuntu-touch.io/device/sargo/

**Comment by ExoPlant** [comment]
> 
> 
> The NFC listing depends on the porter or community members updating the details. See the Pixel 3a: https://devices.ubuntu-touch.io/device/sargo/

I've updated the default in a merge request now
