### ISSUE TITLE
Alarm clock doesn't wake up the phone

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#288]
A legacy bug, that seems still present on ubports image.

Please see https://bugs.launchpad.net/canonical-devices-system-image/+bug/1588526 for more information

**Comment by ernesst** [comment]
The fixed might be this : https://git.launchpad.net/~ci-train-bot/repowerd/+git/repowerd-ubuntu-vivid-2276/commit/?h=repowerd-ubuntu-vivid-2276&id=6143d6a2d90df981d97de556fbe392e8ef617820

**Comment by torchedesc** [comment]
Did you select a day? I thought I had thrown same issue, but my alarm never went off because I didn't select a day.

**Comment by dark-eye** [comment]
@torchedesc @ernesst  If the issue is that  you didn't select a day it might be a clock-app issue as the  date of the next alarm date is determined there and not selecting a day should set the alarm to be a single shot to by fired on the selected time next occurrence.

If it`s reproducible please open an issue on the clock-app.

Thanks,

**Comment by wayneoutthere** [comment]
This link doesn't work above:
https://git.launchpad.net/~ci-train-bot/repowerd/+git/repowerd-ubuntu-vivid-2276/commit/?h=repowerd-ubuntu-vivid-2276&id=6143d6a2d90df981d97de556fbe392e8ef617820

**Comment by wayneoutthere** [comment]
hey everyone... I might have figured out the bug here.  I tried all of the above but it didn't work (well, I couldn't get the link above) and it seems that as long as I wipe out the default word  'alarm' in the field where you give the alarm a name,  and replace it with anything else, then when i press save everything works.  >However, if i leave 'Alarm' in the label field then the alarm doesn't save and... no surprise, doesn't wake me up.  Hope this helps.

**Comment by ernesst** [comment]
I can confirm after a week of test the device wakes up properly when all the days are selected. 

Can we move the bug to clock-app ?

**Comment by wayneoutthere** [comment]
I'm fine with that. Move it wherever you want but it seems there are two things to test: the days selected and the default name in the alarm label field,.

**Comment by Flohack74** [comment]
This issue was moved to ubports/clock-app#50
