### ISSUE TITLE
add Update information for Release Candidate images (what's new)

### ISSUE THREAD

**Issue by pixelr0** [ubports/ubuntu-touch#308]
as it is now you have no idea what's new in RC images. shouldn't be that annoying since there are not many RC images. i'm ok with devel not having logs/information since it's probably annoying to add logs/info with every devel image

**Comment by NeoTheThird** [comment]
Since changelogs have to be manually created, we decided to not use them for rc images. see #72. Since the rc images are mainly targeted at developers and testers, we take it for granted that people who want to be kept in the loop keep an eye on the progress on the milestones: github.com/ubuntu-touch/milestones
