### ISSUE TITLE
[16.04] [qt5.9] Missing Browser and its backend

### ISSUE THREAD

**Issue by nfsprodriver** [ubports/ubuntu-touch#328]
In order to move to qt 5.9.x base we need to rebuild oxide and webbrowser-app.

**Comment by sverzegnassi** [comment]
Efforts on Qt 5.9 has started three days ago, it will take months before we could see a first release candidate. Since the procedure for installing Qt 5.9 is not official - and it's fully experimental - this might be considered as an intermediate step to ensure that Mir and the rest of our middleware properly work with newer Qt versions.

**Comment by Flohack74** [comment]
@nfsprodriver please: 
1) Do not use the critical labels, they will block the CI from moving builds to rc or stable. this is for really critical bugs, that are discovered before a release day.
2) do not create new labels
3) This is not a bug, its just work in progress

**Comment by mardy** [comment]
Do we have a plan to make Ubuntu.Web a wrapper around Qt's WebEngine?

**Comment by mariogrip** [comment]
@mardy bulding qt WebEngine now http://ci.ubports.com/blue/organizations/jenkins/qtwebengine-opensource-src-packaging/detail/xenial_-_qt59/1/pipeline And will also try getting oxide to build.

Then we have both and can give them a test and see what's best for us

**Comment by sverzegnassi** [comment]
As we were mentioning yesterday on the supergroup, we might need to take further actions in case we want to transition from Oxide to QtWebEngine

- A number of webapps (based on Ogra's alternate container) and HTML5 apps depends on both `Ubuntu.Web` and `com.canonical.Oxide` QML modules. We might need an Oxide wrapper as well.
- An eventual deprecation of such applications might be hard, since most of them use regular `ubuntu-sdk-15.04*` or `ubuntu-sdk-15-04*-qml` frameworks. With our current means, we can only blacklist all the 15.04 apps, or nothing. We might need to develop a good deprecation policy.
- This is anyway not an issue for apps like uNav or uWriter, since we could expect Marcos (or others) to support our actions. It might become a problem for the plethora of glorified bookmarks or release-and-then-forget unmaintained apps that use the current WebView in some form.
- We also have to update the AppArmor policies provided by `apparmor-easyprof-ubuntu`, since they are hard-tied to specific Oxide features. (just a reminder)

**Comment by mariogrip** [comment]
I would say that we would keep both for a while, or make a layer that provides com.canonical.Oxide but using qtwebengine

**Comment by mariogrip** [comment]
both oxide and qtwebengine is now built. browser do now work with qt 5.9. but qtwebengine still need bringup work on mir

**Comment by ChloeWolfieGirl** [comment]
You brought me up, so I can work on mir!
