### ISSUE TITLE
Ubuntu Touch on OnePlus 3t -- what's holding us back?

### ISSUE THREAD

**Issue by chadfurman** [ubports/ubuntu-touch#340]
- Device: OnePlus 3t
- Channel: n/a
- Build: n/a

What's the LOE to make this happen?  Huge?  Months of experienced man-hours?  

What are the blockers?  Are we looking at issues with drivers?  Bugs in the apps?

**Comment by NeoTheThird** [comment]
Nothing in particular. In theory, a port using the legacy android container could be created. But since we want to go in a more generic direction with halium.org, all new ports are on hold for the moment. Afaik there already is a Halium port for Oneplus 3t in the works, so as soon as we switch to 16.04 (and with that to Halium), we'll probably be able to provide a development image for this and other devices.

I can't promise you an exact eta yet, but word on the street is, this should happen within a few months, depending on how testing goes.

If you want to know more about the porting process, check out docs.halium.org.

**Comment by ChloeWolfieGirl** [comment]
The OnePlus 3 already boots, I beleive it connects to wifi, no cellular, so yes, theres work in the port, but as NeoTheThird has said, Halium and 16.04 with the 3 core devices are the focus at the moment, but since the core devices have a early alpha of 16.04, it might not be to long until the op3 gets the same.

**Comment by marmistrz** [comment]
There's a working SailfishOS port for OnePlus 3: https://forum.xda-developers.com/oneplus-3t/development/sailfish-os-oneplus-3-3t-t3724264
Maybe you can reuse the worked done here.
