### ISSUE TITLE
new FP2 camera: Pictures and Videos captured with the front camera will be rotated by 180 degrees

### ISSUE THREAD

**Issue by mariogrip** [ubports/ubuntu-touch#370]
New camera module on FP2: Pictures and Videos captured with the front camera will be rotated by 180 degrees

**Comment by derkleinemannvomfeldweg** [comment]
For Sailfish OS, new camera is working now. Could this possibly help?

**Comment by Flohack74** [comment]
Yes it could, can you get infos what they did?

**Comment by wayneoutthere** [comment]
this was filed on Dec 17th... any hope in sight? 
i'm on 16.04 with a FP2 and I get upside down selfies! boo hoo.

**Comment by 5kup** [comment]
Same here... 16.04 stable, and I also tried rc...

**Comment by wayneoutthere** [comment]
someone said if you remove the cam from phone and re-insert it can fix it... i haven't tried this but.. I'm getting close :(

**Comment by dark-eye** [comment]
is the rotation in the viewfinder or in the final capture? (or both? :))

**Comment by wayneoutthere** [comment]
lol! i thought it was just me suffering with that 'move' 
yeah - both.  
but... if you take the photo with the camera UPSIDE DOWN - the photo is correct in the captured image.  pretty hard to make a handsome selfie that way :)

**Comment by luksus42** [comment]
> 
> 
> someone said if you remove the cam from phone and re-insert it can fix it... i haven't tried this but.. I'm getting close :(

Nope, that did not fix it.
(And it is also not possible to turn around the camera within the camera-module, if you plan to put it all together afterwards ;-))

**Comment by peat-psuwit** [comment]
After some digging in different codebases, I've found the following conclusions:

1. The FP2 cameras' orientation: I can confirm that the new FP2 front camera is rotated differently than the old one, and it's reflected in Android's camera API, which is passed onto libhybris & QT (but more on this later) [(1)](https://user-images.githubusercontent.com/6771175/59550492-78237700-8f95-11e9-8df9-a9fad8256426.jpg).
2. Ubuntu Touch's support for camera orientation: it seems like the QT pathway of Ubuntu Touch's camera support always assume that the back camera is rotated 90 degrees counter-clockwise [(2)](https://gitlab.com/ubports/apps/camera-app/blob/master/ViewFinderView.qml#L266) and that the front camera is always rotated the other way around [(3)](https://github.com/ubports/qtubuntu-camera/blob/5d7c6fa8acdb04fdaede5ca37718f6849ef5d243/src/aalmetadatawritercontrol.cpp#L106). Worst of all, both assumptions are made in different places (the first in `camera-app`, the latter in `qtubuntu-camera`).
3. The special cases for BQ Aquaris E4.5 & E5: after asking with a QA member with an E5, it turns out that the reported orientation from it is the same as the new FP2 front camera module [(4)](https://paste.ubuntu.com/p/B4ZzBQtRD9/), yet photo & video captured from it _does_ rotate correctly. Turns out, the orientation reported from the Android API is a lie and Ubuntu acknowledges this in Oxide source code (and also reveals that this applies to E4.5 as well)  [(5)](https://git.launchpad.net/oxide/tree/shared/browser/media/oxide_video_capture_device_hybris.cc#n92).
4. Different schematic for Android's and QT's orientation: Android's camera orientation is defined as "the angle that the camera image needs to be rotated clockwise so it shows correctly on the display in its natural orientation" [(6)](https://github.com/ubports/android_frameworks_av/blob/8c316ef19d87316f6a35dbc9ab516fcde2d5270a/include/camera/CameraBase.h#L35). However, QT's orientation is defined as "the physical orientation of the camera sensor" [(7)](https://doc.qt.io/qt-5/qcamerainfo.html#orientation). `qtubuntu-camera` currently passes this value as-is from Android API and has to be fixed.

So, the following work is required:
1. Update `qtubuntu-camera` to report orientation correctly, add the exception for E4.5 & E5, and remove the assumption about the "other way round" rotation (this should be done in the app).
2. Update `camera-app` to take the corrected orientation into account, and revert the device's orientation for the front camera.

I'll take care of the first work, and may work on the second one if no one else does it after I finished the first one.

**Comment by blaubaer01** [comment]
I confirm after update, the front camera works fine....
But with the main camera I have now an new issue, there I see only purple stripes.
After go back to OTA 9, main camera works fine...

**Comment by Dave1152000** [comment]
FP2
After OTA 10 both cameras orientation seems to be OK. Extreme slowness seems to be an issue and flash still not working

**Comment by jezek** [comment]
FP2 (2019-W32) - Upside-down rotation fixed, inconsistency spotted. Extreme slowness and non working flash confirmed.

Inconsistency:
In camera app, after switching to front camera mode the picture I see is a mirror like picture. (This part is ok)
After making a photo, the resulting image has left and right sides flipped. (And here is the inconsistency)

**Comment by peat-psuwit** [comment]
New FP2 camera's flash issue is tracked in #448. For the non-mirrored front camera image, that's expected. The captured image from the front camera will not be mirrored and will look like if someone looks at you.

For the slowness, I guess we can file a separated issue for that.
