### ISSUE TITLE
Wake up arm64 && amd64

### ISSUE THREAD

**Issue by mariogrip** [ubports/ubuntu-touch#390]
Since we have have support for building arm64 && amd64 we should start replacing the Jenkinsfiles on different xenial project to allow to rebuild for these arch. Once that's done start producing arm64 rootfs and make docs on how to add our repos on amd64 machines

**Comment by pixelr0** [comment]
welp trying to add the repo to desktop (can't say i know what i'm doing :P)
anyway

 sudo add-apt-repository 'deb http://repo.ubports.com/ xenial_-_mir26 main'
but i get this GPG error 

Reading package lists... Done
W: GPG error: http://repo.ubports.com xenial_-_mir26 Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4BD4B4D6DBB583F1
E: The repository 'http://repo.ubports.com xenial_-_mir26 Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4BD4B4D6DBB583F1
Executing: /tmp/tmp.5HLDBGhQRX/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv-keys
4BD4B4D6DBB583F1
gpg: requesting key DBB583F1 from hkp server keyserver.ubuntu.com
gpg: key DBB583F1: public key "UBports build <infra@ubports.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)

update
W: http://repo.ubports.com/dists/xenial_-_mir26/Release.gpg: Signature by key B551C909D750AA744948E9ED4BD4B4D6DBB583F1 uses weak digest algorithm (SHA1)
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/repo.ubports.com_dists_xenial%5f-%5fmir26_Release

**Comment by UniversalSuperBox** [comment]
We build an arm64 rootfs now, but there is no testing for it. I feel as if this bug is no longer actionable without specific repositories which must be repaired. I'll close it for now, but we can always edit and reopen.
