### ISSUE TITLE
Battery usage for Pro 5 with OTA3

### ISSUE THREAD

**Issue by mihaelmilea** [ubports/ubuntu-touch#407]
### Illustrations

- Device: turbo
- Channel: stable
- Build: OTA3

### Steps to reproduce

Use the device as usual, as before OTA3.

### Expected behavoir

Before OTA3 I would see some horizontal lines for battery usage graph during the times that the device was on standby.

### Actual behavior

Now it is a continuos down line with more consumption when the device is hardly used.

### Logfiles and additional information

With the top command I see that there is no particular process that uses the cpu. Also the device does not heat up. Another thing: it is very rare that I see now just one cpu core online, mostly 4 cores are used. Before OTA3 often there was only one core online and it seemed to me that the horizontal lines in battery usage graph were corresponding to the times when only one core was online.

The issue is the same with the latest build from devel channel.

**Comment by Guillerm2** [comment]
Device: Meizu Pro 5 Ubuntu Edition
Channel: stable
Build: OTA-3

I have the same problem since upgrade to OTA 3.

Disable WLAN, GPS and Bluetooth, only 4G activated:
Without using the phone (and without applications in the background), dropped the battery charge from 80% to 21% in six hours.

In Fly mode, disable WLAN, GPS, Bluetooth and mobile data (without SIM card):
Without using the phone (and without applications in the background), dropped the battery charge from 93% to 51% in six hours.

**Comment by arubislander** [comment]
Device: Meizu Pro 5
Channel: rc
Build: r15

I too have seen the battery drain steadily even when not in use. I must add that when I disable wifi (data is off on this phone as I do not have a data plan on that SIM) the drain is much slower, averaging about 1% per two hours.

**Comment by mihaelmilea** [comment]
Battery usage with data on:
![screenshot20180104_022102698](https://user-images.githubusercontent.com/30057613/34632474-ec67aa96-f275-11e7-874c-0a661cf506b6.png)

Battery usage with data off:
![screenshot20180105_213823767](https://user-images.githubusercontent.com/30057613/34632493-050255e2-f276-11e7-95fb-f1c3c3fd0034.png)

**Comment by Guillerm2** [comment]
Battery usage with only WiFi on:

![screenshot drop 1 wifi](https://user-images.githubusercontent.com/28327739/34754727-c64930b2-f5bf-11e7-8fb2-72a11368829a.png)

Battery usage with WiFi off:

![screenshot drop 1 without wifi](https://user-images.githubusercontent.com/28327739/34754753-f55caee2-f5bf-11e7-83d3-8cb147372c35.png)

Today the drain with WiFi off is stable (1% in 9 hours), mysteriously. But the rest of the days, since I upgrade to OTA 3 (25 of December), the drain was like the screenshot (except the 26 of December).
All days I check the battery drain and reset the phablet.

**Comment by mihaelmilea** [comment]
Without doing anything apart from a restart, the issue seams to be solved now. If nobody else needs this post then I think I will close it.

**Comment by Guillerm2** [comment]
Mihaelmiela, wait a little, please. Now, without WiFi and SIM, it's OK (5% in 24h), like 26 of December; but in between the consumption was very hight, and I restarted every days.
Tomorrow I will test with data and SIM card.

**Comment by Guillerm2** [comment]
Today was horrible. I found the phablet shut down to 21:17, with very much hot; probably it was off because of the overheat protection. The phablet was on standby, without applications in the background.
Before the last charge the drain was worrying.

Battery usage with data on:
![turbo automatic shutdown for overhot png](https://user-images.githubusercontent.com/28327739/34910943-4c306fe0-f8bf-11e7-9e32-b66404c922c5.png)

 How this bug could be confirmed? 
There are two similar issues:
[https://github.com/ubports/ubuntu-touch/issues/400](url)
[https://github.com/ubports/ubuntu-touch/issues/387](url)

**Comment by mihaelmilea** [comment]
Well then, if it was overheating there is a big chance that the CPU was used 100% and with terminal -> top command you can identify which process is using the CPU. Can you find that?

**Comment by Guillerm2** [comment]
I could not use top, I found the phablet off, casually shortly after shutdown.
Then I turned on it and I was observing the phablet for a long time, but the consumption was 10% in 12 hours with data (stand by).

**Comment by Flohack74** [comment]
Hello Guys,

I set the ping interval in the push server now to 5 minutes. Anything above will likely impact the detection of a dead session and might lead to missed notifications. Please reboot your devices and try to observe if you find a difference.

**Comment by mihaelmilea** [comment]
Thank you @Flohack74 . I did the reset and I will report back here.

Back when I reported this issue I tried `stop ubuntu-push-client` as in https://github.com/ubports/ubuntu-touch/issues/415 and I believe that solved the issue. But after a reset (when the push-client was back) I didn't seem to have a problem anymore, at least while in wifi. Still it is true that these issues require many days of testing in different conditions.

**Comment by Flohack74** [comment]
The push client might only read the server config once at startup, that could affect it a bit. So, for any repetitive testing you want to do please make sure you restarted the device once, to initialize everything with the latest values.

**Comment by Guillerm2** [comment]
Hello Flohack74,
Thank you. After restart the device the consumption was 1,5% in 3:15 hours, with data (stand by).
Until the Monday I can not do more test. Yesterday was 20% in 17h, and Tuesday  was 33% in 21h, with data (stand by). The WiFi was off all time.

**Comment by mihaelmilea** [comment]
If anyone is interested in an update for the modem drivers please take a look at this: https://forums.ubports.com/topic/929/update-meizu-pro-5-baseband/11

As for me I am ready to close this issue if nothing new comes up... Anyway we are all expecting to move forward to Xenial... :)

**Comment by Guillerm2** [comment]
Thanks mihaelmilea.

The device returned to normal consumptions with data:
- Stand By data on: 10% 18h.

Stand By with WiFi: 4% in 5h. A little high, but is not like the previous drains.
