### ISSUE TITLE
Ubuntu Push Client drains battery

### ISSUE THREAD

**Issue by mdehollander** [ubports/ubuntu-touch#415]
- Device: MX4
- Channel: stable
- Build: UBports OTA-3

### Steps to reproduce

If the ubuntu-push-client service is running, the battery drains very quick. Much more than before OTA-3. When the device is on flight mode or the Ubuntu Push Client is stopped with `stop ubuntu-push-client` the battery usage is much lower.

### Expected behavoir

The power consumption should be similar with the ubuntu push client running or not. 

### Actual behavior

With the Ubuntu Push Client running the battery drains much more quickly, this can be see in the Battery graph

### Logfiles and additional information

[Contents of `/var/log/repowerd.log`](https://paste.ubuntu.com/26341821/)

Screenshot of the battery graph (from 00:00 - 10:00 flight mode, 10:00 - 16:00 ubuntu push client stopped, 16:00 - 20:00 ubuntu push client started):
![battery graph](https://i.imgur.com/efuZYXw.png)

**Comment by Flohack74** [comment]
Hi, I made a quick stats over 10hrs to know how often devices have to reconnect:
![zwischenablage01](https://user-images.githubusercontent.com/16186470/34677210-50d25752-f487-11e7-9ad9-a1157651fddb.png)

As you can see most devices connect 1 or 2 times per hour. Thereafter the count falls off pretty quick to some device with 6 times per hour (60 mark). Some strange device has 342 connects in 10hrs though :)

**Comment by Flohack74** [comment]
Out of 720 devices only 28 connect more than 60 times. However, there is also keepalive messages flowing. I reduced the keepalive interval now, so please observe again during the next days. I hope smth has changed for you.

**Comment by mdehollander** [comment]
Nice analysis. Is it possible to see on the device how many times it connects, maybe in the repowerd log file?
And the keepalive is set on the ubports push server right? So I don't have to change channel?

**Comment by Flohack74** [comment]
Well you would have to grep your logfile, but its a very short one. I can make maybe a debug info for that (upcounter for session creation). Yes the ping interval is set on the server, so no action required

**Comment by derkleinemannvomfeldweg** [comment]
Maybe the strange device with 342 connects is my FP2 which has a high battery drain when on mobile data (#400)? But if so, why does this behaviour occur only on mobile data and not on wifi?
Since I stopped the Push Client with `stop ubuntu-push-client`, my battery drain seems to have dropped to an expected level (97% after 2 hours).

**Comment by Flohack74** [comment]
@derkleinemannvomfeldweg you can send me your push client ID via PM to florian@ubports.com - you should be able to get it from the log hopefully ;) - then I can take a look.

**Comment by derkleinemannvomfeldweg** [comment]
Could you specify in which log I have to look and what I should look for, e.g. how the ID looks like?

**Comment by Malizor** [comment]
I confirm this problem on my Nexus 4.
Since OTA 3, my battery can lose ~70% of it's capacity overnight, with no app opened and mobile data enabled.

After seeing this ticket yesterday I disabled the ubuntu-push-client service and, this morning, I noticed I only lost 3% of my battery overnight. Big difference!

Let me know if I can help in any way. For now I'm leaving the service disabled.

**Comment by HendriXXX** [comment]
I can also confirm this on my N5. After disabling service, mobiledata consumes battery about 1% per hour, like same as wifi connected. Service ON it is about 5-6% per hour which is too much.

**Comment by Flohack74** [comment]
I changed ping interval now to 5 minutes, see my comment in #407 - Please do a clean restart and test once more with your settings. @HendriXXX I can integrate your values in the config for all users, but we need to make sure that everybody still gets notifications and nothing is lost (just to be sure, I am not expecting any loss with these values).

**Comment by Flohack74** [comment]
Now I see that poll interval increase might lead to getting notifications only once an hour - this is definitely too long. What was your experience about lags in delivery?

BR

**Comment by HendriXXX** [comment]
@Flohack74  With my push settings I get email notifications every hour, but Telegram messages still arrives "instantly" no matter what I put in the config file. I currently have no need to get gmail notifications more often. Of course others needs may vary..

Is it possible to get "/proc/timer_stats" support in N5 kernel? It needs "CONFIG_TIMER_STATS=y" option compiled in the kernel. N4 has it already but N5 doesn't. I want to use "eventstat" to examine wakelocks but it wont work without it. It may tell if some app/process wakes device too often.
Is there instructions how to modify, build and install new kernel in UBports?

I think there is also some problem with Wifi network scanning. It may not be related to this push client problem. If I go out and leave phone idling with **mobiledata connected** AND **Wi-fi switched ON**, battery drops faster than **wifi switched OFF**.
Is it constantly scanning available wifi hotspots? Maybe it has too aggressive settings..

**Comment by Flohack74** [comment]
Yes Wifi is also a candidate for drain :) - thx for your findings, I am on business trip but will come back to this in the next days. Telegram messages are pushed whenever you are online, otherwise they are queued, and in theory should be oulled after reconnection. SO for Telegram the 60 minutes might not apply, but or other usages maybe they do.

**Comment by tihom7** [comment]
@HendriXXX - I cannot edit /etc/xdg/ubuntu-push-client/config.json file. Could you share how can I write to it, please? Thanks

**Comment by Flohack74** [comment]
you need to:
```
sudo -i
mount -o remount,rw /
```
Then it should work

**Comment by tihom7** [comment]
Thank you Florian. Unfortunatelly it does not work again. With Nano it gives me some choices to append, prepend or whatever.

**Comment by tihom7** [comment]
Done. Thanks again.

**Comment by lduboeuf** [comment]
any news regarding that bug, should we keep that issue open ?

**Comment by UniversalSuperBox** [comment]
With further development of Ubuntu Touch and what we've learned about its battery management, I believe this issue can be closed.

Many of our battery issues nowadays are caused more by incorrect hotplugging and WiFi chipsets never going to sleep rather than any services running on the host. However, we can look into cases of high battery use as they come up. As it is, I don't think this report is relevant any more.

Thank you to everyone who participated. :)
