### ISSUE TITLE
[xenial] Apparmor needs huge update for QML cache

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-touch#439]
It seems that apparmor is blocking access to the App´s QML cache:
`[  148.262621] type=1400 audit(1388297235.779:260): apparmor="DENIED" operation="open" profile="com.ubuntu.clock_clock_3.8.487" name="/home/phablet/.cache/QtProject/com.ubuntu.clock/qmlcache/14a9b877db859b3508750b744fdbac56988354fa.qmlc" pid=7232 comm="QQmlThread" requested_mask="r" denied_mask="r" fsuid=32011 ouid=32011`

Just as an example. Probably affects all click apps. So we need to find the policy where this can be adjusted for all click apps.

**Comment by Flohack74** [comment]
Cc for @mariogrip in case you wonder why the Apps are not speedy ;)

**Comment by Flohack74** [comment]
I see here 2 options: Either allow access to /home/phablet/.cache, but thats contradictory to the confinement idea of a click package, or redirect Qml cache calls to the .cache folder of each click. Can we somehow find out how this could be done?

**Comment by dpniel** [comment]
What image & version is this on this should have been fixed in the UITK as that cache path is wrong see https://github.com/ubports/ubuntu-ui-toolkit/pull/4 and see my comments in https://github.com/ubports/apparmor-easyprof-ubuntu/pull/1

But the short of it is .cache/QtProject is the wrong path and QtProject is being set by qmlscene as the organisation name. I wouldn't change apparmor paths here as it will break the standard XDG_PATHS all apps have been used to on vivid.

**Comment by mariogrip** [comment]
```

**Comment by mariogrip** [comment]
I'm on the latest images on a freshly flashed nexus 5 (r212) and it seems to work fine here:

```
phablet@ubuntu-phablet:~$ ls .cache/com.ubuntu.clock/
qmlcache
```

**Comment by Flohack74** [comment]
Can you execute aa-status for me please ;)

**Comment by mariogrip** [comment]
```

**Comment by mariogrip** [comment]
```
phablet@ubuntu-phablet:~$ sudo aa-status 
[sudo] password for phablet: 
apparmor module is loaded.
45 profiles are loaded.
45 profiles are in enforce mode.
   /sbin/dhclient
   /usr/bin/lxc-start
   /usr/bin/media-hub-server
   /usr/bin/mediascanner-service-2.0
   /usr/lib/*/mediascanner-2.0/mediascanner-extractor
   /usr/lib/NetworkManager/nm-dhcp-client.action
   /usr/lib/NetworkManager/nm-dhcp-helper
   /usr/lib/connman/scripts/dhclient-script
   /usr/lib/cups/backend/cups-pdf
   /usr/lib/lightdm/lightdm-guest-session
   /usr/lib/lightdm/lightdm-guest-session//chromium
   /usr/lib/telepathy/mission-control-5
   /usr/lib/telepathy/telepathy-*
   /usr/lib/telepathy/telepathy-*//pxgsettings
   /usr/lib/telepathy/telepathy-*//sanitized_helper
   /usr/lib/telepathy/telepathy-ofono
   /usr/sbin/cupsd
   /usr/sbin/cupsd//third_party
   /usr/sbin/dhcpd
   address-book-app
   com.ubuntu.calculator_calculator_2.2.322
   com.ubuntu.calendar_calendar_0.6.2
   com.ubuntu.camera_camera_3.0.0.659
   com.ubuntu.clock_clock_3.8.487
   com.ubuntu.filemanager_filemanager_0.4.528
   com.ubuntu.gallery_gallery_2.9.6
   com.ubuntu.music_music_2.5.1019
   com.ubuntu.reminders_pushHelper_0.5.568
   com.ubuntu.reminders_pushHelper_0.5.568//oxide_helper
   com.ubuntu.reminders_reminders_0.5.568
   com.ubuntu.reminders_reminders_0.5.568//oxide_helper
   com.ubuntu.terminal_terminal_0.8.latest
   com.ubuntu.ubports_ubports_1.8
   com.ubuntu.ubports_ubports_1.8//oxide_helper
   com.ubuntu.weather_weather_3.4.248
   lxc-container-default
   lxc-container-default-cgns
   lxc-container-default-with-mounting
   lxc-container-default-with-nesting
   messaging-app
   openstore.openstore-team_openstore_2.13
   udm-extractor
   unity8-dash
   webbrowser-app
   webbrowser-app//oxide_helper
0 profiles are in complain mode.
7 processes have profiles defined.
6 processes are in enforce mode.
   /sbin/dhclient (31367) 
   /usr/bin/media-hub-server (3258) 
   /usr/lib/telepathy/mission-control-5 (3119) 
   /usr/lib/telepathy/telepathy-ofono (3131) 
   com.ubuntu.clock_clock_3.8.487 (13239) 
   unity8-dash (3625) 
0 processes are in complain mode.
1 processes are unconfined but have a profile defined.
   /usr/bin/lxc-start (788
```

**Comment by Flohack74** [comment]
Thats strange, my clock tries to create the QtProject folder on top cache level, when I remove it also:
`[ 1448.204469] type=1400 audit(1388298535.719:981): apparmor="DENIED" operation="mkdir" profile="com.ubuntu.clock_clock_3.8.487" name="/home/phablet/.cache/QtProject/" pid=20580 comm="QQmlThread" requested_mask="c" denied_mask="c" fsuid=32011 ouid=32011`

Ok lets put this on hold for the moment. Just need to find out how Qt determines the cache path.

**Comment by dpniel** [comment]
It determines it from `QCoreApplication::applicationName` and `QCoreApplication::organizationName` see this [comment](https://github.com/ubports/apparmor-easyprof-ubuntu/pull/1#issuecomment-357633815) which also links to where in qmlscene the org name is getting set

**Comment by dpniel** [comment]
The patch to UCApplication is supposed to undo qmlscene setting the org name.

**Comment by Flohack74** [comment]
Oh cool so this is already in the latest root fs? Sorry but I did not know you were already working on this ;)

**Comment by mariogrip** [comment]
@Flohack74 yes, should be in the latest rootfs

**Comment by Flohack74** [comment]
Cross-Referencing https://github.com/ubports/apparmor-easyprof-ubuntu/pull/1

**Comment by dpniel** [comment]
Ok let's move the discussion back over here instead of that pull-request as that patch doesn't quite solve this particular issue anyway.

In short this issue is only present on apps that use qmlscene and how it tries to cache the initial compiled qml data on launch. The qml runtime is trying to store the cached data in QStandardPaths::CacheLocation, and the cache location is derived from the application name and organisation which qmlscene initially sets to QtProject/QtQmlViewer and once MainView is loaded the UITK overrides those values to the "real" application name and storage locations should work as expected. So at the moment we lose the caching for the launch which is where we want it most. :-(

I propose we do two things here:

1. Patch qmlscene to pick the `APP_ID` of the environment and derive the application name from it. If no APP_ID is set then the normal behaviour should continue. This patch should only be short term and only be kept for minor Qt version changes.
2. Create a new qml application launcher that does all the right things and promote it's use from now on for launching qml only apps, as the qmlscene patch will be removed on the next Qt major vesion bump.

**Comment by dpniel** [comment]
This should be fixed now. Moving to QA

**Comment by NeoTheThird** [comment]
As far as i can see, this seems to work. Anything to look out for while testing @dpniel?

**Comment by dpniel** [comment]
@NeoTheThird the only thing to really look for is apparmor denials for apps trying to access paths like /home/phablet/.cache/QtProject/* (mainly apps that use qmlscene)

**Comment by NeoTheThird** [comment]
Okay, so i tried a bunch of things and didn't see any denials for the cache. Seem to work. Good job, Dan!
