### ISSUE TITLE
[xenial] can't make sshd start by default 

### ISSUE THREAD

**Issue by ch0001** [ubports/ubuntu-touch#444]
- Device: frieza
- Channel: 16.04/devel
- Build:r23

### Steps to reproduce
reboot device

`> android-gadget-service status ssh`
`ssh enabled`

`> service ssh status`
`ssh stop/waiting`

### Expected behavior
sshd is running (like on 15.04/devel)

### Actual behavior
sshd is not running

### Logfiles and additional information
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/1657706/UTdmesg.txt)

[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/1657709/UTlogcat.txt)

**Comment by UniversalSuperBox** [comment]
This should be fixed by ubports/lxc-android-config#4. Anyone who wants to test can, by doing the following.

Note: This involves making your system image read-write and installing different versions of packages. Your changes should be overwritten by an OTA update, but you should also be aware that it could have other unintended consequences. A reinstall of Ubuntu Touch will fix any strange behavior found.

```
sudo mount / -o remount,rw
sudo cp /etc/init/ssh-property-watcher.conf /etc/init/ssh-property-watcher.conf.bak
```

Now, replace `/etc/init/ssh-property-watcher.conf` with [this updated version](https://raw.githubusercontent.com/UniversalSuperBox/lxc-android-config/ef057d857f9b588e4f48667e31fb20eb1bce4b10/etc/init/ssh-property-watcher.conf)

When you're finished testing, simply do the following:

```
sudo mount / -o remount,rw
sudo mv /etc/init/ssh-property-watcher.conf.bak /etc/init/ssh-property-watcher.conf
```
