### ISSUE TITLE
Camera date stamp option location

### ISSUE THREAD

**Issue by UKPhil** [ubports/ubuntu-touch#458]
We now have the ability to add date stamps to pictures that we take on out Ubuntu devices and the stamp is correctly positioned, which is great.

Is there any way the date stamp on/off option could be moved to the “Settings” section (when you click the double arrows up, rather than the advanced options section? The option to add a date stamp should be an option and the ability to add time, change the stamp position and colour should be under advanced.

Following on from this is there any plans to add the ability to add the time, change the stamp colour and position?

**Comment by dark-eye** [comment]
Hey @UKPhil,

the reason its unreality advanced option is that I didn't  want to clutter the quick options menu and since this is an option that people will probably only alter once it shouldn't  add noise to the quick options menu.

about adding more settings to the rendering there is an open issue (which I currently working on ) to add time to the stamp ill add the request for the position and color to it.
what I'm planing is to change the 'avanced options' title  to 'further options' or simply Settings and add an expandable sub menu to the datestamp option.

the future plan is to move this feature to a plug in and design a common menu structure to all plug ins.

**Comment by UKPhil** [comment]
@Eran thanks for getting back to me so quick about this. From reading what you say I see what you mean about the position and agree that users will not use it as much as the other options in Settings.

From the sounds of it, you are working on some good things for the camera app and I cannot wait to see the output.

Is there any plans to add things like panoramic view and a good photo editing tool?

**Comment by dark-eye** [comment]
@UKPhil Sorry it took me along time to write back....
Yes There is plans i`m working on adding plugin system so we can add this kind of improvements as plugins to the camera. 
however I had little time to work on open source lately so it might take some time... (unless some else will do it :))
