### ISSUE TITLE
 Strange sounds after hanging up phone call from other party

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#49]
ubuntu 15.04 r7
If other party hangs up phone call, one very loud peeb-boob are coming. That is all, then everything runs fluently.

Reported by https://launchpad.net/~sebastian-gallehr

**Comment by timovwb** [comment]
Same happens to me on the Nexus 5 (I can't add the Hammerhead label).

**Comment by bastos77** [comment]
In addition if I get a call waiting signal while doing a phone call (Anklopf Signal) this is also much too loud.
Those two bugs maybe could be solved with the same adjustment.

**Comment by mihaelmilea** [comment]
I also need this. Especially when the call connection is not good and I increase the volume and stick the phone to my ear and then disaster strikes! :)

The same for when I receive a text message during a call.

**Comment by bastos77** [comment]
Even in OTA 2 a very annoying bug on FP2. Really harmful. Hurts in the ear!

**Comment by UKPhil** [comment]
I have this sound too when I have a call end by the other person in my OnePlus One.

**Comment by Anne017** [comment]
I am also affected by the same issue (after hanging up the phone seems to briefly switch to hands-free mode with this very loud sound).

Device: FP2
Channel: stable
Build: 15.04 r3 (OTA 3)

**Comment by natineo** [comment]
Same problem here with my device after the updates, please put this issue in the to-do list for next update

Device: FP2
Channel: stable
Build: 16.04 (OTA-10)

**Comment by leebaylis** [comment]
Me too, people look at me really weird when I yank the phone away from my ear and swear at it on trains. 
I get two full volume beeps out of the phone earpiece and then a third out of the speaker. 

Device: FP2
Channel: Development
Build: 16.04 LTS - armhf (20191121)

**Comment by Flaburgan** [comment]
I'm currently trying a [completely new port](https://forums.ubports.com/topic/3658/fairphone-2-fp2) of the Fairphone 2 based on Halium 7.1 (so Android 7.1) instead of the old 5.1. Unfortunately, I still reproduce that bug even with that new port.

**Comment by FPfabi** [comment]
Same error on FP2
- Device: FP2, New Camera Module
- Channel: Edge
- Build: 2020-W18, 16.04 LTS

**Comment by Rom4nB** [comment]
Is there any news about this issue?

It seems to be a very old issue. What is unclear to me: does it still affect other devices (hammerhead, bacon) or only the FP2? Many people in this issue report seem to use a FP2.

I am also using UT with FP2. The noise is really bad, especially when it comes unexpected (call connection rips of because either me or the other person loses phone signal e.g. in train). It really hurts in the ear and I assume it actually makes damage to the ear. :P

Device: FP2
Channel: stable
Buld: 16.04 LTS OTA-12

**Comment by lduboeuf** [comment]
need to be confirmed also on RC ?

**Comment by Flaburgan** [comment]
> need to be confirmed also on RC ?

It is still there even in `devel`

**Comment by Flohack74** [comment]
well finally found the problem. Will try to fix it with the linked PR ;)

**Comment by jezek** [comment]
Device: FP2 (FP2-userdebug 5.1.1 LMY48W ...)
Channel: RC
Build: 2021-W18

Not fixed.
I called, someone and asked them to end the call. The loud beeb-beeb-beep sound was there and pierced my eardrum again.

**Comment by Flohack74** [comment]
We will wait with reopening this after FP2 got updated to Halium 7.1 - I want to land this in OTA-18 maybe. Then please re-evaluate. You can already to this today by switching to the halium-devel channel. But please be aware you need to wait until OTA-17 is out otherwise you cannot switch back to stable (only devel or RC).
