### ISSUE TITLE
[xenial] Images starting to get big

### ISSUE THREAD

**Issue by mariogrip** [ubports/ubuntu-touch#521]
I ran into a problem trying to flash the pro 5 where it was missing 2MB in the cache partition to finish the job. We need to go over and see what we can remove.

**Comment by PhoenixLandPirate** [comment]
Only camera images should be big, not device images.

**Comment by NeoTheThird** [comment]
That's some wisdom @PhoenixLandPirate!

@mariogrip Where's the package list at now?

**Comment by tsimonq2** [comment]
How big is "too big" and what counts in this?

I wonder if we can do some sort of compression of the read-only image...

**Comment by UniversalSuperBox** [comment]
### The problem

"Too big" means that our image files have become too large to fit on the `/cache` partition of any of our devices. Images (and, on updates, image diffs) are downloaded to that partition and later installed by system-image in recovery. In this case, the Meizu Pro 5 doesn't have enough space to store our rootfs images and, therefore, cannot update.

### Compressing the read-only image?

Compression of read-only images is exactly what squashfs is for, but Canonical was never able to use it presumably due to the following:

* It's impossible to remount the file as read-write, a useful feature for developers and tinkerers. I would argue that it would be okay to remove this 'feature' assuming we can provide a great alternative for running all of your favorite tools in Libertine.
* It wasn't enabled by default in Android kernels (and they probably had enough config changes to test as it was) [1]
* The decision to use raw image files may have been made before there were nice tools available for diffing squashfs (and then installing the diffs)
* (most importantly) all preinstalled Ubuntu Touch devices have the rootfs on the `/system` partition rather than an image file in `/data`, so there was really no huge push to make this boot method better.

### Compressing the read-only image.

I've been able to complete a quick experiment in using a squashfs with the current `halium-boot` setup on the Moto G5 Plus. All I had to do was:

1. Enable `CONFIG_SQUASHFS` in my kernel, rebuild it, flash it to the device
1. Download the rootfs image. `adb pull /data/rootfs.img`
1. Mount the rootfs read-only somewhere. `sudo mount rootfs.img mount/ -o ro`
1. Create a squashfs from the rootfs. `mksquashfs mount/ rootfs.img.squash`
1. Push the squashfs to the device. `adb push rootfs.img.squash /data/rootfs.img`

That was it. The device booted into the rootfs, but it appears that writable bind-mounts aren't currently working. I'd only troubleshoot this further if we decide that it's a direction that we want to go in.

[1] with Android A/B partitioning, the system image is commonly stored as a squashfs on disk. That means that upstream device vendors are enabling and using squashfs!

**Comment by mariogrip** [comment]
Well the data rootfs is not the problem, its the cache partition used for install/update that is too small. 

Since we already use heavy compression there (tar.xz) there, the other 3 options are, make the update files smaller (by removing files), use a different partition for the biggest tarball or use network to finish the job after boot. 

And for now the first one is the best one, we ship qt4 (quite big), but we dont need it, the only reason why its there is that telepathy-qt5 depends on it (due to poor packaging, not due to it needs it)

**Comment by mariogrip** [comment]
ugh, merged the other issue, and this closed automatically! reopen since this will become a problem later when we add more stuff. so not fixed, just postponed the issue.

**Comment by mariogrip** [comment]
I know, its pretty cool but i always forgets :P

**Comment by UniversalSuperBox** [comment]
If the issue is postponed for now, would it make sense to either move it to a different milestone or a new issue which better describes it?
