### ISSUE TITLE
[xenial] OSK dissapears when pressing multiple times the numeric key

### ISSUE THREAD

**Issue by ivoxavier** [ubports/ubuntu-touch#567]
- Device: Fairphone 2
- Channel: 16.04/devel
- Build: 251

### Steps to reproduce
Open Keyboard, press multiple times the numeric key. Sometimes just one touch is enough to break the OSK. See it on [action](https://youtu.be/jUBusDtTCiQ)

### Expected behavior
does not break

### Additional information
It seems that affects only Qualcomm devices. On the telegram group some users said that e4.5 is ok, other can reproduce this on nexus 5.

I've already wiped the phone, set it with different languages and always keeps happening

**Comment by Flohack74** [comment]
Can you make the same test (same device) on 15.04 too? Just to be sure... :)

**Comment by ivoxavier** [comment]
Just flashed OTA-3 and it works fine, can't reproduce this on 15.04.

**Comment by UniversalSuperBox** [comment]
I can confirm this on the Nexus 5 and Fairphone 2, but I made an interesting observation. The keyboard only disappears when tapping the left or bottom edge of the keyboard around the layer switch button. Tapping in the middle of the button, no matter how many times, will not reproduce this issue.

**Comment by BlueKenny** [comment]
I can confirm this issue on Bacon

**Comment by NeoTheThird** [comment]
Does not affect M10 HD and Nexus 5.

**Comment by Flohack74** [comment]
I tested on OPO and krillin, they are also not affected. But my hammerhead is. @NeoTheThird do you have the offset issue on startup on your N5?

**Comment by NeoTheThird** [comment]
> @NeoTheThird do you have the offset issue on startup on your N5?

No.

**Comment by mariogrip** [comment]
Are everyone on the latest build? seems we have some weirdness going on here.

**Comment by Flohack74** [comment]
I updated to latest nightly before testing it. My N5 has the display offset problem, so maybe its a certain batch of hardware that also exposes this digitizer issue. Note that it happens on the lower left edge, not the bottom edge. For example I cannot make this work on the shift key´s left edge.

**Comment by UniversalSuperBox** [comment]
For QA:

The workaround applied by https://github.com/ubports/keyboard-component/commit/9148f38bd72a3c53f0355476b7c4a1603c0a157d fixes this problem in most cases. The problem appears to be in something handling touch input above Maliit. Touch points when pressing on the edges of the screen (and occasionally anywhere else) will start at the physical touch point but end hundreds to thousands of pixels away. The keyboard suddenly dismissing was caused by touch points starting at, say, 100px and ending at 1200px. That number is completely impossible as Qt origins are at the top left. The touch point ended about 1000px off the bottom of the screen.

Anyway, I digress. The workaround should reject most invalid dismiss-causing touches and log a warning in `.cache/upstart/maliit-server.log`. Some invalid dismisses may still occur, but I've been able to sit and press the button for up to a minute without any dismisses.
