### ISSUE TITLE
Messages app / history daemon not working correctly after migration to ubports image

### ISSUE THREAD

**Issue by ZeroPointEnergy** [ubports/ubuntu-touch#570]
- Device: BQ Aquaris E5
- Channel: stable
- Build: last Canonical OTA -> Ubuntu 15.04 (r3)

After migrating my BQ Aquaris E5 from the last Canonical OTA image to the newest Ubports image the messaging app did not show any sms anymore. While I was still able to send and receive sms, neither the outgoing nor the incoming sms showed up in the messaging app.

### Steps to reproduce
Update from the latest Canonical image to the most recent Ubports stable image with the Ubports installer.

### Expected behavior
The messaging app should display the old messages as well as the new received and sent ones.

### Actual behavior
The app did not show any messages, old or new received or sent. When started it spend a long time what appeared like loading the messages but no messages got loaded.

### Logfiles and additional information
I managed to get new received and sent messages to show up in the app again by moving ~/.local/share/history-service/history.sqlite away so it would create a new database file.

I tried to dump the old database into a new file to make sure the cause is not corruption. The dump worked, but the app still did not show the messages.

I finally dumped the schema of both the new and the old database and there seem to be some differences in some tables which may account for the problem:
https://paste.ubuntu.com/p/wkJHgwbc63/

**Comment by lduboeuf** [comment]
how did you migrate from Canonical image to UBports one ?

**Comment by ZeroPointEnergy** [comment]
I just used the the Ubports installer

**Comment by lduboeuf** [comment]
I didn't know that the installer is able to keep datas. Can someone  confirm that ?

**Comment by AlainW94** [comment]
it seems that it failed to upgrade the scheme of the database. So I run the following scripts on my old DB (with DB browser sqlite) in order to manually upgrade it : 

- change the version of the scheme in the table schema_version from 12 to 18
Then run this scripts : 

`CREATE TABLE chat_room_info (
    accountId varchar(255),
    type tinyint,
    threadId varchar(255),
    roomName varchar(255),
    server varchar(255),
    creator varchar(255),
    creationTimestamp datetime,
    anonymous boolean,
    inviteOnly boolean,
    participantLimit integer,
    moderated boolean,
    title varchar(1024),
    description varchar(1024),
    persistent boolean,
    private boolean,
    passwordProtected boolean,
    password varchar(512),
    passwordHint varchar(512),
    canUpdateConfiguration boolean,
    subject varchar(1024),
    actor varchar(512),
    timestamp datetime
, joined boolean, selfRoles integer)`

`update  text_events set informationType=1`

`alter table thread_participants add column  "alias" varchar(255);
alter table thread_participants add column "state" tinyint;
alter table thread_participants add column roles tinyint;`

`update thread_participants set state=0`

`alter TABLE threads add column chatType tinyint;`

`update threads set chatType=1`

`CREATE TRIGGER text_threads_delete_trigger AFTER DELETE ON threads
FOR EACH ROW WHEN old.type=0
BEGIN
    DELETE FROM text_events WHERE
        accountId=old.accountId AND
        threadId=old.threadId;
END`

`CREATE TRIGGER voice_threads_delete_trigger AFTER DELETE ON threads
FOR EACH ROW WHEN old.type=1
BEGIN
    DELETE FROM voice_events WHERE
        accountId=old.accountId AND
        threadId=old.threadId;
END`

By running all this script on the history.sqlite on my computer, replacing the file in .local/share/history-service/history.sqlite, after a reboot, I was able to get back all my SMS and voice call history.

Just in case if this happens to somebody else, hope that it can help.

**Comment by UniversalSuperBox** [comment]
I feel that the tail on this bug is probably long enough, most people who will upgrade probably have already. If someone runs into this again, we do have a workaround that we can try. Otherwise it seems like there weren't too many people who ran into it.
