### ISSUE TITLE
[xenial] Printer setting N5 missing

### ISSUE THREAD

**Issue by ernesst** [ubports/ubuntu-touch#612]
- Device: N5
- Channel: Xenial
- Build: 389

### Steps to reproduce
Going to phone setting, 

### Expected behavior
printer setting should be present

### Actual behavior
No printer setting, while on my Nexus 4 - Xenial, it is.

**Comment by tydell** [comment]
I don'thave any problems with printers settings option on my N5 D821 on 16.04 devel. I see this option all the time. I'm playing with 16.04 asmy daily driver since r373.

![screenshot20180520_233933133](https://user-images.githubusercontent.com/1691858/40283994-b58cce08-5c87-11e8-980b-228a388b92ae.png)
![screenshot20180520_233937324](https://user-images.githubusercontent.com/1691858/40283995-b5a7d590-5c87-11e8-8b48-e8796a5dffc3.png)
![screenshot20180520_233941894](https://user-images.githubusercontent.com/1691858/40283996-b5c1f70e-5c87-11e8-8a26-3bd82578cdc4.png)

**Comment by Flohack74** [comment]
@tydell Can you check this with latest nightly? I got the following issue https://github.com/ubports/ubuntu-touch/issues/619 and I am on FP2 with this...

**Comment by tydell** [comment]
I'm on r391 on Nexus5 and printer settings is there as usual. It is usable and have no freeze.

**Comment by Flohack74** [comment]
This is really interesting. Let me wipe my phone xD

**Comment by Flohack74** [comment]
Printer functionality will be targeted for OTA-5.

**Comment by advocatux** [comment]
I don't have printer settings either but it was there at some time before.

BQ E4.5 (krillin) running Ubuntu 16.04 (r96)

![no-printer-in-ss](https://user-images.githubusercontent.com/30233652/41500747-f12cf83c-7197-11e8-82a0-afabc8c36f06.jpg)

See Printer is not between Battery (Batería) and Phone (Teléfono)

**Comment by Flohack74** [comment]
Yes we need to disable it probably, due to too large root fs. It will come back probably at OTA-5
