### ISSUE TITLE
[xenial] Camera app doesn't work 

### ISSUE THREAD

**Issue by padraic7a** [ubports/ubuntu-touch#638]
Bug Report

- Device: BQ M10 frieza
- OS: 16.04
- Channel: Devel
- Build: R86

### Steps to reproduce

Try to open the camera app

### Expected behavior
Camera app opens

### Actual behavior
The camera app doesn't open, or generate an error message. 
The splash screen appears and the blue wheel spins merrily away. 

### Logfiles and additional information
http://paste.ubuntu.com/p/B8Hw3pVCFj/

**Comment by padraic7a** [comment]
Hi @Flohack74 - the device is Frieza, I have updated the issue to add that in.

**Comment by Flohack74** [comment]
Thanks I will NEVER get them right!!!

**Comment by hoh61** [comment]
Dear Padraic7a,

I had the same problem. The reason is you have two camera apps installed. You may have also two camera icons on your application window. At the end from your logfile I can see that you are using the camera app from the open store. This software is generating the problem. If you can remove this properly, then you can use the generic camera which is shipped with the UBport image. This is working fine!
(check the last entries of [https://github.com/ubports/ubuntu-touch/issues/623](url))

**Comment by Daniel20000522** [comment]
Confirmed on Nexus 4 xenial dev r85

**Comment by padraic7a** [comment]
Hi @hoh61 , 

That's a funny one, I don't have two camera icons on my application window. Or rather I do, but one is in the shortcuts and I just have one camera icon in the applications list.

I guess I must have updated the camera from the OpenStore.

I do have two versions of a number of other apps as documented here: https://github.com/ubports/ubuntu-touch/issues/496

**Comment by hoh61** [comment]
my proposal:

remove the version from the open store:

> sudo click unregister  com.ubuntu.camera

After that reboot the device. You should still find an icon for the camera.  This should point to the working version of the camera app.

For me it worked.

**Comment by NeoTheThird** [comment]
Caused by #496.
