### ISSUE TITLE
Switching a Meizu MX4 to UBPorts OTA?

### ISSUE THREAD

**Issue by afettouhi** [ubports/ubuntu-touch#692]
This not release a bug report or an issue but more of a question because I am unable to find an answer to my question looking through the documentation etc. I have a Meizu MX4 with Ubuntu Touch installed updated to the last official OTA that Ubuntu released. How do I switch this over to using Ubuntu Touch and OTA's from UBPorts? I saw that OTA-4 was just releaed from UBPorts and I wanted to try it. If this issue does not belong please provide an appropriate link to where I can get an answer to my question.

PS. Final question about Ubuntu Touch in general. The touch screen is busted (50 pound dumbbell accidently grazed it) on my Meizu MX4 so I can't unlock it at all. Is there a way to unlock the device through USB?

**Comment by NeoTheThird** [comment]
Do i understand it correctly that you are on the latest version from Canonical? In that case, you will have to use the [UBports Installer](https://github.com/ubports/ubports-installer/) to switch over to the UBports version of Ubuntu Touch.

OTA-4 is not released yet. What was published today is the first *release candidate*. See the blog post: https://ubports.com/blog/ubports-blog-1/post/ubuntu-touch-rc-ota-4-148

The release candidate is a weekly build before official release. See the documentation for more info on our release schedule: https://docs.ubports.com/en/latest/about/process/release-schedule.html

> Busted touchscreen

That is a problem. It depends on various factors, since I do not have an MX4, i do not know how well the recovery works. I'd refer you to forums.ubports.com for that question if you don't mind.

**Comment by afettouhi** [comment]
Yes, you are correct I am on the latest OTA version from Canonical. Ahh, so there an installer for UBports many thanks for the link. I will post my question regarding the busted touchscreen on the forum to see if somebody has an idea how to unlock it.

**Comment by NeoTheThird** [comment]
Great, good luck!
