### ISSUE TITLE
Prompt users to re-install all apps on first boot after upgrade

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#706]
### Description of the feature
Can't decide if this fits as a feature request or as a bug report but let's settle with feature request :smile: 
When users upgrade from OTA3 to OTA4, OpenStore and/or system settings app should offer updates to all apps that has a xenial version available from the store. Without this, many users will be confused why their apps doesn't work and when figure it out, it would require them to manually check each of their installed app from the store.

**Comment by NeoTheThird** [comment]
We could avoid this if we made sure the xenial versions have higher version numbers, then updates would show automatically. @bhdouglass Do you think it could be an idea to force xenial version numbers to always be higher than the vivid version numbers for new releases? Also, it might make sense to make xenial the default (at the moment it is not possible to publish xenial-only builds, maybe we could make it so it is the other way around?).

**Comment by nikhilbhalwankar** [comment]
Looks like this is happening because Openstore itself does not get updated to the latest version once upgraded to 16.04 RC. I have opened an issue #725 for this.

**Comment by NeoTheThird** [comment]
Should be fixed: https://github.com/ubports/ubuntu-touch/issues/694

Leaving this issue open until we have feedback from @bhdouglass on the question above.

**Comment by bhdouglass** [comment]
We can't really force xenial versions to be higher than vivid versions because we leave the versioning up to the developer. But to fix the problem here, it might make sense to have a script that runs during/after the upgrade to check all the apps for xenial versions and upgrade to them, that way it happens without user intervention, then you avoid the whole "why aren't my apps working?????".

As to your other point, vivid is still the default because xenial isn't stable yet. I don't want people to forget about vivid just yet. As soon as xenial is stable I'll be making plans to move over to it being the default and deprecating vivid.

**Comment by NeoTheThird** [comment]
> But to fix the problem here, it might make sense to have a script that runs during/after the upgrade to check all the apps for xenial versions and upgrade to them, that way it happens without user intervention, then you avoid the whole "why aren't my apps working?????".

Should that be a system-service that runs automatically, a system-service that you can trigger manually (eg from the system-settings update section) or something the OpenStore App takes care of?

> As to your other point, vivid is still the default because xenial isn't stable yet. I don't want people to forget about vivid just yet. As soon as xenial is stable I'll be making plans to move over to it being the default and deprecating vivid.

I guess that makes sense, but we should think about reaching out to the developers to re-build their apps for xenial somehow. Maybe we could put a big angry red note in the "Manage apps" section of the openstore webinterface that only shows up if you have apps that are vivid-only? With a link to a post explaining the important news for app-devs on xenial. What they have to do (eg. re-compile for Qt 5.9), what they should do (eg. bump the version number, framework, and apparmor policy) and what they can do (eg. use PyOtherSide from the system image rather than shipping it in the package, use QQC2).

**Comment by NeoTheThird** [comment]
The goal should be to have as many apps work on xenial as possible when OTA-4 hits the shelves...

**Comment by Flohack74** [comment]
I think the best would be to mass-mail them... Lots of devs will not look into Openstore that often. Maybe we can encourage a few of them to also come back to aged apps and get them interested again to keep them updated.

**Comment by bhdouglass** [comment]
@NeoTheThird it probably makes most sense to allow the system to do this on first boot to xenial after an upgrade.

I think mailing all the OpenStore app devs makes sense, let them know that xenial is coming and such. We should come up with some verbiage to send out.

**Comment by UniversalSuperBox** [comment]
We already have the Wizard in Unity8 for the OOBE of the phone. It's a full-screen experience that takes users through the first-time setup of their phone. I'm working on making a page for this titled "Update Apps" which shows an update for every app from the OpenStore. Marius has implemented a new call on the UpdateManager which requests a list of all updates. The page is almost working, but it's not quite right...

![image](https://user-images.githubusercontent.com/21966173/42726099-7633d876-8754-11e8-81bc-8a5c75424a99.png)

Just some trouble with anchoring. Once that is fixed up, I'll figure out how to get the Wizard to run after the OTA-3 to OTA-4 upgrade. If users skip this, they won't be able to blame the system for their apps not working...

**Comment by Flohack74** [comment]
@theotherone1985 The assistant for the App upgrade has finished implementation and now is under review for merge to devel image. As soon as we got it build you are invited to test it ;)

**Comment by theotherone1985** [comment]
👍🏼

**Comment by NeoTheThird** [comment]
Closed in https://github.com/ubports/system-settings/pull/71
