### ISSUE TITLE
AnBox install completes but doesn't leave an obvious 'AnBox' icon on the UbuntuTouch desktop

### ISSUE THREAD

**Issue by paul-hammant** [ubports/ubuntu-touch#715]
I updated my MeizuPro5 to 16.04/devel yesterday.  Today I ran through the steps in https://docs.ubports.com/en/latest/userguide/dailyuse/anbox.html and I can't see that AnBox was installed.

The above page would be better if it highlighted that "Settings" is really Android Settings, and in there you can click on apps to see the list of apps that came with AnBox. It might also be worth repeating FAQ items from https://anbox.io/ .... specifically that the PlayStore is not integrated.

**Comment by dellgreen** [comment]
yer i get nothing at all, not even 'Settings'

**Comment by PhoenixLandPirate** [comment]
Its been stated a few times that their are no GAPPs with anbox, perhaps we might bring microG a free google play services alternative, and f-droid, but I don't think its clear yet.

**Comment by UniversalSuperBox** [comment]
Anbox is still experimental and apps installed with it will appear as just another app rather than as a bespoke "anbox" app. If you believe there is a documentation issue, though, please head over to https://github.com/ubports/docs.ubports.com or hit the "Edit on GitHub" link in the upper right corner to edit the page!
