### ISSUE TITLE
Bacon: Screen rotation not working

### ISSUE THREAD

**Issue by tomoqv** [ubports/ubuntu-touch#74]
Bacon on 15.04/devel r10

Since the switch to 15.04/devel, the screen no longer rotates on my OPO. I have tried to disable and enable screen rotation in settings, but the screen remains in portrait mode all the time.

**Comment by tomoqv** [comment]
Bacon on 15.04/devel r15 and r16
Rotation did work for a while, in r12-14 I think. The latest two updates not.

**Comment by mariogrip** [comment]
Fix released: https://github.com/ubports/android_device_oneplus_bacon-1/commit/4aff5f39bad9e2f3457002d3bb698c78f5a20c4a and https://github.com/ubports/android_device_oneplus_bacon-1/commit/387d18b58aaa46f030b6643ef3d6f7ec3da72003

**Comment by tomoqv** [comment]
This is odd. I am getting this issue with like every other update. After a reboot, rotation worked yesterday on r17, but today after updating to r20 rotation doesn't work. I have rebooted once, but still no rotation.

**Comment by tomoqv** [comment]
I am now on 15.04/devel r26, updated this morning. Screen rotation is not working, not even after a couple of reboots.
![image20170612_111357074](https://user-images.githubusercontent.com/13762919/27027237-e516f3ae-4f60-11e7-8d05-8e7c5450dea2.jpg)

**Comment by tomoqv** [comment]
This is still kind of random. Updated to r29 this morning and rotation worked. However, when I noticed that location wasn't working I rebooted. After that location works, but rotation does not.

**Comment by PetHH** [comment]
hmmm, i found the rotation not working whatsoever after installing 15.04 armhf (20170610), which is my initial install on the OPO. So i'm kind of newbie to this, be patient. 
switching rot-lock or reboot didn't change it to working.
when i let the phone laying around over the weekend until it shut-off due to low-battery, i switched it back on at sunday and had a working rotation. 
that worked until i installed, configured and restarted the phone, then rotation went back to dead. even switch rotation-lock on & back off did not improve the sit. 
I let it discharge until the end yesterday, and now its back working.
????

**Comment by rockybulwinkle** [comment]
What I have found so far is that reinstalling the stock android image and allowing it to boot, before running the ubports installer, fixes the issue. Though that isn't an ideal fix because it neccesitates wiping your data.

**Comment by Flohack74** [comment]
Is this still an issue?

**Comment by tomoqv** [comment]
I currently don't use my OPO, but I can't recall this being an issue last time I did.

**Comment by Flohack74** [comment]
Ok then we close for now...

**Comment by erik-kueng** [comment]
Since updating to 2019-W09 on my FP2, the screen stopped to change orientation
