### ISSUE TITLE
Feature request: Long press App on Dash scope opens OpenStore to that app

### ISSUE THREAD

**Issue by nfsprodriver** [ubports/ubuntu-touch#741]
### Description of the feature
Long press App on Dash scope opens OpenStore to that app

### Illustrations
Since the deprecation of the Ubuntu Store long pressing an app on Dash scope leads the user to a nearly empty page with just the option to uninstall or open the app. Having all of the details like before would be much more helpful. Avoiding the development of the fancy Dash scope the easiest way to do that would be a direct link to the OpenStore (url-dispatcher), right?

**Comment by PhoenixLandPirate** [comment]
This doesn't sound like an ideal situation, especially for apps you download outside of the open store.

**Comment by doniks** [comment]
@Phoenixlandpirate but is that a relevant use case? How many apps does a regular user realistically install outside of open store. I'd argue very close to zero. 

As long as there is some vaguely consistent result (not found) I think we're good and we improved the user experience for 99.9% of use cases

**Comment by nfsprodriver** [comment]
@PhoenixLandPirate I see your point, so let's generalize that and say: It would be better to have more than just the above two options. So if OpenStore information is available, it should be loaded, else it should be grabbed by apparmor, manifest, filesystem etc...

BTW, does anybody know where to find that long press action declaration? In unity-click-scope repo? Would like to do some experiments soon...

**Comment by PhoenixLandPirate** [comment]
Their was a conversation we had a very long time ago, where you could hold onto the app, then a context menu would come up, with several different options such as taking you to the apps specific location in system settings, its own scope, the pin ability, the option to uninstall the app straight from their, etc.

I can't remember what other things where discussed, but if you made it so long holding an app, only takes you to the open store, then this limits our options and choices.

Also talking in current content delivery's doesn't seem like a good idea to me, we already have several ways to install software, be that apps directly from the openstore, click packages people send you to test out or your own apps, libertine apps (when the shelf is back, libertine apps sit in the same place as your click apps), and your apps which come from the OS upgrades, aka system apps.

This also ignores future possibilities, we have several Linux os's on mobile, what if someone decides to use Purism's gnome software store, or plasma phones store?

Every none core app can uninstall, every app can have its cache deleted, every app can have its own settings page, and every app can be pinned.

To keep this agnostic as possible is a good goal, consider if you used an android phone, and everytime you held onto an icon, it took you to the google play store, instead of its default "edit" and "app info" if you never used google play, (f-droid, Amazon, or other 3rd party stores) then android would be more difficult for you to use.

**Comment by doniks** [comment]
@phoenixlandpirate thanks for the elaboration! I understand the proposal better now.

I guess one might still consider a short term small tweak (go to open store), and later a richer interaction. But that's up to developers, designers. All the aspects you mention do make sense to me now!

**Comment by Flohack74** [comment]
Just to add to the conversation: Openstore is not an integral part of UBports, but a different project, different people, not part of our organization. In fact, someone else could create another store (FunnyStore, limited only to funny cat apps for example), and then supply an app to host this App store on the phone.

So UBports will not favor a specific store as such, therefore deep system integration with the openstore is probably not happening. That said, the system update menu is now hardlinked to openstore. We will discuss this further, and see when there are other stores upcoming ;)

**Comment by NeoTheThird** [comment]
@Flohack74
>Openstore is not an integral part of UBports, but a different project

While that might be the case on paper, it's not really how it works in reality. Whe ship the openstore as a pre-installed app and use the system-settings updater section to poll the openstore-api for updates. I don't see any issue with at least adding a button to open the open-store page for apps that come from the openstore.

**Comment by Flohack74** [comment]
Yeah but how to figure out about this? We do not have the information locally.

**Comment by PhoenixLandPirate** [comment]
I thought system settings wasn't hard coded for openstore, as we have had discsions about how they should link without being hard coded, and stifeling competion.

As I genurally reply, Open Store is current, but what if theirs an app not published on the open store, but is published in Discover? we will probably have the ability to install both app stores, so if you want the app from discover, you should be able to install it, then when the app updates, system settings should be able to see that that app needs to be updates and act upon it.

This is a different situation, but it all comes back to being as platform diagnostic as possible, and thus, if you download something from discover, it should be treated the same as anything you've downloaded from openstore.

**Comment by BlueKenny** [comment]
What do you think about the idea to show the informations from the click manifest ?

**Comment by Osndok** [comment]
I ran into this earlier when I thought I could discover the app version number through the touch ui. There is a lot of info we could show here (including the openstore url & publisher url) and various controls, but jumping into the openstore is probably not the way to go long-term.

Here is a comparison between the current app-info screen, and the android analog.
![ubports-better-appinfo-5bca0a8e](https://user-images.githubusercontent.com/80066/47232511-803efe80-d395-11e8-8dd4-70ed90371ded.png)

**Comment by dobey** [comment]
The scope preview and the Android system settings page for an app are not analogous. When you long press an icon on the home screen in Android, it starts the drag event to rearrange or remove from the screen.

The scope should be showing a lot more info. If it doesn't, then the app's .desktop file is probably pretty barren. The scope could probably be updated to get app info from open-store, as the old store is dead now. And perhaps a button to go to the store. But either way, scopes are going away in a few months, so it's best to not do too much there.

**Comment by UniversalSuperBox** [comment]
The Unity8 dash has been removed, this issue is no longer valid.

You might be pleased to know that long-pressing on an app in the Drawer opens the OpenStore, though :D
