### ISSUE TITLE
Compile core scopes for 16.04

### ISSUE THREAD

**Issue by PhoenixLandPirate** [ubports/ubuntu-touch#759]
Scopes such as the Photo and today scope no longer work on 16.04, to get at least the core scopes back up and running would be great.

**Comment by UniversalSuperBox** [comment]
The scopes you listed were removed from the images because no one is maintaining them. See https://github.com/ubports/ubuntu-touch/issues/722 and its accompanying PR, https://github.com/ubports/ubuntu-touch-meta/pull/13. It should still be possible to install them as clicks from the OpenStore if a maintainer appears and puts them there.

Getting these scopes back into the image would require:

1. A maintainer for the Scope subsystem, unity8-dash, and the SDK components required.
1. A maintainer for the scopes themselves.
