### ISSUE TITLE
Unclear usage of ubports-qa

### ISSUE THREAD

**Issue by doniks** [ubports/ubuntu-touch#772]
- Device: deb
- Channel: devel 
- Build: 25

### Steps to reproduce
create a pull request for some core software (ubuntu-app-launch)
wait for the CI to build it successfully
connect to device with adb 
run one of 
```
ubports-qa ubuntu-app-launch 6
ubports-qa ubports/ubuntu-app-launch PR-6
[...]
```
or any other guesses or combinations for repo and pr 

### Expected behavior
get the artefact from the pr installed

### Actual behavior
cryptic errors or no errors, no clue how I should use ubports-qa, maybe the problem is in front of the screen, but I can't find it :(

**Comment by NeoTheThird** [comment]
Does this make more sense to you now, @doniks? I tried to explain it as well as possible, but if you think it's necessary, i can take another swing at it. The problem is, that the users somehow need to understand our branch naming and ppa system to use this, but i guess there's no way around it, unless we would just download the deb, which is kind of a hack...

**Comment by doniks** [comment]
muuch better yes. still the odd question, but that can be dealt with elsewhere. thx!
