### ISSUE TITLE
Show libertine apps in the scope

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#782]
It would be a lot more user-friendly to show the libertine apps in the normal scope.

- [ ] Remove legacy apps scope
- [ ] Show the libertine apps in the normal scope

**Comment by TartanSpartan** [comment]
Are there instances where the app icon or name might be ambiguous between a mobile app and a deaktop app?

**Comment by arubislander** [comment]
> @TartanSpartan said:
> Are there instances where the app icon or name might be ambiguous between a mobile app and a deaktop app?

Well, the (Gnome?) Terminal desktop app and the Terminal touch app comes to mind.

**Comment by ruedigerkupper** [comment]
Let me think:
calculator, telegram, (audio)recorder, (gnome)clock(s), writer
and pretty much any web app that's named after its site, like twitter, youtube, vimeo, etc.

So, yes, we must be prepared for ambiguities.

**Comment by ruedigerkupper** [comment]
One way of resolving this would be to mark the icons of desktop-apps with some sort of small graphics, like an „X“ or a little monitor in one of their corners.
Or to mark their names, like „Terminal (desktop)“.

**Comment by NeoTheThird** [comment]
That's an issue all distributions face. If you install ten different terminal apps on your ubuntu desktop, you won't be suprised to see ten terminal apps show up in your launcher. But that's hardly a problem. Mate-terminal has a different icon than Konsole, the gnome-terminal looks different from terminator. You can even install the same application multiple times using different methods, but if you do that, you can't be suprised to see a deb, appimage, flatpack and snap version of that app show up. That's exactly what you want.

**Comment by ruedigerkupper** [comment]
Right you are. Still it will be a nice hint to the user indicating if that icon will launch an application designed for mobile usage or for the convergent desktop. (Most desktop apps will not be usable in mobile view.)

**Comment by mateosalta** [comment]
perhaps, another section in the apps scope, like "favorites, apps, legacy, anbox" all in the same scope, but divided in categories

**Comment by zubozrout** [comment]
@mateosalta Hmm, not a bad idea, I like it. Though it would be great to have an option somewhere in settings to perhaps allow for a more mixed view (favorites + rest) or for a more divided one as you suggested.

**Comment by dobey** [comment]
This has several problems, and we explicitly avoided this in unity-scope-click because of that. This is not the same issue as all distributions face. When you make a chroot in a traditional distro, and install some GNOME packages in it for example, those packages do not also show up in the GNOME on your host. Apps installed in your VMs/containers/chroots do not show up in the main apps menu on your host system.

With libertine, you can not only have an app that's installed in the host, duplicated in a container, but you can have N containers, of which M may have the same apps installed. People using libertine need to have some way to differentiate which container an app is running in, as well as to differentiate it from an app in the host system. Further, the current libertine scope has some items filtered out, which get installed but should not show up in the special case of libertine, as X apps.

**Comment by NeoTheThird** [comment]
Due to the results of this discussion, the development team decided against doing it this way. Once we move to the latest unity8 (which no longer has unity8-dash and scopes), this question will be raised again. For now, having it in a scope is good enough.
