### ISSUE TITLE
Perform a full upgrade if the system has been updated using apt

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#785]
Since we are normally using deltas to upgrade from one release to the other, it can cause issues when users make heavy use of apt. Could we work around that issue by checking if the rootfilesystem has been modified, and then download a full upgrade if necessary? We could simply check if either the apt sources list or the `/userdata/.writable_image` flag file exist. Not foolproof, but it might work. Or am I missing something?

**Comment by doniks** [comment]
sounds good to me

**Comment by mariogrip** [comment]
Sounds good, but might be annoying for some if we force this behavior. it would be good if we have a popup saying, "I see you have used apt, do you want to do a full upgrade to keep your sanity?". since forexsample I don't want to do a full upgrade if i just installed qdbus and only that.

**Comment by NeoTheThird** [comment]
sure

**Comment by Flohack74** [comment]
@ShadowEO Currently we completely replace the root filesystem. Not only dpkg entries are lost, more or less everything that you did to the /etc directory e.g. - Thats a different philosophy than on a desktop, yes. But it is also much more inconvenient on a mobile device if you have issues with the system or booting etc. after an update went wrong.

So all efforts towards keeping the user-modified state need to be done with great care. Also I think if we want to have such a feature, we need to change the way of update distribution, we would need to go to normal apt mode more or less instead of full rootfs images, and that would mean the recovery needs to download the packages? But no network connection in recovery. Or who prepares the update then, the running OS? Also, as we are on a mobile device, if you allow OTA update incrementially, how do you guarantee consistency if the download gets interrupted, disk is full etc.? Where do we store the debs before update? etc etc. I see this as a huge effort, and I am not sure it will help more than it might harm.

**Comment by ShadowEO** [comment]
@Flohack74  Thanks for elaborating on this for me, I understood that the update replaces the system image, hence why the data partition keeps that etc folder for overrides.

And you've got great points there. Though I could see UT storing the deb packages under /data/ temporarily (similar to how the init overrides are stored) but then you're absolutely right, how would the system-image-upgrader know what to do? 

Would Delta updates be a possibility? Where only changed files are updated, and even then, updated similar to a patch. Wouldn't this make it possible to simply patch the on-device dpkg info repository? Sorry if I'm asking a lot of questions, I'm curious is all :)

And you're right, this would likely be a huge effort to add support since it would require changes to the recovery image, system-image-upgrader, etc (unlike you're average user, I do understand development and understand the amount of work this would take to get implemented, I was by no means trying to say this would be a simple task, otherwise I'd probably have implemented a dirty kludge myself on my own device for testing). As I said in my previous comment, I completely understand if this is unfeasible, and I thank you for elaborating on the reasons as to why it would be unfeasible to implement. You've definitely sated my curiosity, and I'm sure you've thoroughly explained why this isn't a viable solution to system-image updates enough that others will be sated too.

**Comment by Flohack74** [comment]
@ShadowEO Thx for the flowers ;) - Well at the end, everything is possible, since its software. The question is just what benefits it would bring for us, justifying the amount of work to put in. Currently I do not see many benefits. I know that many people think about Ubuntu Touch as "Ubuntu for mobile devices means its the same like on a notebook". But actually its more like other mobile phone distros.

What we will have to do however is a way how to post-install debs that are not fitting in the image since the cache partition runs over. This happens already on devel builds if we are not careful, and so it would be nice to get ideas, how we can integrate debs "sideloaded" after the initial image has been installed. Should this happen in recovery still? During boot of main? Later on etc.

Opinions plz.

**Comment by ShadowEO** [comment]
Honestly, I think this could possibly happen under recovery, we could chroot into the system image and run dpkg on the "sideloaded" debs to install them, but you are correct, what happens if Cache overflows? 

Perhaps though, the best option would be a pre-boot stage to finish updates, similar to what Windows does after applying updates? It would need to have a separate startup screen indicating that it's doing update cleanup so the user doesn't think it's frozen on boot though we do still run into the problem of where to store the debs, as the data partition can't always be relied on to have enough free space.

Though that could be solved by disallowing updates until storage has been freed up, similar to how Desktop Ubuntu does it if /var is full. 

OO! I just thought of something while trying to think of an idea for this!

Could we make use of OverlayFS for this purpose, similar to how OpenWRT does it's package system (the changes are stored in writable flash, while the original system sits in a read only romfs partition)? That way, the underlying system image doesn't need to be touched, and user changes can be stored completely separate. 

I'm not entirely sure how OverlayFS does it's work, but I believe it stores the modifications only and merges them with the underlying filesystem's version, so we could theoretically use that to perform most of the work if we use it to overlay the /var/lib/dpkg folder root. We'd also be able to dump user applications by erasing the overlay if it's required.

It may require a wrapper around dpkg to allow for package blacklists (like packages known to break during upgrades or similar) or to ensure the user's packages aren't pulling in an older version of something contained in the ROM. 

I've never undertaken a project of that magnitude before, so I can't speak as to the effort it would involve, But that may be a good way to go about handling user installed Debian packages.

**Comment by Flohack74** [comment]
Ok nice, we should pick this up in a separate "working group / experiment". Maybe you want to start a Forum thread, because now we leave Github´s area of usability ;)

**Comment by doniks** [comment]
> Maybe you want to start a Forum thread

Please link it here when you do

**Comment by Arc676** [comment]
Any updates on this? Losing all the `dpkg` data means that if you install tools such as `git`, `gcc`, and `make` via `apt` you have to reinstall these after every update.

**Comment by dobey** [comment]
@Arc676 That is why you should create a libertine container instead, and install them there.

**Comment by Arc676** [comment]
Got it. Thanks @dobey
