### ISSUE TITLE
Welcome Wizard: Should automatically advance after network connection

### ISSUE THREAD

**Issue by bhdouglass** [ubports/ubuntu-touch#845]
When selecting a wifi network in the welcome wizard it would be nice if it automatically advanced to the next page after a network connection is made.

**Comment by UniversalSuperBox** [comment]
This issue should be fairly easy to fix if you have an Ubuntu Touch device. Even if you don't and have some QML know-how, you can get through this.

Check out [30-wifi.qml in Unity8](https://github.com/ubports/unity8/blob/xenial/qml/Wizard/Pages/30-wifi.qml). The QML has a property called `connected`. Every time this changes, it will fire a signal (`connectedChanged`). You can create a handler for this signal (`onConnectedChanged: {}`) which checks if `connected` is true, then calls `pageStack.next()` if it is.

You can edit this QML directly on your device if you want. Mount the rootfs read-write and then edit the file (I think it's in `/usr/share/unity8/Wizard/Pages/`). To run through the wizard, run `rm .config/ubuntu-system-settings/wizard-has-run` and then `restart unity8`. You will need to forget your Wi-Fi network before doing that to see the Wi-Fi page!

If you're taking this on, please add a comment here to say so.

**Comment by UniversalSuperBox** [comment]
Go for it! Let me know if you have any trouble.

**Comment by UniversalSuperBox** [comment]
@dark-eye are you still interested in this, or shall we wait for another contributor to give it a shot? :)

**Comment by Arc676** [comment]
I can confirm that the fix suggested by @UniversalSuperBox works as expected on Nexus 5 running `devel` 16.04 (2019-01-11).

Added these lines to `/usr/share/unity8/Wizard/Pages/30-wifi.qml`:

```
    onConnectedChanged: {
        if (connected) {
            pageStack.next()
        }
    }
```

Notes: the wizard appeared immediately, even without restarting Unity 8. Also, there was significant latency after the wizard exited, possibly because the device was actually already set up.

**Comment by Arc676** [comment]
@UniversalSuperBox Since you already knew how to fix this in October of last year, why didn't you? I'd be happy to make the edits mentioned in my last comment in the Unity 8 repository, but the fact that it's 5 lines and you didn't already do this suggests that there's more to this that I'm aware of.

I should add that I have no experience working on operating system components.

**Comment by Flohack74** [comment]
We want to drag in more people into development with easy tasks. When we solve all easy tasks by ourselves, how we can ever grow, since people have no starting point. So yes, patches welcome ;) - And strictly spoken its not a real OS component but rather part of the display environment unity8, so you cannot break that much ;)
