### ISSUE TITLE
Wrong date (Expected + 1) at latest updates

### ISSUE THREAD

**Issue by Benni777** [ubports/ubuntu-touch#881]
Environment
Nexus 4 (mako), 16 GB
Ubuntu 16.04 (2018-09-12)
Channel: dev

Steps
Open Settings (Einstellungen)
Select Updates (Aktualisierungen)

Expected
Ubuntu touch
Version 160
Updated on **12.** September

Actual

Ubuntu touch
Version 160
Updated on **13.** September

All dates have the expected date  +1 day.

**Comment by Arc676** [comment]
Can confirm this also happens on Nexus 5 (hammerhead).

**Comment by Flohack74** [comment]
Are you sure it is not https://github.com/ubports/ubuntu-touch/issues/685

**Comment by Arc676** [comment]
Might be related. But these dates aren't from the 1970s. I think something's changing the update dates too. I'm willing to bet that tomorrow, the date on which I supposedly installed the latest update is going to become Sept 16. I'll update this thread if it happens.

In these screenshots, we see that UT 586 was installed on September 15 (that's today, so that's obviously wrong). After downloading and installing UT 589, suddenly both updates were installed today.

### Before updating to 589
![Before updating](https://user-images.githubusercontent.com/30745465/45583391-9e5e9e00-b8c1-11e8-9e4b-96acebf9c58f.png)

### After updating to 589
![After updating](https://user-images.githubusercontent.com/30745465/45583392-a1598e80-b8c1-11e8-86ec-dc32c7f3be34.png)

**Comment by Arc676** [comment]
As expected, the date at which I updated to 589 has changed. I updated to 589 yesterday, but now it says I updated today.

![Screenshot](https://user-images.githubusercontent.com/30745465/45597832-ed93f400-b9d1-11e8-8062-027663a04df4.png)

**Comment by Flohack74** [comment]
Yes this is a bit wonky ;) - I think still we can track this in #685 to reduce amount of tickets. If those issue needs additional info, plz put it there ;)
