### ISSUE TITLE
clicking on lock button reboots nexus 5 Ubuntu 15.04 (r3)

### ISSUE THREAD

**Issue by skeever** [ubports/ubuntu-touch#884]
nexus 5 Ubuntu 15.04 (r3)

### Steps to reproduce
When the phone is active short pressing power butting brings up menu 

Power off
Reboot 
Cancel

No matter what option I select (including doing nothing) the phone reboots

### Expected behavior
My expectation is that tapping power button would cause phone to blank the display instead of forcing a reboot. 

### Actual behavior
displays broken boot menu that reboots my phone no matter what

**Comment by skeever** [comment]
I will clean it and see if the situation improves.

**Comment by skeever** [comment]
Cleaning it didn't help, I used rubbing alcohol and a q-tip and was able to slip some paper around the opening. I guess it is still possible that there is an issue with the switch, clean or no clean. 

If I am the only one reporting this, it's probably HW. Thank you for your help and your suggestion. Meanwhile, do you have any thoughts on a work around? Is there a documented way to change the behavior of the buttons that you know of? I searched and wasn't able to find anything. 

Thanks again!

**Comment by Arc676** [comment]
Well I also have a Nexus 5 and have the exact same issue, but I'm pretty sure it's a HW issue.

My current workaround is as mentioned in my previous post. If I see the shutdown menu appear even though I'm not holding the power button, I quickly jiggle the button and click it a few times to make sure it isn't jammed.

The problem seems less severe if I don't press hard on the button and press in the center so no one side gets all the weight.

**Comment by dobey** [comment]
The power button just goes bad over time. It's a hardware fault. You cannot change the behavior of the hardware fault (the button being trapped in closed circuit state) through software. The problem will get worse in the future, until the point where the button must be replaced, to be able to function normally again.

**Comment by skeever** [comment]
Thanks again to everyone that replied. I think you're all right about the button crapping out. Now I know why I was able to get it for $50!
